### ISSUE TITLE
Show a popup dialog to choose the right simulator if needed

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#1]
When two Simulators with the same screen ratio are open, RocketSim can't decide which one is the currently focused one. This could lead to a "bug" where the action is performed in the wrong simulator.

By showing the two simulators with the same ratio as a decision alert we can solve this issue in a better way.

**Comment by iSapozhnik** [comment]
Just as an idea... Why not showing a dropdown menu with different simulators which are currently booted?

**Comment by AvdLee** [comment]
Yes, that’s kind of the idea!

**Comment by AvdLee** [comment]
This is no longer needed!
