### ISSUE TITLE
Show touches in recordings does not seem to work

### ISSUE THREAD

**Issue by djavan-tagheuer** [AvdLee/RocketSimApp#101]
**Describe the bug**
The show touches in recordings does not seem to work: we can't see the touches in the video.

**To Reproduce**
1. Enable the "Show touches in recording" param
2. Record a video where you perform some clicks and touches on the simulator
=> Touches (and pan moves) are not visible in the video

**Expected behavior**
For what I understand of this feature, the touches should be displayed (as they are on the simulator when the Simulator's preference `Show single touches` is enabled).

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3
 - Version 4.1.1

**Comment by AvdLee** [comment]
@djavan-tagheuer so, if I understand correctly, you can see the touches in the simulator during the recording, but the touches aren't visible in the output video. Is that correct?

Would you mind sharing me a diagnostics report from the settings about page?

**Comment by djavan-tagheuer** [comment]
Hi @AvdLee .
I pressed the `Send Diagnostics` button. Nothing happened, I hope you received it 😉

**Comment by AvdLee** [comment]
> I pressed the Send Diagnostics button. Nothing happened, I hope you received it 😉

Ah, it's built around the default Mac Mail app. Am I right you don't use Mac Mail? It should open a email compose window to send the attachments.

**Comment by djavan-tagheuer** [comment]
I'm using the default Mac Mail app. I'll try to reboot, to see if this changes anything 🤷‍♂️

**Comment by djavan-tagheuer** [comment]
After reboot, sending the Diagnostics works. However, touches record still does not work. 
I've updated Xcode in between, so I tested it first on Simulator 12.4 and now on Simulator 12.5.

**Comment by AvdLee** [comment]
I received your Diagnostics Report. I'll schedule seeing whether I can find the fix for this 🙂

**Comment by djavan-tagheuer** [comment]
I might I found what happened. I was not using the floating window, only enabling the touch record from the app settings. However, as you can see on the screenshot, the touch record from the floating window was disabled while the one in the settings was enabled.
Enabling the touches from the floating window worked and I now can record the touches!

<img width="657" alt="Screenshot 2021-06-03 at 16 49 38" src="https://user-images.githubusercontent.com/43636702/120665581-33e45680-c48c-11eb-84e0-b2c41f0d0c5a.png">

**Comment by AvdLee** [comment]
@djavan-tagheuer aaaah, that's a very clear bug. I should be able to fix that!

**Comment by AvdLee** [comment]
This is fixed in the next release. I was referencing the wrong preferences key 😅
