### ISSUE TITLE
Ability to change floating window position

### ISSUE THREAD

**Issue by dansimau** [AvdLee/RocketSimApp#102]
After I installed RocketSim (4.1.2 build 60), I was working on my app the next day and I saw part of a panel off the end of the screen. I thought maybe it was a hidden menu because I'd just updated to Xcode 12.5. Then I realised it was RocketSim.

<img width="490" alt="Screenshot 2021-04-29 at 11 09 49" src="https://user-images.githubusercontent.com/203031/116528593-4d6a0f80-a8dc-11eb-8496-e8f626a773df.png">

I typically work with the simulator on the right hand side of the screen, so it would be nice for RocketSim to work in this configuration (at the moment it seems fixed to the right of the simulator window).

**Comment by AvdLee** [comment]
@dansimau this makes total sense and should be relatively easy to fix. I'll add it to the roadmap!

**Comment by AvdLee** [comment]
This will be fixed in the next release: https://twitter.com/rocketsim_app/status/1416380381180354561?s=20
