### ISSUE TITLE
Incorrect video size for iPad Air 4th gen landscape - content cut off

### ISSUE THREAD

**Issue by Thomvis** [AvdLee/RocketSimApp#103]
**Describe the bug**
A video recorded of an iPad Air 4th gen simulator (Xcode 12.4) in landscape yields an incorrect video where part of the rightmost content is cut off:

https://user-images.githubusercontent.com/134170/117447534-f00a3a00-af3d-11eb-8d36-90e5732d0344.mp4

**To Reproduce**
1. Open an iPad Air 4th gen simulator
2. Record a video

**Expected behavior**
The video has the correct dimensions

**Screenshots**
See video above

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 14.4

**Comment by AvdLee** [comment]
Oh damn, that's that not good! Did you experience the same with other iPad simulators?

**Comment by Thomvis** [comment]
I tried with the iPad Pro 12.9” and that one was fine

**Comment by AvdLee** [comment]
This is fixed in the upcoming release. The resolution as noted in https://help.apple.com/app-store-connect/?lang=en/#/dev4e413fcb8 is not in the same aspect ratio, resulting in the wrong scaled export.
