### ISSUE TITLE
Add an option to position the image

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#104]
This speaks to `itself`:

![image](https://user-images.githubusercontent.com/4329185/117448494-1d0b1c80-af3f-11eb-855e-3e87104d0b4f.png)

**Comment by lj-dickey** [comment]
+1 for this enhancement!

**Comment by jaafarbarek** [comment]
I like the tool so much, but this is blocking me from using it with the designs I have in the app I am working on.
I wish there was an option as mentioned to position the design image.

**Comment by AvdLee** [comment]
This is upcoming in version 7.1.0!
https://twitter.com/rocketsim_app/status/1513901678717808653?s=20&t=rmGeKhqP3IpEr_nqs9IZmQ
