### ISSUE TITLE
Cannot edit deeplink groups

### ISSUE THREAD

**Issue by KsAvsFan** [AvdLee/RocketSimApp#105]
**Describe the bug**
I am not able to edit the groups I've setup for deeplinks.  I can create new groups, and add deeplinks to that (the currently selected, or new, group), but I cannot select existing groups to see the associated deeplinks. 

**To Reproduce**
1. From Preferences, go to Deeplinks tab
2. Try to select an existing group name to see associated Deeplinks
3. Selection is not indicated. Cursor is placed in label of Group name, but no associated deeplinks are visible. In this case, I selected the Content Page group, and one deeplink should be visible - Bellman Carts (see screenshots)

**Expected behavior**
I expect the Group name to highlight or show some sort selection, and the associated deeplinks configured to appear in the detail view

**Screenshots**
<img width="764" alt="RocketSim - Cursor in Group Name" src="https://user-images.githubusercontent.com/1811479/120372623-0907d000-c2dd-11eb-93c4-ea92dd664fac.png">
<img width="398" alt="RocketSim - Bellman Carts" src="https://user-images.githubusercontent.com/1811479/120372641-0d33ed80-c2dd-11eb-83ef-060a72b57cc6.png">

**Desktop (please complete the following information):**
 - OS:  OSX Catalina - 10.15.7
 - RocketSim: 4.1.2(60)

**Additional context**
I really like the functionality of RocketSim.  I've been using it for a couple months now for videos to add to Jira tickets and PRs, and for Deeplink Testing. It works great.  Just this one glitch I've encountered so far.

**Comment by AvdLee** [comment]
Closing this since we dropped support for Catalina
