### ISSUE TITLE
Convertion failed window can't be closed

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#112]
There should be a close button on this popup:
![image](https://user-images.githubusercontent.com/4329185/133607081-cfd0b6f4-f7f9-4894-ba27-01c661dcfb37.png)

**Comment by adurbalo** [comment]
It happens few times during saving Gif recording session (with duration at least 10-15 second)

**Comment by AvdLee** [comment]
This is fixed in the upcoming release
