### ISSUE TITLE
Save recordings to clipboard for easy sharing

### ISSUE THREAD

**Issue by jordibruin** [AvdLee/RocketSimApp#12]
I would like to be able to record and quickly paste the video into iMessage, Twitter or Slack. Any plans for adding this?

**Comment by AvdLee** [comment]
Yes, definitely! I'll add it to the roadmap

**Comment by AvdLee** [comment]
This will be released in 1.3.0. Unfortunately, Slack does not work yet. I'm going to fix that with https://github.com/AvdLee/RocketSimApp/issues/15
