### ISSUE TITLE
macOS: Onboarding stuck on screen recording permissions

### ISSUE THREAD

**Issue by ChiellieNL** [AvdLee/RocketSimApp#122]
I already had a previous version installed on macOS 12.0.1 and granted permissions for screen recording.

Then I updated to the TestFlight build 6.0.0 (76) and got into the onboarding again.
When I reached the page for screen recording permissions, I got stuck since they were already granted.

Tried to quit and relaunch the app, but again got stuck at the same page.
To solve the issue I disabled the permission (and choose to not stop the app) and re-enabled it again (again chosen to not stop the app). Then I was able to continue

<img width="1326" alt="Schermafbeelding 2021-11-26 om 09 16 50" src="https://user-images.githubusercontent.com/4691834/143549971-966106da-e551-462d-989e-07eb8e6364e7.png">

**Comment by AvdLee** [comment]
@ChiellieNL thanks for reporting this! I've experienced the same and figured it's related to TestFlight only, since it overwrites an existing App Store app. I'll verify a bit more!

**Comment by AvdLee** [comment]
Closing this as this is pretty surely related to TestFlight
