### ISSUE TITLE
Right rotated screenshot is upside-down

### ISSUE THREAD

**Issue by ChiellieNL** [AvdLee/RocketSimApp#123]
**Describe the bug**
When I have a right-rotated device, screenshots are upside-down (left rotated or portrait works fine)

**To Reproduce**
1. Rotate the device to the right
2. Make a screenshot

**Expected behavior**
A screenshot that matches the device

**Screenshots**
<img width="2176" alt="Schermafbeelding 2021-11-26 om 11 37 53" src="https://user-images.githubusercontent.com/4691834/143568419-b848ff34-6406-4957-a439-71aae402dc69.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Xcode 13.1
- RocketSim 6.0.0 (76)

**Comment by AvdLee** [comment]
I'm closing this as a can't fix. There's no way for me to find out whether you rotated your device right or left, which is why I just picked left rotations as a default. Limitations of sandbox app, unfortunately!
