### ISSUE TITLE
Touches appearing in the wrong place

### ISSUE THREAD

**Issue by btjones** [AvdLee/RocketSimApp#124]
**Describe the bug**
Touches are appearing in the wrong place on videos.

**To Reproduce**
1. Open any app
2. Touch some things
3. Save the video and watch it
4. Touches appear in the wrong place

**Expected behavior**
Touches appear where I clicked the simulator with my mouse.

**Screenshots**

In this video I am dragging the tiny thumbnails near the bottom of the screen but in the video the touches appear near the top of the screen.

https://user-images.githubusercontent.com/155808/145662721-243cf6be-807e-40fc-86e4-94cf229f0502.mp4

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.0.1

**Additional context**
 - iPhone 13 Simulator running iOS 15.0

**Comment by btjones** [comment]
Interestingly it appears closer (but still off) when recording on my laptop monitor instead of my external monitor:
https://user-images.githubusercontent.com/155808/145662955-9e8418f9-1db9-4d8b-978f-3622cb9953e7.mp4

I'm on a MacBook Pro (13-inch, M1, 2020) and my external monitor is 4k in case that is a factor here.

**Comment by AvdLee** [comment]
Interesting! This must be related to an external screen, indeed! On which side do you have your screen configured? And what resolutions does it have? That would allow me to reproduce this!

**Comment by btjones** [comment]
**Screen Sizes**
<img width="698" alt="Screen Shot 2021-12-13 at 10 41 44 AM" src="https://user-images.githubusercontent.com/155808/145850935-aaa707d6-63e2-4b1b-ae70-093e922ba91a.png">

**Screen Position**
<img width="780" alt="Screen Shot 2021-12-13 at 10 42 43 AM" src="https://user-images.githubusercontent.com/155808/145850964-c5156255-a867-4e8a-8de5-306134958b2d.png">

**Laptop Screen Details**
<img width="430" alt="Screen Shot 2021-12-13 at 10 43 23 AM" src="https://user-images.githubusercontent.com/155808/145851007-c03cc707-eee8-4c1f-bebf-1be640b99757.png">

**External Monitor Details**
<img width="439" alt="Screen Shot 2021-12-13 at 10 43 10 AM" src="https://user-images.githubusercontent.com/155808/145851070-1dc9ac5a-09b1-478d-a27a-0ffb25de7a95.png">

**Comment by AvdLee** [comment]
That's a great external screen ;-)

Thanks a lot, I'll try to reproduce this!

**Comment by AvdLee** [comment]
This will be fixed in 6.0.2, available tonight on TestFlight!

**Comment by btjones** [comment]
Thanks so much! Love the app.
