### ISSUE TITLE
Always show "finger" touch on screen

### ISSUE THREAD

**Issue by btjones** [AvdLee/RocketSimApp#125]
**Is your feature request related to a problem? Please describe.**
Sometimes touches appear and disappear very quickly which can make it hard to see what the user's action was in a video.

**Describe the solution you'd like**
It would be nice to have an option to always show a finger "touch" circle so that you could see where the "finger" is hovering/moving before it actually touches the screen. This would actually be the mouse pointer but using the circle appearance of a touch in the simulator. It would then change visually when actually touching the screen.

**Describe alternatives you've considered**
I've considered using other apps to achieve this goal but it would be much simpler to have it included in RocketSim

**Comment by btjones** [comment]
In ScreenFlow 10 this feature is called "Attention Effect" and is a gray circle that floats around the screen with your mouse.

<img width="308" alt="Screen Shot 2021-12-14 at 11 48 14 AM" src="https://user-images.githubusercontent.com/155808/146042510-93aebf95-a4e8-4f37-8c3e-db2863461c19.png">

**Comment by AvdLee** [comment]
Another example of how this looks when used in Principle:

https://user-images.githubusercontent.com/4329185/156150514-61ccccfe-4dd6-431b-8b5e-9617dae658bd.mp4

**Comment by AvdLee** [comment]
This will be included in the 11.0.0 release:
![CleanShot 2023-07-21 at 12 15 57@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/b1a87796-abc6-4c78-a56b-c52cb809c12f)
