### ISSUE TITLE
Additional Bezel Colors

### ISSUE THREAD

**Issue by haIIux** [AvdLee/RocketSimApp#137]
**Is your feature request related to a problem? Please describe.**
I'm trying to use custom bezel colors or more bezel colors then what is offered (black) or that I can find that is...

**Describe the solution you'd like**
As a pro users, custom bezel colors, much like the custom background colors would be a nice feature.

**Describe alternatives you've considered**
I've considered finding some method to alter the color or finding a replacement program.

**Additional context**
N/A

**Comment by AvdLee** [comment]
Thanks, @haIIux, I'll see what I can do!

**Comment by ArturoLee** [comment]
Customizable clay and semi transparent bezels would be great options. I just purchases Pro! Love this tool.

**Comment by AvdLee** [comment]
@ArturoLee can you elaborate on what you mean with "Customizable clay"?
Also, do you mean with transparent bezels literally having the device be a bit more transparent? I wonder what the usecase is for that 🤔

**Comment by ArturoLee** [comment]
Scratch the clay part. There are a way too many ways to customize bezels. Just being able to customize the bezel color would be great (with the option of transparency). It would mainly be useful for helping out with branding/marketing so it can match with backgrounds.

![IMG_3931](https://user-images.githubusercontent.com/13791726/150168057-f85431c7-a5af-47f5-8c0c-21a766c63cc9.jpg)

**Comment by AvdLee** [comment]
Perfect, this makes sense! I'll see what I can do here

**Comment by AvdLee** [comment]
I'm submitting 8.5.0 tonight!

![image](https://user-images.githubusercontent.com/4329185/184008708-88023cf3-47e1-4c02-8f67-9ab472503502.png)
