### ISSUE TITLE
RocketSim process gets into state that it's draining battery

### ISSUE THREAD

**Issue by markltownsend** [AvdLee/RocketSimApp#144]
**Describe the bug**
I noticed that my new M1 Max MBP was suddenly draining battery like my "old" Intel i9 MBP.  After looking at other options, opened Activity Monitor and saw that RocketSim was at the top of the list for Energy Impact.

**To Reproduce**
Unfortunately, not sure how it got into this state.  The interactions I've had with it have been mostly around trying it with the new Xcode betas by switching what version of Xcode it is using via the Preferences panel.

**Expected behavior**
RocketSim uses minimal energy when running in the background.

**Screenshots**
<img width="699" alt="Screen Shot 2022-02-09 at 11 41 03 AM" src="https://user-images.githubusercontent.com/395903/153279243-a3eede93-b543-4604-9b26-875c326cd38c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.2

**Comment by AvdLee** [comment]
I have actually noticed something similar on my M1 MacBook. There must be some background process running or not cleaned up correctly. Thanks for reporting in, I'm planning on working on this asap.

**Comment by AvdLee** [comment]
Top priority today! Refactoring with Instruments on my side. I want to get rid of this completely and have a high-performant application!

**Comment by AvdLee** [comment]
I've done a lot of improvements for the upcoming build which are likely going to help a lot in this regard. I'm going to close this issue for now and I'm going to reopen it when I think it's not yet solved.
