### ISSUE TITLE
Recording simulator stuck in buffering and won't stop.

### ISSUE THREAD

**Issue by yonaharel** [AvdLee/RocketSimApp#162]
**Describe the bug**
When tried to record screen in the simulator the timer didn't stop.
There was no way that I could close rocketSim (I didn't find it in the force close menu but the timer on the status bar was still there).
When moving the cursor to the status bar it was in loading animation constantly
had to restart my machine

**To Reproduce**
1. Press The record button 

**Desktop (please complete the following information):
MacBook Pro M1 Pro 2021 14 inch
 Monterey
12.0

**Comment by yonaharel** [comment]
Uninstalled and reinstalled and couldn't reproduce. maybe a one time bug?

**Comment by AvdLee** [comment]
There was a bug like this in a previous build but it got fix in the latest RocketSim version. Could it be that you were still running an old version of RocketSim before?
