### ISSUE TITLE
Dynamic type control

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#165]
Xcode allows easy changing the dynamic type size, but you'll always have to navigate back to the simulator. We could leverage the floating windows and enjoy a much better experience

**Comment by Sherlouk** [comment]
Subscribing for updates. This would a really helpful feature - I wonder about other accessibility features too like reduce transparency and more? ❤️

**Comment by AvdLee** [comment]
This will be fixed in 10.2.0, see: https://twitter.com/twannl/status/1649859478114770954?s=20
