### ISSUE TITLE
Allow overlay to be on the left of the simulator

### ISSUE THREAD

**Issue by bsrz** [AvdLee/RocketSimApp#166]
## Problem

I have my simulator on the left of Xcode, which means the overlay of the simulator is on top of Xcode's file navigator.

## Solution

A preference parameter to change the side of the simulator on which the overlay appears.

## Screenshots
![CleanShot 2022-04-15 at 12 12 14](https://user-images.githubusercontent.com/1077441/163594402-2df982a1-5ea1-4c4b-9785-cc40ecce22e4.png)

**Comment by AvdLee** [comment]
Related to #234. Would be nice to have a `Force at bottom` or `Force at left` setting

**Comment by AvdLee** [comment]
![CleanShot 2023-01-16 at 12 29 59@2x](https://user-images.githubusercontent.com/4329185/212598934-7206ff2e-5a41-43f2-9aba-b4a5361fa377.jpg)

Will be released in RocketSim 9.1!
