### ISSUE TITLE
Undefined spot in bottom left corner on recordings

### ISSUE THREAD

**Issue by ridmaur** [AvdLee/RocketSimApp#169]
When recording with bezels on and with touches, the final recording does show a spot (in my case, orange) in the left bottom corner of the final recording. See attached file. The spot disappears at the end of the video.

https://user-images.githubusercontent.com/2020923/164887596-1c3dc592-1fcf-42d9-b0cb-edb1fb5be447.mp4

.

**Comment by AvdLee** [comment]
@ridmaur which version of RocketSim are you using?

**Comment by ridmaur** [comment]
7.1.1 (98)

**Comment by ridmaur** [comment]
Any feedback on why this is happening? Could it be because I am using Screen Sharing to access the computer on which RocketSim runs?

**Comment by AvdLee** [comment]
@ridmaur this is a bug I need to fix, it's in the code of RocketSim. Working on a fix right now!

**Comment by AvdLee** [comment]
Up until now I could not reproduce it, but I found out it's only happening if you tap for touches, no dragging. Fixing now!

**Comment by ridmaur** [comment]
Thanks @AvdLee. When do you expect the issue to be available in update available in App Store?

**Comment by AvdLee** [comment]
I'm hoping the end of this week, but at least before the end of the month!

**Comment by ridmaur** [comment]
Thanks for the feedback. I’m about to release a new version of my app with in-app support using videos. So I hope rather sooner than later, but no pressure :-)

**Comment by AvdLee** [comment]
It's live now!
