### ISSUE TITLE
Show touches in the simulator

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#17]
It would be nice to be able to show touches in the simulator during recording

**Comment by AvdLee** [comment]
For future reference, the new preferences option in the Xcode 12 simulator to enable touches is not included in recordings. Therefore, a custom solution is required.

**Comment by rlaurb** [comment]
+1. As an instructional aid, the video needs to show what you need to do to achieve a result. What I'd like to see is a round spot (like the "finger" spots that show when you press the option key in simulator) that tracks the mouse and does something visual (like change color) when you click the mouse. This would allow the viewer to know exactly what you were doing in the video.

**Comment by Ariandr** [comment]
I'm looking forward to this feature!

**Comment by AvdLee** [comment]
@Ariandr I can tell you that I got a prototype running locally already so it's coming for sure, maybe soon 😎

**Comment by AvdLee** [comment]
This is coming in RocketSim 4.0!
