### ISSUE TITLE
Save as Reference

### ISSUE THREAD

**Issue by Sherlouk** [AvdLee/RocketSimApp#172]
Currently RocketSim has a great ability to compare design to actual output.

I wonder if there could be a one button option to take a snapshot of the simulator and then use that as the reference/design in the comparison view?

This would make it easy to iterate on UI work and understand what's changing from build to build.

**Comment by AvdLee** [comment]
You could drag the thumbnail directly into RocketSim, isn't that sufficient enough? Let me know your thoughts!

**Comment by Sherlouk** [comment]
🤦  of course I can, d'uh

my apologies!
