### ISSUE TITLE
Floating windows do not appear right away when moving to second screen

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#176]
Occasionally, the floating windows are not showing up when dragging the simulator to a second screen.

**Comment by doozMen** [comment]
This still happens to me regularly when stage manager is enabled. Any idea how to fix that?

**Comment by AvdLee** [comment]
@doozMen we're not officially supporting stage manager, unfortunately. See #233

**Comment by doozMen** [comment]
Ok may I ask for a less fancy window that is not attached to the simulator. Just a normal one? Or should I move to using Pulse?

**Comment by AvdLee** [comment]
You can, definitely! Although it won't be something we will focus on in de short term. So for now it might make sense to move to Pulse or to turn of stage manager 😢
