### ISSUE TITLE
Option to skip positive confirmation that derived data is deleted

### ISSUE THREAD

**Issue by blastum** [AvdLee/RocketSimApp#177]
**Is your feature request related to a problem? Please describe.**
It is inefficient to provide a positive confirmation that derived data has been deleted when we know we will get a negative confirmation if it fails

**Describe the solution you'd like**
Provide an option to hide the "derived data has been deleted" method

**Describe alternatives you've considered**
It does not need an option, you could just not show it ever

**Additional context**
 I hate inefficient ~programs~ UI
<img width="262" alt="screenshot_173" src="https://user-images.githubusercontent.com/5921425/168157170-5e81f080-df15-487f-8c2f-b4b62cd5cf3b.png">

**Comment by AvdLee** [comment]
Agreed! This will be fixed in 8.0.1
