### ISSUE TITLE
Act as a "window manager" for multiple Simulators

### ISSUE THREAD

**Issue by gohanlon** [AvdLee/RocketSimApp#178]
Group several device simulator windows into a single window (somehow) to make macOS's "Split View" much more useful, e.g. Xcode/NeoVim on the left, device simulators on the right. And, non-split Full Screen is even less useful as-is, but it could be amazing on a second monitor if multiple simulator devices could share one window.

My workflow often involves using multiple simulated devices simultaneously, e.g. both a small iPhone mini and a large iPhone Max to represent the smallest and largest targeted screen. It's also common for me to also have an iPad in the mix, too.

* Level 1: Provide a tabbed "document view" of simulators. This would be especially useful with Split View on what's probably the most common setup: a single, built-in display.
* Level 2: Act like a tiling window manager of sorts, and tile multiple device simulators within the same window. Bonus: make a "focused" simulator full size, and thumbnail the other simulator(s). And of course, a keyboard shortcut to rotate which simulator is focused.

I do wonder if such a feature is even possible with a reasonable amount of effort, and if it is, whether RocketSim already has any meaningful amount of functionality towards creating a feature like this. (I'm thinking specifically of the simulator "overlay" techniques RocketSim already has, which I imagine to be quite...involved.)

Thank you for RocketSim!

**Comment by AvdLee** [comment]
@gohanlon sorry for not replying any earlier, but I don't think this is something RocketSim can provide. I'm not in control of the Simulator windows.
