### ISSUE TITLE
Display HTTP traffic (API requests)

### ISSUE THREAD

**Issue by grennis** [AvdLee/RocketSimApp#179]
**Is your feature request related to a problem? Please describe.**
It's helpful to monitor network traffic of an app in development.

**Describe the solution you'd like**
A lightweight HTTP monitor for just the app I'm debugging with json request/response would be great. If it just magically worked like other features, that would be awesome.

**Describe alternatives you've considered**
There is proxyman to display network traffic (API requests) but it's a pretty heavyweight general purpose tool that does too much and shows me too much. I've also used other tools like flipper but those require modifying the app.

**Additional context**
None

**Comment by sslash** [comment]
I would love this as well! 🙌

**Comment by AvdLee** [comment]
This is now available in 12.11.0:
https://docs.rocketsim.app/features/hzQMSrSga7BGWvxdNVdwYs/network-monitoring/guS2qEK2RWWc3coihRQXZT

![image](https://github.com/AvdLee/RocketSimApp/assets/4329185/ef8cffca-75ba-4bdd-b9f7-405d477d5b4f)

**Comment by AvdLee** [comment]
@sslash @grennis I'd love to get your feedback on this feature and whether it fulfills your needs!

**Comment by grennis** [comment]
> @sslash @grennis I'd love to get your feedback on this feature and whether it fulfills your needs!

Very cool, will try it out this weekend. Thanks!

**Comment by grennis** [comment]
@AvdLee The first time I hooked it up, it worked nicely. Then I tried later and it was consistently crashing with exception below. I doubt the error message is correct, I'm just running iOS 17.5.  I sent details to your email: 

"Thread 10: Fatal error: Could not get data from _swizzleURLSessionDataTaskDidReceiveData. It might causes due to the latest iOS changes. Please contact the author!"

**Comment by UnknownCoder807** [comment]
> @AvdLee The first time I hooked it up, it worked nicely. Then I tried later and it was consistently crashing with exception below. I doubt the error message is correct, I'm just running iOS 17.5. I sent details to your email:
> 
> "Thread 10: Fatal error: Could not get data from _swizzleURLSessionDataTaskDidReceiveData. It might causes due to the latest iOS changes. Please contact the author!"

Getting the same.

**Comment by AvdLee** [comment]
@grennis @UnknownCoder807 did you change anything in terms of target device to get this crash? E.g. build on a device or a different Simulator?

**Comment by UnknownCoder807** [comment]
> @grennis @UnknownCoder807 did you change anything in terms of target device to get this crash? E.g. build on a device or a different Simulator?

For me, I just installed the upgrade to rocketsim. Added the code as told in the instructions and it gave me this error when I tried to run in the simulator.  I’m using Xcode 15.3 and iPhone 15 pro max 17.4 simulator.

**Comment by grennis** [comment]
> For me, I just installed the upgrade to rocketsim. Added the code as told in the instructions and it gave me this error when I tried to run in the simulator. I’m using Xcode 15.3 and iPhone 15 pro max 17.4 simulator.

Yeah, same here. I am actually not able to get it to work anymore, it always throws that exception. Not sure what changed but I didn't switch simulators or try on a real device.

**Comment by qeude** [comment]
Same here with Xcode 15.4, iPhone 15 Pro 17.5
I don't know if it can help but here are some more information:
- I'm using the `default` URLSession with just the `timeout` and `additionalHeaders` modified
- Most par of the AppDelegate is still Obj-C
- I might have other dependencies that do swizzling such as `AFNetworking`
Hope it can help 🙏

**Comment by AvdLee** [comment]
Thanks a lot for reporting in all. 12.11.1 at least no longer throws an assertion, but logs a warning in the console instead. I've opened https://github.com/AvdLee/RocketSimApp/issues/538 to dive deeper into this!
