### ISSUE TITLE
Offer a one-time price for Pro. Subscriptions are annoying.

### ISSUE THREAD

**Issue by spnkr** [AvdLee/RocketSimApp#180]
**Is your feature request related to a problem? Please describe.**
I want pro but don't want to pay monthly.

**Describe the solution you'd like**
A one time price I can pay.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by AvdLee** [comment]
@spnkr how about the yearly license subscription instead? Or are you looking for a lifetime purchase? If the latter: what would be a reasonable price you think?

**Comment by johnnieWa1ker** [comment]
Are you considering adding to the subscription model the ability to “freeze” pro-functionality at the level of the latest version of the application at the end of the subscription? 

To make it clearer - I saw such a model in CleanShot X and it seems to be the most honest and interesting payment scheme. There is a motivation for the developer to release updates and it seems to be a more attractive purchase scenario for the user (at least the first annual subscription will be bought better)

**Comment by AvdLee** [comment]
Well, I would love to do such thing, but that becomes unmanageable in the Mac App Store. I'm trying to find the best middleground between maintaining a side project while also offering best licence options possible.

Currently, I'm considering adding license key support for teams through a web purchase, activating it in the app later. Not sure if that gets approved by Apple, though!
