### ISSUE TITLE
Deeplink does not open my app

### ISSUE THREAD

**Issue by gpambrozio** [AvdLee/RocketSimApp#19]
**Describe the bug**
Using a deeplink that should open my app is opening Safari instead

**To Reproduce**
1. Have an app that is successfully setup to handle universal links (correct entitlement file, valid and available app association file), install on the simulator
2. Create a universal link in RocketSim that works on your app on a device
3. Activate the link in RocketSim
4. Simulator opens the link in Safari instead

**Expected behavior**
Open my app

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - XCode 11.4.1
 - Simulator device: iPhone 11  iOS 13.4.1

**Additional context**
N/A

**Comment by AvdLee** [comment]
Hey @gpambrozio, this sounds like an issue with Universal Links instead. Sometimes, universal links can sometimes stop working if its once denied by the user.

You can take a look at this troubleshoot guide as an example: https://blog.branch.io/3-steps-to-troubleshoot-ios-9-and-ios-10-universal-links/

Let me know if that works!

**Comment by AvdLee** [comment]
@gpambrozio closing this one. Feel free to reply and I'll open if needed.

**Comment by gpambrozio** [comment]
@AvdLee I'm still trying to figure out what's wrong. Universal links work perfectly on a device with the same project so the setup should be working. Not sure if there's something the sim does differently in this case.

**Comment by AvdLee** [comment]
@gpambrozio can you reset the simulator through "Device -> Erase all contents and settings" and try it again?

**Comment by gpambrozio** [comment]
@AvdLee I know now what is the issue, not sure how to fix it. Leaving it here for historical reasons and in the hope someone might have an idea.

Our app was created originally by developer X and then transferred to developer Y. So our app id we have in `apple-app-site-association` is `X.com.whatever`. But the app is signed with a cert from developer `Y`. So for simulator builds the verification fails and deep links don't work... But on the device it does.

**Comment by AvdLee** [comment]
@gpambrozio that's unfortunate! I'm unsure how to fix that for you but it's clearly not an issue with RocketSim. If you like, keep us posted on any solutions you find for, indeed, future reference!
