### ISSUE TITLE
RocketSim Appears Briefly When Switching Between macOS Spaces

### ISSUE THREAD

**Issue by nlabarbera** [AvdLee/RocketSimApp#195]
**Describe the bug**
I have the simulator closed and shut down. When I swipe between my Mac's spaces, the RocketSim window appears for 3-4 seconds then disappears. 

**To Reproduce**
- Have multiple Spaces on your Mac.
- iOS Simulator is closed.
- Swipe between Spaces with the 4 finger swipe.

**Expected behavior**
Not to see the RocketSim window flash as my iOS simulator is closed down and killed.

**Screenshots**
Cannot take screenshot. When I attempt to take a screenshot it disappears first.

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Version 8.0.2

**Additional context**
N/A

**Comment by AvdLee** [comment]
That is not good indeed, I'll look into that!

**Comment by AvdLee** [comment]
@nlabarbera this is perfect, thanks a lot! For my idea: do you have any Simulators open? And if so, where is that Simulator located on the screen?

**Comment by nlabarbera** [comment]
Hey @AvdLee - sorry about the delay here. No, the simulator is closed. Both Xcode and the Simulator are killed and not running or still looming in the background.

**Comment by AvdLee** [comment]
Got it reproduced, fixing now!

**Comment by AvdLee** [comment]
Fixed in 8.0.3!

**Comment by nlabarbera** [comment]
@AvdLee - Sweet, rock on! You are truly the best. Thanks for all the great content and a wonderful product! Have an amazing week buddy! 🚀

**Comment by AvdLee** [comment]
@nlabarbera thank you for reporting the issue!
