### ISSUE TITLE
Add support for macOS Mojave 10.14

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#2]
This is most likely the most requested feature short-term. A crash is happening on 10.14 which should be fixed before adding support.

**Comment by AvdLee** [comment]
This crash is fixed and the build is submitted to the App Store.

**Comment by AvdLee** [comment]
This is added in the 1.2 release which is currently In Review.

**Comment by anastely** [comment]
Hey @AvdLee I guess it's not available now for this version 10.14 :(?
![Screen Shot 2020-10-21 at 9 07 20 PM](https://user-images.githubusercontent.com/24620979/96760252-8bdcba00-13e1-11eb-87e6-ec23f55d04d5.png)

**Comment by AvdLee** [comment]
@anastely correct, I had to drop 10.14 for several improvements, unfortunately. Is there no way for you to upgrade to Catalina?

**Comment by anastely** [comment]
@AvdLee Sadly no..
