### ISSUE TITLE
RocketSim is crashing when recording a video

### ISSUE THREAD

**Issue by iSapozhnik** [AvdLee/RocketSimApp#20]
**Describe the bug**
RocketSim is crashing when recording a video

**Steps To Reproduce**
Unfortunately I don't have any. At some moment that app just started to crash every time I'm trying to record a video.
The only thing I can see in the Console app is this: `Service exited due to SIGABRT`. I think you will see it in crash reports

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Version: Version 1.1.0 (16)

**Comment by AvdLee** [comment]
Thank you for reporting this crash. I knew it happened on 1.1.0, did you also see it in 1.2.0?

**Comment by iSapozhnik** [comment]
Let me update the app

**Comment by iSapozhnik** [comment]
Yeah it's the same. Will try to remove the app and install it again.

**Comment by AvdLee** [comment]
This is fixed in 1.2.2!
