### ISSUE TITLE
macOS Spaces Doesn't Show Preview Of Active Window

### ISSUE THREAD

**Issue by nlabarbera** [AvdLee/RocketSimApp#200]
**Describe the bug**
Sorry to bug you again @AvdLee. However, since the update was pushed resolving [Appearing When Switching Spaces](https://github.com/AvdLee/RocketSimApp/issues/195), macOS Spaces now doesn't show the active windows that are on the current Space. I can confirm, this is only an issue when RocketSim is open. When RocketSim is closed, macOS Spaces works as designed.

Related to this issue: https://github.com/AvdLee/RocketSimApp/issues/195

**To Reproduce**
1. Open multiple spaces on your Mac, with a window open on each space.
2. Open RocketSim.
3. Swipe up, to show your Spaces.

**Expected behavior**
The expected behavior is that you can 'preview' what window is on each Space. However, with RocketSim open, the preview is gone for the current Space. I'll provide screenshots below.

**Screenshots**
With RocketSim closed, you can see Xcode in the Preview for Space #5
<img width="1007" alt="Screen Shot 2022-07-11 at 08 32 43" src="https://user-images.githubusercontent.com/52508348/178301298-26b1df85-c65f-4138-a36b-1da3ca5fe731.png">

However, with RocketSim open, you can see the Preview for Space #5 is empty yet Xcode is still open on that Space:
<img width="1381" alt="Screen Shot 2022-07-11 at 08 33 35" src="https://user-images.githubusercontent.com/52508348/178301504-c12ca4a6-ba7f-4fcc-b33a-0294cf56466f.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Version 8.3.0 (111)

**Additional context**
Thanks for all your help! Again, sorry to bother you with another issue. I truly care about RocketSim and want the user to have the best experience they can have. Also, I believe RocketSim is an amazing tool and want to see it succeed.

**Comment by AvdLee** [comment]
@nlabarbera thanks for reporting in! RocketSim hides whenever the Simulator hides. I don't see a Simulator window active in your Space, is that correct? In other words, it's expected for RocketSim to not be visible.

Or, do you state that RocketSim causes Xcode to hide in the spaces overview? 🤔  If so, I'm afraid there's not much I can do to fix that... 🤔

**Comment by AvdLee** [comment]
Closing this one as I haven't been able to reproduce this lately.
