### ISSUE TITLE
'Add device bezels around captures' doesn't work with GIF recordings

### ISSUE THREAD

**Issue by medcalc** [AvdLee/RocketSimApp#202]
[This is a duplicate of bug  #136]
I believe it's an important feature (it's in part why I paid the pro subscription), because I use GIFs in slideshows alongside with PNGs and JPEGs, without the more complicated logic of having to deal with different HTML markup in the slideshow if I was mixing images and video files...

Describe the bug
Device bezels don't show up in GIF recordings.

To Reproduce

 -  Check 'Add device bezels around captures' in Preferences...
 - Click on 'Start GIF Recording'
 - End recording
 - View final result, device bezels are not present in the produced GIF file.

Expected behavior
Bezels should appear, as they do when using MP4 recordings

Desktop (please complete the following information):

- OS: Ventura 13.0 beta 3 (yes sorry it's a beta)
- Version: RocketSim 8.3.0 (111)

**Comment by kristojorg** [comment]
I am also seeing this with Ventura 13.0 and RocketSim 8.6.0 (117)

**Comment by mapierce** [comment]
Yeah I'm getting the same issue. It's a shame, cause a GIF is always what I use in a PR to show my changes and it looks more complete with the bezel

**Comment by AvdLee** [comment]
@mapierce you can use MP4s as well inside PRs and GitHub comments! Nevertheless, I see the value in this feature 🙏

**Comment by AvdLee** [comment]
This will be fixed in 9.6
