### ISSUE TITLE
Landscape mode captures are upside down

### ISSUE THREAD

**Issue by vdhamer** [AvdLee/RocketSimApp#206]
The output files are by default upside down when Xcode simulator is position in Landscape mode.

If you 
1. Launch the simulator. 
2. Click once on the rotate 90' button. 
3. Save the output (it holds for PNG files, but likely also for MP4)

**Workaround**
- Click 3x on the rotate 90' button
- Or fix the output PNG images by rotating 180' in Photoshop

**Desktop (please complete the following information):**
 - OS: 16 beta (20A5339d). Don't think it is beta related.
 - MocOS Monterey 12.5 (non-beta)
 - Xcode 14.0 beta 5

**Comment by AvdLee** [comment]
This is a known problem and not something I can fix right now since I'm unable to read out the orientation of the Simulator. You can rotate the simulator twice more and it should result in the right output. Let me know if that helped!
