### ISSUE TITLE
MP4 resolution not suitable for App Preview

### ISSUE THREAD

**Issue by vdhamer** [AvdLee/RocketSimApp#208]
**The bug**
There are 4 device types needed for submitting an app to the App Store.
The generated MP4 files (with bezels on) are not accepted by App Store Connect
because the resolutions are not correct. Maybe App Store changed req's?

**To Reproduce**
1. Start simulator for gen2 iPad Pro 12.9"
2. Check that bezels are enable in RocketSim. 
3. Create a short MP4 video3. A few seconds is enough.
4. Save the MP4 file locally
5. Drag file to gen 2 iPad Pro 12.9" app previews in App Store connect

**Expected behavior**
I know that PNG files need work to make them App Store ready.
But the documentation claims the .MP4 videos can be submitted as is.
App Store (on actual site) says in a red error message that it accepts either 900x1200 or 1200x1600.
RocketSim automatically generates 1000x1362. So cannot be submitted as is.

**Workarounds**
* Open iMovie ("new App Preview") > import .mp4 from rocketsim > share (save) as App Preview. Some hassle required to get iMove to use the right format. This converts 1000x1362 (portrait) to 900x1200 portrait. App Store then accepts the downsized MP4.

**Comment by vdhamer** [comment]
<img width="834" alt="Screenshot 2022-08-14 at 23 31 18" src="https://user-images.githubusercontent.com/13396568/184555652-6051744a-f3f2-4b16-8b24-daacc6c8a72c.png">

**Comment by vdhamer** [comment]
"Expected behavior". Yes, you expected it, but you might have inside information ;-) But anything in your documentation to show that two of your main features (bezels and App Store support) don't go together?

"Bezels change resolution" (and aspect ratio) sounds logical. But doing an image resize (in PS) followed by a canvas resize (in PS, with appropriate fill color) gives me the correct resolution. So the process could be automated. I tried creating an automation in PS, but the easy ways without programming didn't work.

"app previews might not even get accepted with the bezels applied". My app (Photo Club Waalre) with App Preview actually got accepted **with** bezels a few days ago. But everyone's mileage may vary. All I know is that they did actively review the app, because they initially rejected it. I had mentioned that I had tested on iOS 16 Beta in the "what's new" section but iOS 16 is not a released Apple product yet. Maybe it got caught by a script - the violation of Term and Conditions was technically correct, but overdone. 

"Feel free to still reply!". Appreciated!

**Comment by AvdLee** [comment]
> Well, you expected it, but you might have inside information ;-) But anything in your documentation to show that two of your main features (bezels and App Store support) don't go together?

That's a very valid point. I'll reopen this issue, but mostly to indicate more clearly that bezels and ASC Previews are not supported. Since bezels might change aspect ratio, it will actually be hard to make preview videos formatting work without changing how the app looks. 

I appreciate the detailed reply!

**Comment by vdhamer** [comment]
> That's a very valid point. I'll reopen this issue, but mostly to indicate more clearly that bezels and ASC Previews are not supported. Since bezels might change aspect ratio, it will actually be hard to make preview videos formatting work without changing how the app looks.

Ahhh. Well actually what I did to get JPG and MP4 into the App Store was to scale both exactly to the expected dimensions and thus expected aspect ratio.

The procedure I mentioned was how I converted the JPGs with bezels.

A comparable procedure for converting the MP4 with bezels used Apple's iMovie (comes with MacOS) that actually has built in support for generating App Previews for the App Store. See https://apple.stackexchange.com/questions/145336/apple-said-we-can-use-imovie-to-make-app-previews-but-i-cant-export-the-correc

**Comment by vdhamer** [comment]
In Sep 2022, my submission to the App Store got rejected because I used bezels in the images and video preview.

I don't understand the reasoning behind this (some large apps have heavily Photoshopped screenshots, including screenshots that span consecutive images). I can't see how this misleads the user. But anyway, that's my conclusion: depending on the reviewer, you may or not be allowed to have bezels. My impression is that the App Store has recently become stricter on such rules.

**Comment by AvdLee** [comment]
I've started working on this! The render size indeed is off since the bezels are added. 
A little todo for myself since I'll be working on this across days:

- If ASC optimization is turned on, we should adjust the padding inside the `SimulatorMockupFactory` to ensure that the output size equals the expected App Store Connect resolution
- Potentially, we could adjust the `SimulatorMockupFactory` to just always put out the requested render size that's given as input

**Comment by AvdLee** [comment]
This will be fixed in 9.1!
