### ISSUE TITLE
typo: "Convertion failed" -> "Conversion failed"

### ISSUE THREAD

**Issue by vdhamer** [AvdLee/RocketSimApp#209]
**Describe the bug**
An error message shown in the little windows that appear when you capture still/video.
Just contains a typo.

**To Reproduce**
I won't bother figuring out when the error message shows up (probably a bug in itself: maybe related to 0 second Gif captures?).
But it is simplest to just find the typo via a text search ;-)

**Comment by vdhamer** [comment]
<img width="464" alt="Screenshot 2022-08-14 at 23 27 00" src="https://user-images.githubusercontent.com/13396568/184555588-0c2a4db3-f0d7-4ea7-8d2e-b423791ceffa.png">

**Comment by AvdLee** [comment]
Yesss, perfect! These are quick wins 💪 Thanks, fixed in 8.5.0!
