### ISSUE TITLE
Sparse app icon in statusbar

### ISSUE THREAD

**Issue by EvilOne** [AvdLee/RocketSimApp#21]
**Describe the bug**
The icon is rather sparse when not in dark mode. See the screenshots.

**To Reproduce**
Start the app and look to the statusbar.

**Expected behavior**
Unselected icon a little more visible than it currently is.

**Screenshots**
Unselected app icon:
<img width="50" alt="2020-05-06_06-57-25" src="https://user-images.githubusercontent.com/169561/81174150-e9ca3200-8f66-11ea-9254-18637447fde8.png">

Selected app icon:
<img width="68" alt="2020-05-06_06-57-25 (1)" src="https://user-images.githubusercontent.com/169561/81174173-f5b5f400-8f66-11ea-9a57-b9fabc4bebd0.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Version [e.g. 22]: 1,20,0 (21)

**Additional context**

**Comment by AvdLee** [comment]
That's a very good point! I love dark mode so much that I didn't notice this. I'll fix this!

**Comment by AvdLee** [comment]
This will be fixed in the upcoming release!
