### ISSUE TITLE
RocketSim PRO seats for companies

### ISSUE THREAD

**Issue by rukano** [AvdLee/RocketSimApp#212]
Is there any way to buy or subscribe to RocketSim PRO for companies? At the moment is all done via AppStore subscriptions (which probably use the user's private AppleID) but is it possible for a company to buy let's say 4 seats, and distribute them to 4 employees?

**Comment by AvdLee** [comment]
The only way to purchase RocketSim is through the App Store, but it might be possible to have a look at [Apple Business Manager](https://developer.apple.com/support/volume-purchase-and-custom-apps/). Hope that helps! If not, can you contact me at contact@avanderlee.com?
