### ISSUE TITLE
Folders don't open on first click

### ISSUE THREAD

**Issue by kassi** [AvdLee/RocketSimApp#215]
**Describe the bug**
If I choose a folder from the RocketSim menu bar icon according to the currently running app, the folder won't open.
Hitting the menu item a second time opens the folder in Finder.
This happens every time after a restart of the app via Xcode (CMD+R).
Same for other folders like Application Support.

**To Reproduce**
1. Go to Xcode and hit CMD+R
3. Focus the simulator
4. Go to RocketSim menubar item
5. Select the app
6. Select Documents folder

**Expected behavior**
The documents folder opens in finder.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5
 - Xcode 13.4.1
 - RocketSim 8.5.0 (just updated and tried again)
 - MacbookPro 16", 2021, M1 Max

**Comment by AvdLee** [comment]
@kassi I tried reproducing this, but without success. Do you think it's possible for you to sent me a screen recording to contact@avanderlee.com?

**Comment by AvdLee** [comment]
Alright, key is to really open the folder from the status bar menu directly after launching a new build. It's likely that the build folders didn't refresh for the latest generated build.

**Comment by AvdLee** [comment]
This is solved in RocketSim 9.0.0
