### ISSUE TITLE
Ordering of Deeplinks in menu is inconsistent

### ISSUE THREAD

**Issue by GrandPoohBear** [AvdLee/RocketSimApp#22]
**Describe the bug**
Ordering of the Deeplink menu items is inconsistent between menu renderings.

**To Reproduce**
1.  Create a bunch of Deeplinks named "A","B","C","D","E"
1.  Close the app and relaunch
2.  Open the menu to launch one of the deeplinks, note the order of the menu items.
3.  Click away, then click back to the menu.
4.  _Sometimes_ the ordering changes.

**Expected behavior**
The ordering should be the same each time you drop the menu down for better predictability and usability.

**Screenshots**
<img width="408" alt="Screen Shot 2020-05-07 at 2 18 22 PM" src="https://user-images.githubusercontent.com/1160174/81335742-b58d6900-906d-11ea-9100-d2f2bfa0207e.png">
<img width="413" alt="Screen Shot 2020-05-07 at 2 18 34 PM" src="https://user-images.githubusercontent.com/1160174/81335743-b625ff80-906d-11ea-8ec6-fcf88b751f7d.png">

**Desktop (please complete the following information):**
 - OS: 10.15.4
 - Version 1.2.1 (22)

**Additional context**
Opening the Preferences seemed to lock the order in place.  Not sure why.

**Comment by AvdLee** [comment]
Thanks @GrandPoohBear, this indeed can be improved and could start with simply alphabetical order. Ideally, the order would be manageable from the settings but that's something for the long-term. I'll add this to the roadmap!

**Comment by AvdLee** [comment]
![image](https://user-images.githubusercontent.com/4329185/81505873-daded900-92f2-11ea-85db-f2ad10d578a8.png)

Working on it! I will try to submit this tonight, releasing it in 1.2.3!

**Comment by AvdLee** [comment]
Submitted, thanks again for reporting in!
