### ISSUE TITLE
Unable to use RocketSim with another simulator

### ISSUE THREAD

**Issue by gdelataillade** [AvdLee/RocketSimApp#220]
I'm using the free trial.

I started using RocketSim with an iPhone SE (3rd generation) but then I wanted to switch to an iPhone 14 Pro Max because my Figma screens are designed with large screen dimensions.

The issue:
When I open another simulator instead of the iPhone SE, the RocketSim floating windows are not showing. I am still able to take screenshots though.

<img width="300" alt="Screen Shot 2022-09-14 at 18 25 22" src="https://user-images.githubusercontent.com/32983806/190210240-4cba5de6-bc38-4b56-b80e-f4e3948841d9.png">

<img width="300" alt="Screen Shot 2022-09-14 at 18 25 03" src="https://user-images.githubusercontent.com/32983806/190210315-ea74b97d-82b7-4ec7-a55f-9934c4ad14ed.png">

**Comment by AvdLee** [comment]
This was fixed in 8.7.0. Feel free to reopen this issue if you're still experiencing the same problems.

**Comment by gdelataillade** [comment]
Hi! The only way I found to download RocketSim is on the App Store, and the last version on the App Store is 8.6.0 (released 4 days ago).

Info:
_macOS Monterey 12.5.1
MacBook Pro 14 M1 Pro_

**Comment by gdelataillade** [comment]
It seems to be fixed on 8.6.0 though. I'm closing the issue.
Thanks
