### ISSUE TITLE
Screenshot sometimes fails with an error

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#225]
> 2022-10-12 17:22:50 | ProcessController.swift:L62 | Read line for process Simulator screen capture: An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):

**Comment by vdhamer** [comment]
"sometimes" looks like an understatement. Hard to get any screenshots done. Workaround?

**Comment by AvdLee** [comment]
@vdhamer from analytics I can see that it works for most of the users, that's why I mention "somtimes". Are you constantly running into issues? If so, would you mind sending me a Diagnostics Report through Preferences -> About -> Report an issue?

**Comment by vdhamer** [comment]
Yes, I was consistently/repeatedly running into issues. Ended up making screenshots without RocketSim.
Will send Diagnostics Report as soon as I can reach my Mac (am traveling with just an iPad, gasp!). My Mac hasn’t been upgraded to Ventura yet (for same reason) so I will test before and after the upgrade.

**Comment by AvdLee** [comment]
@vdhamer I recently released a new version with big performance improvements. I'm closing this one for now as I'm pretty sure the issue should no longer exist. (I found a potential cause along the way). Feel free to reopen if otherwise!
