### ISSUE TITLE
Rocketsim shows a new version is available although it's already installed

### ISSUE THREAD

**Issue by 4PixelsDev** [AvdLee/RocketSimApp#227]
**Describe the bug**
The behavior from the title also happens after the application restart.

**Screenshots**
<img width="1459" alt="Screenshot 2022-10-25 at 22 29 11" src="https://user-images.githubusercontent.com/597534/197876213-b4c5f713-730a-4564-8ee8-9a521185e5b9.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version  13.0 (22A380)

**Comment by AvdLee** [comment]
This is fixed in 8.6.2
