### ISSUE TITLE
Team Licenses & Purchasing outside of App Store

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#228]
For Team Licenses or options to buy RocketSim outside of the App Store, check out: https://avanderlee.gumroad.com/l/rocketsim

**Comment by oszydlowski** [comment]
Hey @AvdLee! It's not entirely clear to me what the pricing for team license is. Should I put in the number of team members as the quantity here (https://avanderlee.gumroad.com/l/rocketsim)? If so, how is that different than just buying X individual licences? The price per person look the same

**Comment by AvdLee** [comment]
Hey @oszydlowski!

> Should I put in the number of team members as the quantity here (https://avanderlee.gumroad.com/l/rocketsim)?

Yes, exactly. 

> If so, how is that different than just buying X individual licences? The price per person look the same

It's not different! 

----

In other words: Quantity set to 5 equals 5 licenses

**Comment by mrgradyed** [comment]
Hi @AvdLee, 

thanks for this nice helpful tool.

I currently see 2 different prices for the 1-year license. 

- If purchased via **in-app** subscription, it's 30.99 **€** (**~** 32 **$**) per year (including vat). 
- If purchased via **avanderlee.gumroad.com**, the price is higher, 51.42 **$** (**~** 48 **€** ) with vat. 

May I know the reason behind this pricing policy? Thank You.

<img src=https://user-images.githubusercontent.com/2436636/225403615-ef41a0ff-f674-4482-aeae-7eaf5392a2fe.png width="150"><img src=https://user-images.githubusercontent.com/2436636/225400750-ee60a0db-abdc-47d1-940f-513161436373.png width="150"><img src=https://user-images.githubusercontent.com/2436636/225400727-cdc1d700-9957-4687-909c-145719466696.png width="150">

**Comment by AvdLee** [comment]
> May I know the reason behind this pricing policy? Thank You.

I see the team licenses as commercial licenses, which is why they're a little more expensive. It's a common pattern!
