### ISSUE TITLE
Ability to offset the screenshot against the iOS simulator.

### ISSUE THREAD

**Issue by nonameplum** [AvdLee/RocketSimApp#231]
**Is your feature request related to a problem? Please describe.**
Ability to adjust offset of the screenshot when comparing (useful when sometimes designers make "universal" design between platforms and e.g. the navigation bar is at different position from the top than what we have by default have on iOS).

**Describe the solution you'd like**
Fields that would allow to set the offset (left, right, top, bottom) to the screenshot against the simulator screen.

**Describe alternatives you've considered**
Move the screenshot using mouse.

**Additional context**

**Comment by AvdLee** [comment]
@nonameplum thanks for reporting in! I wonder, have you tried the available offset options?
![CleanShot 2022-11-03 at 11 46 51@2x](https://user-images.githubusercontent.com/4329185/199701717-d6d5a731-f5b8-4f1f-bb89-f319adb58a6a.jpg)

If so, could you elaborate a bit more what you need? As in: do you need more fine control as in pixel offsets?

**Comment by nonameplum** [comment]
Yes, I have tried but I didn't see any difference (as probably the image ratio matched exactly the same with simulator?).
Anyway, I have ability to precisely configure the offset would be great.

**Comment by nonameplum** [comment]
Simulator: iPhone 14 iOS 16.0
![test](https://user-images.githubusercontent.com/1753816/199706675-5b88676c-a2c0-4d46-93bf-29b494432a5e.png)

**Comment by AvdLee** [comment]
Would this be a helpful implementation? It's not optimized, but illustrates the idea!

https://user-images.githubusercontent.com/4329185/214150818-fc7f2bbb-757a-4842-a0bb-2e2fbd45c228.mp4

**Comment by AvdLee** [comment]
This will be available in RocketSim 9.3, see for a preview: https://twitter.com/twannl/status/1618344563231584256?s=20&t=FfIv03CNgTEJznA9Nc2ylA
