### ISSUE TITLE
Improve Stage Manager support

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#233]
See email Rene Skov, the window seems to be jumpy

**Comment by AvdLee** [comment]
I could no longer reproduce this

**Comment by fawzirifai** [comment]
Any updates? @AvdLee

**Comment by AvdLee** [comment]
@fawzirifai is this still happening to you? I've not been able to reproduce this lately

**Comment by fawzirifai** [comment]
Yes, still happening. @AvdLee

**Comment by AvdLee** [comment]
I've spent half a day on this and have to conclude that there's very limited support in terms of APIs to handle stage manager window changes. On top of that, RocketSim's windows work together with the Simulator and RocketSim both visible. Stage manager, unless grouped, works in a way of focussing on a single app only. Therefore, it's challenging to keep both RocketSim and Stage manager visible.

Therefore, it's not realistic to offer proper support for RocketSim to those using Stage Manager on macOS.
