### ISSUE TITLE
Allow the overlay screenshot compare image to scroll with the Simulator

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#235]
See for context: https://twitter.com/nehayward/status/1590794292360269825?s=20&t=yuvcuElxlp5-axOd-4yb2w

It would allow to compare bigger screens

**Comment by scottwio** [comment]
This is the feature I can't live without at the moment I use XScope for overlays as I can manually scroll the image with it.

**Comment by AvdLee** [comment]
@scottwio thanks for that insight! Do you have a good suggestion on how this could work ideally for you?

**Comment by scottwio** [comment]
I think, close to what you have now, but as you scroll, the image would scroll with you. Then you can adjust as needed horizontal and vertical, as sometimes your get designs that don't marry up to the initial position on the phone. xScopes' little draggy handles would be a nice interface for the adjustments.

![Screen Recording 2022-11-24 at 12 27 33 2022-11-24 12_29_10](https://user-images.githubusercontent.com/340168/203784821-45343087-7643-4873-a15b-d8f0f08f7f0c.gif)

**Comment by AvdLee** [comment]
Similar to https://github.com/AvdLee/RocketSimApp/issues/231

**Comment by AvdLee** [comment]
Would this be a helpful implementation? It's not optimized, but illustrates the idea!

https://user-images.githubusercontent.com/4329185/214150818-fc7f2bbb-757a-4842-a0bb-2e2fbd45c228.mp4

**Comment by scottwio** [comment]
> Would this be a helpful implementation? It's not optimized, but illustrates the idea!
> 
>  output.mp4

Absolutely, looks prefect 🔥

**Comment by AvdLee** [comment]
This will be available in RocketSim 9.3, see for a preview: https://twitter.com/twannl/status/1618344563231584256?s=20&t=FfIv03CNgTEJznA9Nc2ylA
