### ISSUE TITLE
Grid and Rulers - wrong alignment 

### ISSUE THREAD

**Issue by Fortidude** [AvdLee/RocketSimApp#239]
**Describe the bug**

As you can see on the screen below - the middle of Rulers is at `51.3%` and the grid is completely miss aligned as well.
It would be nice to put the line directly in the horizontal middle of the screen.

**To Reproduce**
1. Open RocketSim
2. Enable Grid / Rulers

**Expected behavior**
Grid and rulers align to center (or a way to align them left/center/right(

**Screenshots**
<img width="710" alt="Screenshot 2022-11-28 at 13 01 25" src="https://user-images.githubusercontent.com/8781462/204273072-19f91f0b-9879-4d30-b330-a367644663e4.png">

**Desktop (please complete the following information):**
 - OS: iOS 15.5
 - Version of RocketSim: 8.7.0

**Additional context**

I would like to align the grid to the center, however there is no such option. Without this those two are pretty useless feature to be honest 🤔

**Comment by AvdLee** [comment]
@Fortidude thanks for reaching out! Have you tried out the preferences options to change the grid spacing?
If not, could you see if that's fulfilling?

**Comment by Fortidude** [comment]
hey 👋  @AvdLee 

Yes, I have. The only one settings for Grid that 'kinda' works is this below. `49 blocks` works as well. 


The main reason it doesnt work well is because it's aligned from the left edge of the screen - would be nice to align it to the center (horizontal)


### 49 blocks:
<img width="380" alt="Screenshot 2022-11-28 at 15 28 09" src="https://user-images.githubusercontent.com/8781462/204302565-aada2489-32cc-4265-8132-a3f44a9ca276.png">


### Example with 8 blocks. It's completely misaligned.


<img width="380" alt="Screenshot 2022-11-28 at 15 30 33" src="https://user-images.githubusercontent.com/8781462/204303103-493c4c6f-8ac3-48c9-bbd2-5e42258c9841.png">


### Example with `49 devices pixels` and `1 blocks`:  (23 pixels works quite well)

<img width="380" alt="Screenshot 2022-11-28 at 15 33 01" src="https://user-images.githubusercontent.com/8781462/204303694-0620d347-858e-4972-8540-6d7bffd9017c.png">



now the more I think about It - the more I see what you have tried to do here. 
And I think it can work nice with some config, but it's quite difficult to set it up properly 🤔  Especially since it will require different settings for different simulator size (I believe)

**Comment by AvdLee** [comment]
Closing this as I believe grids should align from the lefthand side. Also, the ruler functionality can be used to find the center accordingly:



![Image](https://user-images.githubusercontent.com/4329185/211205209-26619111-65a1-425f-b59e-5cc300421892.jpg)
