### ISSUE TITLE
Creating an MP4, rather than Creating a MP4

### ISSUE THREAD

**Issue by ridmaur** [AvdLee/RocketSimApp#243]
**Describe the bug**
When creating the MP4 as part of the recording, the temporary progress window displays "Creating a MP4". I think it should be "Creating an MP4".

**To Reproduce**
- Record an MP4 of the simulator.
- When stopped, progress window is shown with incorrect text.

**Expected behavior**
When creating the MP4 as part of the recording, the temporary progress window displays "Creating a MP4". I think it should be "Creating an MP4".

**Comment by AvdLee** [comment]
This will be fixed in 9.1
