### ISSUE TITLE
How to activate team license?

### ISSUE THREAD

**Issue by weakvar** [AvdLee/RocketSimApp#244]
I got a team license for RocketSim, but I can't found any button to enter a key and activate the license. What should I do for that?

**Comment by AvdLee** [comment]
@weakvar thanks for buying a RocketSim Pro license first of all!

The installation instructions can be found on Gumroad after buying, but I've added them here for your convenience:

> Thanks for buying RocketSim Pro
>
> To activate your license key:
>
> - [Install RocketSim 8.6.1+ from the Mac App Store](https://apps.apple.com/app/apple-store/id1504940162?pt=117264678&ct=website-header&mt=8)
> - Open the sales view (Statusbar menu -> RocketSim Pro...)
> - Right-Click Restore Purchase from within the footer and select Enter Team License
> - Fill in your license key
> - Enjoy RocketSim Pro
