### ISSUE TITLE
Instead of delete derived data, move to trash

### ISSUE THREAD

**Issue by blastum** [AvdLee/RocketSimApp#245]
**Is your feature request related to a problem? Please describe.**
Deleting derived data is a time-consuming process and there is no notification of completion, so occasionally I get errors from RocketSim long after a request to delete.

**Describe the solution you'd like**
Moving to the trash, as with the homebrew `trash` command, is a fast operation.

**Describe alternatives you've considered**
No other way to do it in the app.

**Additional context**
Have a nice day?
<img width="258" alt="screenshot_44" src="https://user-images.githubusercontent.com/5921425/211058594-70577559-3630-4532-afdd-17a5dbe044eb.png">

**Comment by AvdLee** [comment]
Interesting, I wasn't aware this could take so long! I'll see what I can do here 🙏

**Comment by AvdLee** [comment]
Fixed in 9.2.0!
