### ISSUE TITLE
Ability to move the floating windows.

### ISSUE THREAD

**Issue by oliverfoggin** [AvdLee/RocketSimApp#248]
**Is your feature request related to a problem? Please describe.**
I use Xcode a lot with the simulator in a shared side by side display. When the simulator is focussed the floating windows appear in arbitrary and often not very convenient places.

**Describe the solution you'd like**
It would be good to be able to move the floating windows around so that I can position them in a more convenient place.

**Describe alternatives you've considered**
For now I have to turn off the floating windows when I'm working with the side by side like this. But it might be an option to make the windows not floating but as their own proper window so I can move it around? Maybe.

**Additional context**
Screenshot of the issue mentioned.
![Screenshot 2023-01-08 at 18 55 40](https://user-images.githubusercontent.com/1813244/211213760-e5abcf00-2938-447a-9e3f-7ac771848552.png)

**Comment by AvdLee** [comment]
Closing this as fixed as I believe version 9.1.0 and with a fix for #234 will be a solution to this issue as well. Let me know if not!
