### ISSUE TITLE
Add a link to the folder where "On My iPhone" files are stored in the Files App

### ISSUE THREAD

**Issue by chrisvasselli** [AvdLee/RocketSimApp#249]
**Is your feature request related to a problem? Please describe.**
I'd like to test various scenarios around loading files using `UIDocumentPickerViewController`, and it's always a pain to get files onto a simulator to test. The easiest way seems to be either to (1) sign into iCloud in the simulator, which has its own issues, or (2) add files to the "On My iPhone" folder.

However, accessing the "On My iPhone" folder from the host Mac is pretty tricky, involving a path with a UUID that is unique on every simulator.

**Describe the solution you'd like**
I'd like to be able to tap on my app or the "Perform" button, and in addition to the existing folders, have a link to a new one for the "On My iPhone" folder location.

**Describe alternatives you've considered**
Up until recently I've been sharing a photo from the photo library and selecting "Save to Files", and then the host Mac searching the entire device container for the name of that file. I recently discovered the `xcrun simctl` command below that makes things a bit easier, but ideally it could be built into a tool like RocketSim.

**Additional context**
It looks like the path to this folder is determinable by using the command `xcrun simctl get_app_container booted com.apple.DocumentsApp groups` to get the path to the Files app's app group folder. The contents of On My iPhone seem to be stored in the subfolder called "File Provider Storage" in this app group folder.

Here's a screenshot of the folder I'm talking about in the iOS files app:
![Simulator Screen Shot - iPhone 8 - 2023-01-10 at 17 31 17](https://user-images.githubusercontent.com/227043/211501203-9fc1b5ff-fe9b-4df3-aa6e-71d1565661d2.png)

And here's an example location of this folder in finder on the host Mac:
<img width="563" alt="Screenshot 2023-01-10 at 5 36 32 PM" src="https://user-images.githubusercontent.com/227043/211501547-89f8b7e6-a0f2-498d-a31d-b0cbafb57d01.png">

**Comment by AvdLee** [comment]
Thanks a lot for all the details, that makes it a lot easier to share. Do you know whether the folder within the AppGroup is always called `File Provider Storage`? If so, this is like a 5 minute fix!

**Comment by chrisvasselli** [comment]
@AvdLee I tested on an English simulator running iOS 16.2, and a Dutch simulator running iOS 15.5, and they both seemed to use the name "File Provider Storage". I also checked https://applelocalization.com and it can't find the string "File Provider Storage", which makes me feel like it's not localized (which makes sense, since it's not user facing).

On an iOS 14.5 simulator, the location seems to be in a different app group, but I haven’t figured out a way to identify it reliably. For my purposes, limiting this to iOS 15+ simulators would be totally fine.

I suppose it's possible there could be some settings that affect the location, but so far I haven’t found any.

**Comment by chrisvasselli** [comment]
Just tested on an iOS 15.0 simulator too, and it seems to get the correct location. 

I also noticed that the File Provider Storage folder doesn't exist in a freshly launched simulator, but is created as soon as I open the Files app (and possibly at other times). So make sure to account for that as well.

**Comment by AvdLee** [comment]
Amazing, this sounds like a quick win! I'll try to squeeze it into 9.1
