### ISSUE TITLE
Change recording destination folder

### ISSUE THREAD

**Issue by amayers** [AvdLee/RocketSimApp#25]
**Describe the solution you'd like**
Recordings created by RocketSim would be saved to `~/Desktop` folder. Since this is the default behavior for the simulator's CMD-S for screenshots, as well as macOS' screenshot/recording functionality.

**Describe alternatives you've considered**
I guess you could make this configurable, but IMHO its probably not worth that additional UI/complexity.

**Comment by AvdLee** [comment]
Done!
