### ISSUE TITLE
Secondary screen no longer works correctly since 9.1.0

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#256]
It appears that the floating window doesn't follow the Simulator nicely. Must be related to the window animation!

**Comment by AvdLee** [comment]
Fixed in 9.1.0

**Comment by sQuarecoW** [comment]
Wow, that was fast!

**Comment by AvdLee** [comment]
> Wow, that was fast!

It's a critical bug for RocketSim to work, so that required priority!
