### ISSUE TITLE
Simulator rotate buttons?

### ISSUE THREAD

**Issue by drivediary** [AvdLee/RocketSimApp#257]
**Is your feature request related to a problem? Please describe.**
I really hate needing to click the rotate button until the simulator is in the correct rotation for my need. Even going to the menu bar > Device > Oriantation is a pain lol.

**Describe the solution you'd like**
Im not sure if you're able to with limitations, but I would love four buttons to be able to instantly go to the orientation I need.  Would be super nice! :) 

**Describe alternatives you've considered**
I have included a mock-up of my idea.

**Additional context**
![rotate_feat_req](https://user-images.githubusercontent.com/71890705/214566476-edec181f-31a6-4c2e-a541-a06df6858dba.png)
**Love the app by the way! :)**

**Comment by drivediary** [comment]
No problem. By the way, a simple “thank you” for offering suggestions to improve an app I’ve paid to use- or even a positive response- wouldn’t go amiss. Just saying.

**Comment by AvdLee** [comment]
@drivediary you are totally right, sorry about that! I absolutely appreciated your request, but replied in the process of issue clean up.

This is no excuse, I should've be more thoughtful of the way I closed this ticket. Once again, sorry for that! 🙏
