### ISSUE TITLE
"Report a bug" doesn't react to clicks

### ISSUE THREAD

**Issue by bbethke** [AvdLee/RocketSimApp#259]
**Describe the bug**
When I launch Preferences, navigate to the "About" tab, and select "Report a bug," nothing happens. I've checked all open Safari windows and tabs and used Exposé to look for any open windows, but it seems the button isn't triggering anything.

macOS Ventura 13.2
M1 Max MacBook Pro

**To Reproduce**
1. Go to "Preferences..." in the RocketSim menu.
2. Click on the "About" tab.
3. Tap the "Report a bug" button.

**Expected behavior**
A window or browser tab/window would launch, allowing me to report a bug.

**Screenshots**
<img width="772" alt="image" src="https://user-images.githubusercontent.com/779109/214638379-93822092-d7c7-47a5-b0a0-a987b4a74eef.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.2

**Additional context**

**Comment by AvdLee** [comment]
@bbethke could it be that you don't have the Mac Mail app installed? 🤔 That would result in it not doing anything

**Comment by AvdLee** [comment]
I've add a fallback to inform users about this next time 👌

**Comment by bbethke** [comment]
@AvdLee I don't have the mail app configured, but I have it installed. Good to know. Thanks!

**Comment by AvdLee** [comment]
@bbethke perfect! For now, you can Right Click the button to generate a report and file your issue if you have one!

![CleanShot 2023-01-25 at 21 59 23@2x](https://user-images.githubusercontent.com/4329185/214689333-f288bb14-216d-48f1-aec3-d58e5edb3d0d.jpg)

You can mail it to contact@avanderlee.com
