### ISSUE TITLE
Floating Window Appears Far from Simulator

### ISSUE THREAD

**Issue by bbethke** [AvdLee/RocketSimApp#260]
**Describe the bug**
Viewing the simulator on an external monitor causes the floating window of Rocket Sim to appear across the screen from the simulator (with or without dynamic window placement). Viewing the simulator on the native laptop screen (M1 Max MacBook Pro) allows the floating window to follow the simulator at the correct distance. This is the case even if I close and reopen the floating window once the simulator is already open on the external monitor (DELL 27" P2720D) or restart the simulator to launch directly onto the external monitor. This also happens in the hidden mode (red tab).

**To Reproduce**
1. Connect an external monitor (DELL 27" P2720D).
2. Launch the iPhone 14 Pro simulator with Xcode 14.1.0.
3. Open RocketSim's floating window.
4. Hide the floating window with the "eye" icon. Tap the red rocket tab to unhide the window.
5. Notice the floating window is placed immediately adjacent to the simulator.
6. Move the simulator to an external monitor.
7. Note that the floating window now appears on the opposite side of the screen in relation to the simulator window.

**Expected behavior**
The floating window (hidden/collapsed or visible) should be adjacent to the simulator window regardless of the screen it appears on.

**Screenshots**
![SCR-20230125-g9q](https://user-images.githubusercontent.com/779109/214642081-b8deb564-a423-4ad3-84cb-6b63ef405ba0.jpeg)
![SCR-20230125-gah](https://user-images.githubusercontent.com/779109/214642102-6feb1fea-0dd6-41cb-bec2-ffabcd953aaf.jpeg)

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version: 13.2

Thanks for the awesome tool! Let me know if there's further troubleshooting I can help with.

**Comment by AvdLee** [comment]
I just submitted a fix for this, version 9.2.0. It should be available soon! Let me know if that build fixed your issue, in case I'll reopen this. Thanks a lot for the detailed report!

**Comment by bbethke** [comment]
@AvdLee Awesome! I'll be sure to test it when the update is available. Thanks for the quick response!
