### ISSUE TITLE
Voice Synthesis for Monterey?

### ISSUE THREAD

**Issue by larryapple** [AvdLee/RocketSimApp#270]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by larryapple** [comment]
My co-developer in India does not have a Ventura-capable Mac. In Ventura, I find the default voices for each country and the classic voices, but on his Monterey machine no voices show. Would it be possible to install them with RocketSim? (He also doesn't have an iOS-16 capable iPhone, or even access to one). We are creating "PokerOutLoud", a near-clone of Apple's Texas Hold'm, but we think ours will be easier and more fun to play. And eventually connected to ChatGPT.

**Comment by AvdLee** [comment]
@larryapple thanks for reporting in. Can you tell me what you mean with Voices? And where do those live on the system?

**Comment by larryapple** [comment]
Thanks for getting back to me. These are the voice synthesis voices. Each player in PokerOutLoud, both AI and human, will announce his or her bid with a different voice, if that option is enabled. Then the human players will also be able to make their bids with voice recognition instead of by touch or typing.

**Comment by larryapple** [comment]
They live in Accessibility.SpokenContent

**Comment by AvdLee** [comment]
Thanks for the extra context! I'm afraid I'll be unable to include this inside the RocketSim binary and copy it over for older macOS versions. Sorry, but I think you'll have to look for another way to solve this!

**Comment by larryapple** [comment]
Actually it turns out I was mistaken. I am now able to sign in to my Apple ID, and then the voices are there.

At this point, Monterey is proving much more stable than Ventura for me. Which is good, because my partner cannot run Ventura anyway.

Sorry to have wasted your time, but I do think the voices can be a very useful thing.
