### ISSUE TITLE
Subscription issue

### ISSUE THREAD

**Issue by minamikhael1** [AvdLee/RocketSimApp#274]
I had many issues with payment, which led to me using a different apple id, and I was able to subscribe but the app is still basic not pro, I tried quitting, and restoring the purchase, but still basic.

I already received the receipt from apple, and I can see the subscription in my account.

**Screenshots**
![image](https://user-images.githubusercontent.com/8222881/217796510-0494dac0-33fe-4644-aefa-c55d3a3c3a81.png)
![image](https://user-images.githubusercontent.com/8222881/217796944-76bde6fe-9f68-4479-a6ff-a6f423921513.png)
![image](https://user-images.githubusercontent.com/8222881/217797096-4004f2b9-7c6c-4fe7-b26a-065645625585.png)

**Comment by AvdLee** [comment]
@minamikhael1 I'm sorry for this inconvenience! Most of the times, this happens due to a mismatch in account used to purchase and account used to restore a purchase.

Can you check whether the Mac App Store is signed in with the same email as the original purchase?

**Comment by minamikhael1** [comment]
@AvdLee I have 2 accounts, yes that true, I tried signing in with both and the restore fails on both.

**Comment by AvdLee** [comment]
Can you report an issue via Settings -> About -> Report an issue? The diagnostics report will help me further solve this issue. I'm also closing this issue here, since I don't want this issue to contain more personal information from you. Let's continue via mail!
