### ISSUE TITLE
Remove app name in Dynamic Island when recording video

### ISSUE THREAD

**Issue by Sparklydust** [AvdLee/RocketSimApp#276]
**Is your feature request related to a problem? Please describe.**
When enabling device bezels while recording, the app name appears on the simulator dynamic island. 

Unfortunately, and because of this issue, I can not share video recording in Jira tickets or other platforms when working for a company. So this feature is no of use.

**Describe the solution you'd like**
No app name reference while recording on the dynamic island or any other place of the simulator. 

**Describe alternatives you've considered**
At least for the paid subscription it can be hidden, as it would be fair to have it on the free version. 

**Additional context**
I really like this application, and try to have all my developer colleagues subscribed to it. 
It is so cool that having this kind of add in the middle of a recording is not necessary.

**Comment by AvdLee** [comment]
@Sparklydust you can disable the watermark from preferences:
 
![CleanShot 2023-02-12 at 20 12 50@2x](https://user-images.githubusercontent.com/4329185/218331956-3896938f-f08d-4431-99d6-5520349ac353.jpg)

Therefore, closing this issue. Let me know if that isn't solving your issue and I'm happy to reopen!
