### ISSUE TITLE
Ruler hover outputs are cut off

### ISSUE THREAD

**Issue by jostster** [AvdLee/RocketSimApp#281]
**Describe the bug**
Overlay the grid and ruler on simulator. If you are comparing elements that are on the far right of the screen and looking at the ruler, the points and % are cut off because they are displayed on the right of the ruler

**To Reproduce**
1. Enable ruler on simulator
2. Hover mouse of the ruler on the far right, usually around the 370 range.
3. Notice the points and % are cut off and unreadable.

**Expected behavior**
The text should shift to the left or still show without being cut off.

**Screenshots**
<img width="140" alt="image" src="https://user-images.githubusercontent.com/278510/219092710-affc7495-a8cf-41f6-866a-e50f11f38d90.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 16.2

**Additional context**

**Comment by AvdLee** [comment]
Great catch! That would be a nice improvement indeed 🙂

**Comment by AvdLee** [comment]
Also requested by V. Yevtushenko

**Comment by AvdLee** [comment]
This will be fixed in 10.3.3
