### ISSUE TITLE
Network Link Conditioner - Slower connections

### ISSUE THREAD

**Issue by vykut** [AvdLee/RocketSimApp#283]
Would be really useful to simulate various network conditions directly from the RocketSim window.

The current Network Link Conditioner in Xcode, that's part of the Additional Tools is impacting the network conditions of the whole mac, not just the current iOS simulator. 
At least for me, this is very frustrating when trying to demo different features that are move visible in different network conditions (errors, shimmers, etc)

**Comment by AvdLee** [comment]
@vykut I would love to build this, but I'm afraid there's not much I can do. At least: I'm not sure if there are any AppKit/macOS APIs that would allow me to build this.

If you have any suggestions on how I could implement this, I'm happy to give it a shot!

**Comment by vykut** [comment]
@AvdLee I have looked this up on google and I'm afraid I couldn't find any native APIs that could do this. There are some discussions in [this](https://superuser.com/questions/126642/throttle-network-bandwidth-per-application-in-mac-os-x) forum, but I don't know how feasible it would be

**Comment by AvdLee** [comment]
Yeah, it's pretty much all globally managed. I'll see if I can further investigate this later!

**Comment by AvdLee** [comment]
I've looked into this sample project to disable networking for a specific app: https://developer.apple.com/documentation/networkextension/filtering_network_traffic

Unfortunately, I have not been able to get any networking requests through the sample app 😢

**Comment by AvdLee** [comment]
@vykut good news, this is coming in the next update. Though: only enable/disable networking. Would that be enough or do you also need slow internet connection testing? If the latter, what scenarios do you test with that?

**Comment by vykut** [comment]
Hey @AvdLee, that’s great! I saw your posts about this upcoming feature. Can’t wait to use it!

regarding slow internet connection, that would be really useful as I need to test how the app behaves in these conditions. Our app is completely relying on the internet and without it nothing really works

**Comment by AvdLee** [comment]
Airplane mode is now available, but keeping this open as a possible future implementation to test slow connections

**Comment by AvdLee** [comment]
Asked Apple during WWDC, I should use https://developer.apple.com/documentation/networkextension/neappproxyprovider

**Comment by AvdLee** [comment]
Alright, I've made progress here now that we have [RocketSim Connect](https://docs.rocketsim.app/features/hzQMSrSga7BGWvxdNVdwYs/introduction/iXHZvJWvedgZuVTN5V3YS1).

The idea would be to swizzle URLSession and configure a proxy that's hosted inside RocketSim.app. From there, I can build both Airplane Mode more reliably and Network Link conditioning.

## Resources
- https://forums.swift.org/t/option-to-make-connect-proxy-work-with-http-traffic/49737
- https://github.com/apple/swift-nio-examples/blob/main/connect-proxy/Sources/ConnectProxy/ConnectHandler.swift
- https://opticalaberration.com/2021/12/proxy-server.html
- https://github.com/derhuerst/simulate-network-conditions

**Comment by AvdLee** [comment]
Good news, got this working locally. Currently finalizing the implementation, will be available in the next major 13.0.0 release.

**Comment by AvdLee** [comment]
This is coming in 13.0.0:

https://github.com/user-attachments/assets/89398d09-8b87-43b5-806b-9cfcc5a2db31

<img width="1076" alt="CleanShot 2024-12-05 at 13 48 46@2x" src="https://github.com/user-attachments/assets/eb289799-8cde-4456-b21a-44e680ea048b">
