### ISSUE TITLE
Show floating windows when focus is lost

### ISSUE THREAD

**Issue by maylukas** [AvdLee/RocketSimApp#284]
**Is your feature request related to a problem? Please describe.**
When visually comparing screens and simultaneously making changes in a code editor, it would be helpful if the overlay would stay visible on focus loss.

**Describe the solution you'd like**
Add an option to keep the overlays on loss of focus.

**Describe alternatives you've considered**
Uberlayer - We are currently using it and are considering switching our team to RocketSim but this issue is currently keeping us from doing so.

**Comment by AvdLee** [comment]
@maylukas thanks for reporting in! Can I assume the code editor will always be Xcode? If so, I could build an option to keep the layers active when the switched-to application equals `Xcode.app`

**Comment by MarianLudwig** [comment]
Hey @AvdLee, I'm facing the same issue. However, I'm developing in React-Native, using WebStorm or VSCode as well as my browser during design checks. Is there a possibility to add an option to always keep the layers active?

**Comment by AvdLee** [comment]
@MarianLudwig thanks a lot for reporting in, that makes it clear I should make this option as flexible as just keeping it visible always. For your understanding: the challenge is that the RocketSim window is a floating window, so it would basically be shown on top of any other window. Therefore, I'm hiding it if an app other than the Simulator is visible.

Maybe I can calculate whether the active Simulator window is actually visible or whether it's hidden behind another application window and use that to hide/show.

T.b.c!

**Comment by AvdLee** [comment]
10.0.2 will introduce a global toggle to keep the floating windows visible at all times.

This is a first iteration to try and see if it will help in your cases.

![CleanShot 2023-03-18 at 20 12 55@2x](https://user-images.githubusercontent.com/4329185/226131399-526fca2c-82b0-4a23-b4d7-7965d2efe42a.jpg)

@scottwio @MarianLudwig @maylukas I'm keen to hear whether this would be sufficient enough!

**Comment by scottwio** [comment]
Perfect, thanks so much for doing this so quickly. Honestly, this is more than enough for my needs.
