### ISSUE TITLE
Change Localization

### ISSUE THREAD

**Issue by vykut** [AvdLee/RocketSimApp#286]
Would it be possible to add an option to change the locale for a given application? 
This would be useful for quick testing of different localizations

**Comment by AvdLee** [comment]
So I looked further into this and the only thing i can build is the ability to quickly relaunch an app in a specific language.

- No Simulator restart needed
- App gets restarted
- Debugger won't be attached anymore

Would that still be useful?

**Comment by AvdLee** [comment]
This will be implemented in 11.2.0, here's a preview: https://twitter.com/twannl/status/1684994256832745473?s=20
