### ISSUE TITLE
Trigger deeplinks from app menu while recording

### ISSUE THREAD

**Issue by xlsmearlx** [AvdLee/RocketSimApp#29]
**Is your feature request related to a problem? Please describe.**
Currently, I'm trying to record several deeplinks in my app, but the app icon change to stop recording and I'm unable to select one of my stored deeplinks.

**Describe the solution you'd like**
Maybe add an option to stop the recording or trigger a deeplink in the app menu.

**Comment by AvdLee** [comment]
This is a good point! I could make an "extra" statusbar icon for stopping the recording. I'll see what I can do!

**Comment by AvdLee** [comment]
This will be added in 4.1.1
