### ISSUE TITLE
Screenshots contain alpha and don't work for App Store Connect

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#302]
> The screenshots PNG with the optimise for app store turned on have alpha in the, so they get rejected from app store connect

Let's see if we need to disable custom backgrounds for these modes.

> I did add bezel, and it failed for me on iphones 14 pro max and 11 pro max

**Comment by AvdLee** [comment]
It might be related to drag & drop only: https://twitter.com/BrendanLiamT/status/1636631230916734976?s=20

**Comment by BrendanThompson** [comment]
Here are my settings:
![CleanShot 2023-03-17 at 19 31 07](https://user-images.githubusercontent.com/2595712/225853246-caed91ba-67a9-4d14-9026-352c8d5c4392.png)

This only happened when I dragged and dropped into ASC using Safari. It also didn't always occur. When I dragged three in only two were marked as failed the last one worked.

**Comment by BrendanThompson** [comment]
I spoke too soon! Went and checked ASC after about an hour or so 😢 

![CleanShot 2023-03-17 at 19 35 20](https://user-images.githubusercontent.com/2595712/225854105-35ebb4b9-fddf-4555-90e3-53d6ad3e77f1.png)

**Comment by AvdLee** [comment]
Found the issue, this will be solved in 10.0.2!
