### ISSUE TITLE
Feature request: Adjust simulator status bar

### ISSUE THREAD

**Issue by houtzager** [AvdLee/RocketSimApp#303]
**Is your feature request related to a problem? Please describe.**
When making screenshots or recordings, it's nice having a clean consistent simulator status bar. Right now I need to run some simctl command to achieve this.

**Describe the solution you'd like**
It would be great if I could configure a preset configuration in rocket sim, and activate this with one button click each time I need to make screenshots or recordings. In addition, it could be a setting to automatically apply this configuration before creating a screenshot or screen recording.

**Describe alternatives you've considered**
x

**Additional context**
![image](https://user-images.githubusercontent.com/1859059/224480018-497abcf3-0cb7-4933-91b9-8c5a854da91d.png)

**Comment by houtzager** [comment]
Ah, should've checked for similar issues before. Duplicate of: https://github.com/AvdLee/RocketSimApp/issues/173

**Comment by AvdLee** [comment]
Thanks for reporting, love the image you've created! I'll actually keep this one open because of that image ;-)
Fun fact: I actually wrote code for statusbar adjustment a long time ago. However, it seems that this feature is broken in latest simulators.

When that's working again, I'll definitely implement this!

**Comment by AvdLee** [comment]
Update:

This is still a known issue in the changelog of Xcode 15 beta 6

<img width="938" alt="CleanShot 2023-08-14 at 20 43 46@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/ddb047a5-0fef-45a7-90fa-68e904061d2e">

I filled feedback to Apple. In case you'd love to see this coming to RocketSim, I highly encourage to also file feedback. To make it easy, mention my feedback ID: FB12140796

**Comment by houtzager** [comment]
> Update:
> 
> 
> 
> This is still a known issue in the changelog of Xcode 15 beta 6
> 
> 
> 
> <img width="938" alt="CleanShot 2023-08-14 at 20 43 46@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/ddb047a5-0fef-45a7-90fa-68e904061d2e">
> 
> 
> 
> I filled feedback to Apple. In case you'd love to see this coming to RocketSim, I highly encourage to also file feedback. To make it easy, mention my feedback ID: FB12140796
> 
> 
> 
> 

A bit late perhaps, but done. ✅

**Comment by AvdLee** [comment]
This appears to be working now so I'm shipping this with 12.6.0:

<img width="860" alt="CleanShot 2024-01-26 at 22 28 57@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/0499e611-64e4-4313-a93c-3c7811ff0e36">

**Comment by houtzager** [comment]
That's awesome! 👏
