### ISSUE TITLE
MP4 videos are not playing in Slack

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#31]
Other videos are playing in Slack so it's weird that this one isn't!

**Comment by AvdLee** [comment]
The HEVC MP4 codec is not supported by Slack. Changing it to h264 fixed it!

**Comment by handsoffred** [comment]
>> The HEVC MP4 codec is not supported by Slack. Changing it to h264 fixed it!

Is this a slack setting the user can change?

**Comment by AvdLee** [comment]
@handsoffred this had to do with the internal settings in RocketSim. Is there anything not working for you?

**Comment by handsoffred** [comment]
yes, in Slack but not in RocketSim, sorry. I get a greenscreen when I post
MP4 videos but other team members see it fine. Based on the comments here
I'm going to try different encoding.
