### ISSUE TITLE
Deeplink grouping

### ISSUE THREAD

**Issue by houtzager** [AvdLee/RocketSimApp#314]
**Is your feature request related to a problem? Please describe.**
When having many deeplinks, it'd be nice to group them by environment/feature so that it's easier to find the one I need.

**Describe the solution you'd like**
Custom grouping of deeplinks. 

Because there are already deeplink groups focussed on bundle ids, this existing "group" should probably be renamed to "Apps" or so. 

**Describe alternatives you've considered**
Naming & sorting properly, though the sorting doesn't seem to work.

**Comment by drucelweisse** [comment]
I upvote this feature, because at our project we have over 50+ deeplinks that are associated with different product within application and it would be very useful to group them inside app group. And it's complicated to search a needed one between all of them

**Comment by AvdLee** [comment]
I'm closing this in favor of https://github.com/AvdLee/RocketSimApp/issues/464

This is definitely something I'm going to build short term, I totally see the value!
