### ISSUE TITLE
Video Performance

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#32]
**Describe the bug**
It seems that the performance of videos is not always optimal: https://twitter.com/pd959/status/1267812116792131584?s=20

**To Reproduce**
1. Download https://github.com/pd95/CS193p-Memorize
2. Try recording a video

**Expected behavior**
Smooth videos!

**Comment by pd95** [comment]
Somehow RocketSim keeps 5-7% CPU after having saved a file. Don't know what is going on. I will attach an analysis report from activity monitor.

[Analyse von „RocketSim“.txt](https://github.com/AvdLee/RocketSimApp/files/4740532/Analyse.von.RocketSim.txt)

**Comment by pd95** [comment]
Just to let you know: I've tested everything with Xcode 12 beta 1, and the stuttering persists.
The stuttering disappears only if I use the `codec` option in `simctl` (but the file size is  much bigger):

    xcrun simctl io 5DD37C26-6507-4EB1-8E57-151A110E8AA2 recordVideo --codec=h264 test.mp4

So I suppose the issue is that the my Mac cannot run the Simulator and the HEVC encoding in parallel.

**Comment by AvdLee** [comment]
@pd95 I'm afraid I can't do a lot about that as I'm dependent on `simctl` for the recording. I've at least fixed the CPU issue which is already great.

I'll keep an eye open for video performance improvements and will implement so if I'm able to!

**Comment by AvdLee** [comment]
Good news; to fix https://github.com/AvdLee/RocketSimApp/issues/31 I had to change the codec to h264. It's actually not that bad to do so, especially as it will fix your issue too! 🎉
