### ISSUE TITLE
Extend clickable area for `Grid/Rulers` options

### ISSUE THREAD

**Issue by menteValidus** [AvdLee/RocketSimApp#320]
**Is your feature request related to a problem? Please describe.**
When I want to disable `Grid` or `Rulers` I keep either misclicking labels or clicking on outside area as I used to larger action areas. It's a little bit frustrating for me.

**Describe the solution you'd like**
I would like to have extended clickable areas for `Grid/Rulers` buttons.

**Additional context**
Here's on the screen I highlighted extended clickable areas.
 
<img width="246" alt="Screenshot 2023-03-31 at 22 54 13" src="https://user-images.githubusercontent.com/39064926/229206832-07f6869a-b5d5-4ad4-9b57-0d70a3a102b4.png">

**Comment by AvdLee** [comment]
This will be fixed in 10.1.0!
