### ISSUE TITLE
Tooltips for screenshot tab shown on other tabs

### ISSUE THREAD

**Issue by thofreym** [AvdLee/RocketSimApp#321]
**Describe the bug**
Tooltips for the screenshot / screen recording tab are shown on other tabs.

**To Reproduce**
Go to any other tab than the screenshot tab and hover the mouse over any control.

**Expected behavior**
The tooltip for the control over which the mouse is hovering should be shown.

**Screenshots**
<img width="261" alt="Capture d’écran 2023-04-01 à 15 16 13" src="https://user-images.githubusercontent.com/67976669/229293375-cfa2c05d-2f30-41da-a4f4-e3b6bc6be966.png">
<img width="214" alt="Capture d’écran 2023-04-01 à 15 56 44" src="https://user-images.githubusercontent.com/67976669/229293442-da2d5ee8-424f-4529-8cc5-16886fe7a166.png">

**Desktop (please complete the following information):**
 - OS: 13.1

**Comment by AvdLee** [comment]
Yeah, this is an annoying one. I'll see what I can do!

**Comment by AvdLee** [comment]
Also reported by M. Stibane

**Comment by AvdLee** [comment]
This should no longer be happening
