### ISSUE TITLE
Overlay advanced settings from percentile to point

### ISSUE THREAD

**Issue by loicgriffie** [AvdLee/RocketSimApp#324]
**Is your feature request related to a problem? Please describe.**

Overlay advanced feature provide offset on X and Y but with a percentile value which do not help having a precise idea of some layout discrepancies

**Describe the solution you'd like**

This feature is great to find out any offset issue on layout and apply the same.

**Describe alternatives you've considered**

A value in point instead of percentile would much more useful for that use case.

**Additional context**

Version : 9.5.0 (139)

![Capture d’écran 2023-04-04 à 10 39 15](https://user-images.githubusercontent.com/1225240/229736754-406c24c8-96f9-42f6-9d26-36432a2faeb4.png)

**Comment by AvdLee** [comment]
Good idea @loicgriffie, it could potentially even be both. I'll see what I can do!

**Comment by AvdLee** [comment]
This will be fixed in 10.2.2
