### ISSUE TITLE
JPEG with bezel shows whitespace

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#327]
See this image from A. Weiß:

![image](https://user-images.githubusercontent.com/4329185/230437576-ef75b10b-7791-4bed-ab3f-7a9a18d4c2a5.png)

Probably due to half pixels

**Comment by AvdLee** [comment]
@alexanderwe this should be fixed in 11.0.0!

**Comment by alexanderwe** [comment]
@AvdLee I can confirm, I do not see this issue any longer. Thanks a lot for fixing it ! 🙂
