### ISSUE TITLE
Unreadable button in "light mode"

### ISSUE THREAD

**Issue by pd95** [AvdLee/RocketSimApp#33]
**Describe the bug**
When a video has been recorded, the buttons allowing to switch between MP4 and GIF are not well readable in light mode.

**To Reproduce**
1. Capture a video
2. After stopping the recording, the dialog which allows switching between GIF and MP4 has black text on dark gray background
3. See attached screenshot

**Expected behavior**
Readable buttons also on 

**Screenshots**
<img width="246" alt="Bildschirmfoto 2020-06-06 um 17 24 34" src="https://user-images.githubusercontent.com/25307503/83950497-6d5b9500-a82b-11ea-88b2-e88870f61d80.png">
<img width="246" alt="Bildschirmfoto 2020-06-06 um 17 24 40" src="https://user-images.githubusercontent.com/25307503/83950499-6e8cc200-a82b-11ea-840e-ab655217d423.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 10.15.5 (19F101)

**Additional context**
N/A

**Comment by AvdLee** [comment]
Fixed!
