### ISSUE TITLE
Dynamic type size indicator.

### ISSUE THREAD

**Issue by sanguish** [AvdLee/RocketSimApp#330]
The simulator allows you to easily change the dynamic type size, but it has no way to find out what they current type size is.

I know that adding support or dynamic type is on the roadmap, but I'm hoping that would include indicating what the current dynamic type size is.

**Comment by AvdLee** [comment]
This will be fixed in 10.2.0, see: https://twitter.com/twannl/status/1649859478114770954?s=20
