### ISSUE TITLE
Distribute RocketSim outside of the AppStore

### ISSUE THREAD

**Issue by itskoBits** [AvdLee/RocketSimApp#339]
I love RocketSim and use it on my personal Mac all the time. I can't install it on my work Mac because we have a policy that blocs the AppStore. Can you distribute RocketSim outside of the AppStore - e.g. as a dmg in Gumroad?

**Comment by AvdLee** [comment]
That's already possible, see: https://avanderlee.gumroad.com/l/rocketsim
(Similar to the Team licenses link on rocketsim.app)

Let me know if you have any questions!

**Comment by AvdLee** [comment]
Btw, great to hear you love RocketSim and you use it all the time ❤️  If you have anything I can improve, I'd love to know!
