### ISSUE TITLE
Copy gif to clipboard

### ISSUE THREAD

**Issue by akashnimare** [AvdLee/RocketSimApp#34]
Great little app. Been using https://www.getcloudapp.com/ for the same purpose. The one thing I really liked about CloudApp is that once you are finished recording up the gif, it will copy the same into your clipboard which really saves time. This is what I'm looking for -

* Move the setting for gif/mp4 to somewhere in preference

I think the whole thing here can be moved to preference since the user won't toggle it frequently 

![image](https://user-images.githubusercontent.com/2263909/83963160-79923180-a8c1-11ea-8b65-4bc736eff902.png)

**Comment by AvdLee** [comment]
I've decided to remember the switch position as a setting. This feels more intuitive!
The automatic copy to pasteboard is a bit harder as the GIF needs to be generated which takes time. Therefore, you wouldn't know when its actually added to your clipboard and it might be a worse experience.

**Comment by AvdLee** [comment]
Done!
