### ISSUE TITLE
Make sure the Simulator either boots or becomes active right after opening RocketSim

### ISSUE THREAD

**Issue by Fesh-com** [AvdLee/RocketSimApp#344]
**Describe the bug**
When I doubleclick RocketSim.app, nothing happens.

**To Reproduce**
doubleclick

**Expected behavior**
RocketSim launches (shows window, appears in dock, etc)

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - macOS 13.3.1
 - RocketSim 10.0.6

**Additional context**
today I wanted to try RocketSim. On first launch, it showed the "upgrade to pro" screen. I tried the yearly, but couldn't finish the payment (different problem, my main AppleID is from Germany, but I live in Austria now and Apple doesn't allow austrian credit cards with a german AppleID. It seems I need to buy a german giftcard to get money there).
So finally I chose "Go basic" to test RocketSim...
And then nothing happened. So I re-launched Xcode, and the simulator - but RocketSim does not launch anymore.
Which logfile do you need?

Marc
marc@fesh.com

**Comment by Fesh-com** [comment]
Dang. You really should add _some_ feedback when launching the app by doubleclick.
I just clicked in my simulator window, and the RocketSim window appeared.

I now have "Always show windows" active - please make this the default. Or turn it around to "Hide window when Simulator is not in front", default off.

**Comment by AvdLee** [comment]
> And then nothing happened. So I re-launched Xcode, and the simulator - but RocketSim does not launch anymore.

This is actually fixed in 10.2.1: I'm now launching the Simulator

> Dang. You really should add some feedback when launching the app by doubleclick.

This is great feedback and I never thought of it! Tunnel vision for me since I'm so used to opening the Simulator right after launch.

I'll reopen this ticket and rename it, to account for making sure the Simulator either boots or becomes active right after opening RocketSim 👌

**Comment by AvdLee** [comment]
This will be fixed in 10.2.2
