### ISSUE TITLE
Send push notifications

### ISSUE THREAD

**Issue by jnwagstaff** [AvdLee/RocketSimApp#35]
I love that you can open deeplinks easily, it would also be awesome to be able to send notifications through APNS to ensure all the setup is correct.

**Comment by AvdLee** [comment]
Yes, totally agree! I’m planning to build this just like with deeplinks in a manageable manner 💪🏻

**Comment by Sherlouk** [comment]
Going to drop a plus one and subscribe to updates on this. Would love this capability with the ability to create multiple sample APNS payloads and quickly send them (especially while recording to demo key journeys etc!)

**Comment by AvdLee** [comment]
Yeah, this is still something on top of my mind, but I just didn't get to building it yet! I'll see if it fits the 9.0 release in Q4!

**Comment by Sherlouk** [comment]
Aye no pressure Antoine, your product, your roadmap! I think with Live Activities and such coming through now though, and the ability to drive/update them from push notifications, it would be an ideal time to add this capability.

**Comment by AvdLee** [comment]
Totally, couldn't agree more! It actually fits my roadmap perfectly well, so expect this in Q4!

**Comment by AvdLee** [comment]
This is finally fixed in 9.0.0! If you're open to help me test it out, contact me at contact@avanderlee.com for a TestFlight invite 🙏🏻
