### ISSUE TITLE
Automatically update timezone to match location change

### ISSUE THREAD

**Issue by ohkhan** [AvdLee/RocketSimApp#353]
**Is your feature request related to a problem? Please describe.**
When I change locations using RocketSim I need to manually update my Mac's system time to match timezones. Ideally there should be done an option for this to work automatically.

**Describe the solution you'd like**
When I change locations it'd be great if timezone for the simulator updated accordingly. Based on my research it isn't possible to change just the simulator timezone without changing the host device's timezone as well. Changing the host machine's timezone could be accomplished by using `sudo systemsetup -settimezone`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AvdLee** [comment]
That's a super interesting idea! Thanks a lot for doing the extra research by telling me how it can be done systemwide. I'll see what I can do!

**Comment by ohkhan** [comment]
Yeah that approach sounds good to me! Restart is totally acceptable for my use case.
Appreciate the promptness. Looking forward to this feature 😀

**Comment by AvdLee** [comment]
How does this look?
https://twitter.com/twannl/status/1684608083258130433?s=20

**Comment by ohkhan** [comment]
Amazing this is perfect! Thank you!

**Comment by AvdLee** [comment]
This will be implemented in 11.1.0

**Comment by AvdLee** [comment]
In case you don't want to change the location, but just the time zone: https://twitter.com/twannl/status/1685010160521981952?s=20
