### ISSUE TITLE
Adding a deeplink with leading or trailing whitespace causes the link to be removed

### ISSUE THREAD

**Issue by renssies** [AvdLee/RocketSimApp#36]
**Describe the bug**
I was creating a group of deeplinks and discovered that if I press + any deep links with leading or trailing whitespace are removed. 

**To Reproduce**
1. Open the preferences
2. Create a new Deeplinks group
3. Set a title
4. Click the plus to add a deeplink
5. Enter a title for the deeplink
6. Enter the URL but add a space before or after the URL
5. Click the plus again for a new deeplink, the deeplink that was just entered disappears. 

**Expected behavior**
I expect the URL to be saved with the trailing or leading white space removed (trimming), you often copy a link and accidentally leave whitespace. Especially if you have to copy a lot of links.

**GIF**
![2020-06-17 17-34-33 2020-06-17 17_36_22](https://user-images.githubusercontent.com/830094/84918590-15415000-b0c1-11ea-8422-cc0f68e64bb7.gif)

**Desktop:**
 - OS: macOS 10.15.5
 - Version 2.1.0 (29)

**Comment by AvdLee** [comment]
Oh, wow, nice catch! This should be easy to fix. I'll add it to the roadmap.

**Comment by AvdLee** [comment]
Fixed!
