### ISSUE TITLE
Magnifier coordinates are vertically inverted

### ISSUE THREAD

**Issue by mstrokin** [AvdLee/RocketSimApp#364]
As you can see I'm poiting at the top of the screen but coordinate is 631
<img width="599" alt="image" src="https://github.com/AvdLee/RocketSimApp/assets/564552/cca2a039-691b-4076-8d2b-69ae05b83071">

Rulers are working fine (i.e. zero is at the top)

**Comment by AvdLee** [comment]
Thanks for reporting in, that should be fixed! 🙏

**Comment by AvdLee** [comment]
This will be fixed in 11.2.1
![CleanShot 2023-08-19 at 14 37 50@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/5a6340f2-2e39-4192-8e20-2eb21f97c2d0)
