### ISSUE TITLE
Not able to record a transparent video

### ISSUE THREAD

**Issue by ridmaur** [AvdLee/RocketSimApp#365]
**Describe the bug**
Not able to create a transparent video of simulator showing bezels.

**To Reproduce**
1. Configure RocketSim> Settings > Bezels turned on.
2. Set Background color and Frame color to a color both with opacity to 0 (should mean fully transparent).
3. Record an MP4 video with 'Add Device Bezels', 'Touches', 'Remove Watermark' turned on. "Record Audio" and "App Preview Optimized" turned off.

**Expected behavior**
Would expect the resulting MP4 to have a transparent background.

**Desktop (please complete the following information):**
 - OS: Ventura
 - Version: 13.4

**Comment by AvdLee** [comment]
Would you mind trying to copy the resulting video into Keynote and see if it's transparent? 

I'm pretty sure it works, I just verified it myself:
![CleanShot 2023-06-13 at 19 17 08@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/982ace94-1920-4c33-a222-e8c99f3267fb)


The thing is: QuickTime would not show transparency: 
![CleanShot 2023-06-13 at 19 17 38@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/94068f59-2870-4e26-9805-27731752db24)

QuickTime shows a black background, making it look like alpha videos aren't supported.

**Comment by AvdLee** [comment]
It's probably Twitter not supporting transparent videos 🤔
