### ISSUE TITLE
Don't Enable Device Frames for App Preview

### ISSUE THREAD

**Issue by alexsereno** [AvdLee/RocketSimApp#366]
**Is your feature request related to a problem? Please describe.**
Apple rejects apps when "The app preview includes device images and/or device frames." Although they sometimes slip and let apps through, its against their policy. Screenshots are allowed to have device frames from what I can tell, but not video previews.

**Describe the solution you'd like**
If "optimize for app preview" is selected, automatically remove device frames if checked.

**Describe alternatives you've considered**
Rerecord my entire rejected video because I still had device frames checked 😭

**Additional context**
Rocket Sim is crucial for [ironiq.app](https://ironiq.app)! Great work :D

**Comment by alexsereno** [comment]
Yeah its an interesting UX problem! Perhaps toggling optimize for app previews unchecks device bezels, since no app preview can have bezel, and unchecking it re-enables bezels if you had it selected. This way its sort of clear that bezels and app preview can't be on together. This is similar to how you currently output a JPG instead of a PNG screenshot if optimize for app previews is enabled as apple doesn't allow transparency in screenshots.

Either way rocketsim is super crucial for me!

**Comment by AvdLee** [comment]
I'm closing this issue as I don't think it's worth implementing since many of my apps never get rejected with RocketSim bezels 🙏
