### ISSUE TITLE
Allow re-ordering of deeplinks

### ISSUE THREAD

**Issue by renssies** [AvdLee/RocketSimApp#37]
**Is your feature request related to a problem? Please describe.**
I have several deep links that link to parts of a profile page. So I've named them "Profile -> PART". However, I copied the links in random order and now they are in a random order in the menu bar item. 

**Describe the solution you'd like**
I would like to drag a deep link to re-order it, similar to dragging an item in the Xcode or Finder sidebar. A way to (auto-)sort by title would also be a solution.

**Comment by AvdLee** [comment]
Makes total sense! Thanks for reporting in. I've already had it on my list but it hasn't been a priority yet. I'll see what I can do!

**Comment by AvdLee** [comment]
Fixed and scheduled for the next update! https://twitter.com/rocketsim_app/status/1286007245545844736?s=20
