### ISSUE TITLE
Audio Recording not working

### ISSUE THREAD

**Issue by pnome** [AvdLee/RocketSimApp#373]
**Describe the bug**
When I try to record the simulator audio, it doesn't work.

**To Reproduce**
Try to record audio from the simulator.

**Expected behavior**
I expected it would record audio.

**Screenshots**
Here's a recording of me trying to get it to work. Apologies that it's from an iPhone - I just didn't want to be screen recording in case that interfered with what I was actually trying to do.
https://www.loom.com/share/e8751d564f30454e850c97ddc2887945?sid=eff21c96-07bc-4de5-84c8-ba6131af7b45
Other apps that record system audio work fine. I've tried killing other apps that do things with system audio (Loopback, Loom, Blackhole) and it still doesn't work

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.4 (22F66)

**Comment by AvdLee** [comment]
Reminder for myself to email @pnome using the email address shared on Twitter.

**Comment by AvdLee** [comment]
Reopening since there's still scenarios it doesn't work. Let's add more debug logs and continue investigation

**Comment by AvdLee** [comment]
The issue should now be fixed in the latest 11.0.0 release
