### ISSUE TITLE
Floating windows not appearing (Xcode 15b3, iOS 17)

### ISSUE THREAD

**Issue by nesevis** [AvdLee/RocketSimApp#375]
⚠️ Xcode 14.3 works as intended, this is specifically about Xcode 15)

RocketSim Version: 10.5.1 (164)
macOS: Ventura 13.4
Xcode: 15b3
Sim: iPhone SE iOS 17

Xcode is located in `/Applications` and `xcode-select` is using the same version

I just installed the app and granted the necessary permissions.

It detects recent builds and lets me run them, but there is no simulator control (image recording; floating controls).

## Things I've tried
- I have network-wide ad blocking, which blocked the app's amplitude tracking. Disabling the blocking didn't change anything.
- Deleting UserDefaults.
- Reinstall the app.

edit:

Console logs report the following when I try to start a recording:

`error	10:04:35.161451+1000	RocketSim	deviceProfileMissing [Recording starting failed]`

I also see these errors:

`error	10:05:41.920777+1000	RocketSim	Warning: Window NSMenuWindowManagerWindow 0x10e64b740 ordered front from a non-active application and may order beneath the active application's windows.`

`error	10:14:30.454880+1000	RocketSim	missingChromeJSON(path: "/Applications/Xcode15b3.app//Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Chrome/phone.simdevicechrome/Contents/Resources/chrome.json") [Frame info fetching failed]`

> /Applications/Xcode15b3.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Chrome/phone.devicechrome/Contents/Resources

…is a valid path, with the only difference being `phone.devicechrome` doesn't have the sim prefix.

**Comment by AvdLee** [comment]
Thanks for reporting in, @nesevis! This is already fixed for 11.0.0 for which you can join the TestFlight if you like:
https://testflight.apple.com/join/ORz3QWRv

I'm hoping to release this in two weeks.

**Comment by stuffmc** [comment]
Do we meed Pro to see that window? It doesn't appear with macOS 14.2.1, Xcode 15.1 and SImulator 1019

**Comment by AvdLee** [comment]
@stuffmc definitely not! Could you select "Report an issue" from the status bar menu and contact me there? I'd love to find out your issue!
