### ISSUE TITLE
Fine tune of zoom and offset

### ISSUE THREAD

**Issue by carlosypunto** [AvdLee/RocketSimApp#380]
In comparing functionality, for fine tune of zoom and offset, the slider is not very precise. 

I propose to put a couple of buttons on each value to increase or decrease it by clicking on it.

**Comment by sprejjs** [comment]
Yes, please, being able to modify the offset by 1 pixel is something I wish I had as well. Keyboard shortcuts might work very well, or being able to set the value with the keyboard instead of using sliders.

**Comment by AvdLee** [comment]
This will be fixed in 11.2.1:

<img width="710" alt="CleanShot 2023-08-19 at 14 26 04@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/cbf91ea5-e507-49d0-b2a7-d620a768d3b0">
