### ISSUE TITLE
Link to App Group Container

### ISSUE THREAD

**Issue by sena-mike** [AvdLee/RocketSimApp#383]
**Is your feature request related to a problem? Please describe.**
We have links to bundle, sandbox, etc but seemingly no link to the app group container for the entitlements on the app.

**Describe the solution you'd like**
A link to open the app group container in the same list as the sandbox link.

**Describe alternatives you've considered**
I log the URL for the app group container currently.

**Additional context**
App groups are stored in:
`/private/var/mobile/Containers/Shared/AppGroup/**`

https://developer.apple.com/documentation/xcode/configuring-app-groups

**Comment by AvdLee** [comment]
Great idea and low hanging fruit! I'll try to squeeze this into the next development cycle!

**Comment by AvdLee** [comment]
@sena-mike this feature actually already exists!

<img width="1042" alt="CleanShot 2023-08-18 at 15 31 20@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/38f4b19a-4d09-4b86-bb13-797f443495e6">

I wonder whether the issue isn't working as expected for you?

**Comment by sena-mike** [comment]
Amazing, I must have missed this. Thanks
