### ISSUE TITLE
Quick location selection

### ISSUE THREAD

**Issue by minamikhael1** [AvdLee/RocketSimApp#387]
RocketSim makes it super easy to add locations using search or by directly selecting a location by moving a pin on a map.
It would be awesome if I can also select my saved locations from a dropdown (for example) instead of having to do multiple steps to activate them (send them to the simulator)

I might be facing some bug because after saving locations, I still get a message:
`No locations found for [MyApp]`

So for now if I want to select an already saved location:

1. I have to click on "Configure locations"
2. Click on a saved location
3. Click on the "Send"

Suggestion:
1. Click on some dropdown, it shows my saved locations
2. Selecting one of them should directly send it to the simulator.

This way it would be much more intuitive. 

[UPDATE] After playing with the app a bit. I found out that if I created a new "Group" and select my app's bundleID for that group, locations start to show as buttons, so maybe it's a bug because I also tried to restart the simulator and RocketSim but it didn't work

[UPDATE] Default group (which was already created) was just missing the bundleID when I added it, buttons showed up as well. no need to create a new group.

**Comment by AvdLee** [comment]
It sounds more like I should update my onboarding to make it clearer how groups work rather than a request to change how to use saved locations, do you agree?

If not, I'm happy to reopen, but the app is designed to work bundle-identifier-based.

Keep me posted!

**Comment by minamikhael1** [comment]
I agree!
