### ISSUE TITLE
gif quality

### ISSUE THREAD

**Issue by crabucate** [AvdLee/RocketSimApp#39]
**Describe the bug**
The gifs have grey stripes in white areas.
**To Reproduce**
1. Record a gif with a white tableviewcontroller

**Expected behavior**
Well, it should be white. ;)

**Screenshots**
![crabnotes](https://user-images.githubusercontent.com/61051016/86378558-127e5780-bc8a-11ea-94c2-472e885b0301.gif)

**Comment by AvdLee** [comment]
Thanks for reporting in, this should indeed be better!

**Comment by AvdLee** [comment]
This is fixed with 3.0
