### ISSUE TITLE
Spoofing camera and microphone

### ISSUE THREAD

**Issue by frees11** [AvdLee/RocketSimApp#393]
Hi, 

is it possible to add camera spoofing? So when application is open in simulator and I have feature which uses camera, I can fake data for camera from image or playing video. Analogically with microphone? So now I can test for example QR recognition or sound recognition without real device?

Thanks

**Comment by AvdLee** [comment]
Although I wish this was possible, I'm not able to implement this. It's out of my possibilities :(
