### ISSUE TITLE
Cannot add app for 'Improved focus support'

### ISSUE THREAD

**Issue by pcolton** [AvdLee/RocketSimApp#4]
In the main pref window, clicking on Enable does bring up prefs, but RocketSim is not in the list and I cannot drag-drop in the app either, so there's no way for me to enable the improved focus support.

macOS 10.15.4

**Comment by AvdLee** [comment]
Hmm, that's interesting! I'll see what I can do

**Comment by AvdLee** [comment]
@pcolton does this issue still happen in 1.1.0?

**Comment by pcolton** [comment]
Yes, still happens, I don’t see RocketSim in the list of apps I can select. I’ll try install and reinstall.

**Comment by pcolton** [comment]
Reinstalling didn’t help. Might I need to clear out prefs or something?

**Comment by AvdLee** [comment]
@pcolton would you mind sharing a screen recording of the issue? You could mail it to me at contact@avanderlee.com if you like to keep it private

**Comment by pcolton** [comment]
Am I supposed to see RocketSim in that list of allowed screen sharing apps? I assume so.
[Screen Recording 2020-05-03 at 8.15.07 AM.mp4.zip](https://github.com/AvdLee/RocketSimApp/files/4570843/Screen.Recording.2020-05-03.at.8.15.07.AM.mp4.zip)

**Comment by AvdLee** [comment]
@pcolton yes, you should! 

![image](https://user-images.githubusercontent.com/4329185/80946413-4d7d1f80-8dee-11ea-8894-61e8770c9286.png)

I'll try to figure out what's going on here. Thanks for the recording!

**Comment by AvdLee** [comment]
I think I know what's going on, this will be fixed in 1.3.0!

**Comment by pcolton** [comment]
Wonder if this is related. I can try. 

https://ericasadun.com/2020/05/04/catalina-permissions-chrome-zoom-etc/

-Paul

**Comment by AvdLee** [comment]
I'm pretty sure the upcoming update will fix this for you. To end up in that list, the app should've used screen recording APIs at least once (of course, without it working as there's no permission). After that, the system will show the alert automatically and list RocketSim.

I'll keep you posted on the release, if it doesn't work, we can try out the link!

**Comment by AvdLee** [comment]
I've submitted 1.2.1 that fixes this. Please, feel free to reopen if this issue still occurs. Thanks for reporting in!

**Comment by pcolton** [comment]
Good news, fixed!

<img width="349" alt="image" src="https://user-images.githubusercontent.com/92073/81331858-12c9f000-9057-11ea-8411-b84c1566553a.png">

**Comment by AvdLee** [comment]
Nice!!! Thanks for replying back to me!
