### ISSUE TITLE
Brew formulae

### ISSUE THREAD

**Issue by hamsternik** [AvdLee/RocketSimApp#40]
**Is your feature request related to a problem? Please describe.**
Add Brew support

**Describe the solution you'd like**
Add Home-brew formulae like [the bunch of other macOS apps](https://formulae.brew.sh/formula/).

Actually I don't know should I add the steps of implementation for that one or not 😬

**Comment by AvdLee** [comment]
Hi @hamsternik,

What exactly do you want to do with Home-brew support? I don't see how this works with Mac Apps 🤔

**Comment by AvdLee** [comment]
Closing this for now as I don't see what I can do here

**Comment by hamsternik** [comment]
@AvdLee I mean to add the feature to install your app via Homebrew. Something like `brew cask install rocketsim`.

One point that confused myself about add it to Homebrew is that the app is not free but you sell it via AppStore. So if you want to add the possibility be installed via Homebrew you have add some sort of **buy Licence** logic inside your app.

**Comment by AvdLee** [comment]
@hamsternik gotya, makes sense. Indeed, it's not something I have for now! I'll revisit this if anything changes.
