### ISSUE TITLE
Simulate MFMessageComposeViewController

### ISSUE THREAD

**Issue by Swany** [AvdLee/RocketSimApp#400]
The Simulator does not allow an app to bring up the Messages UI (you get an alert saying "Your device is not capable of sending text messages.")

I would like a faux Messages UI that displays the recipients, subject. body. It doesn't need to do anything other than present (with data filled in) and go away when cancel is pressed. This would allow demoing/recording apps that make use of the link to Messages feature.

Super Bonus points for handling MFMailComposeViewController in a similar way.

**Comment by AvdLee** [comment]
Thanks for the request, @Swany. Unfortunately, this is something I can't build since I can't influence the inner Simulator functionality. If anything changes in the future, I'll reopen accordingly.
