### ISSUE TITLE
Light mode for floating windows 💡

### ISSUE THREAD

**Issue by casperriboe** [AvdLee/RocketSimApp#402]
**Is your feature request related to a problem? Please describe.**
- At times it can be difficult to see the contrasts of the floating windows on some monitors. On my primary external monitor in particular I have a hard time gauging the windows' surroundings due to the dark material backgrounds on top of other programs that has a dark UI. 
During the day I generally have my system UI light, while some websites or programs I prefer to have dark.

**Describe the solution you'd like**
- Support light mode in the floating windows, using the light version of the background materials.

**Describe alternatives you've considered**
- Minimising other content I have behind my simulator and RocketSim - however tedious.

**Additional context**
- N/A.

**Comment by AvdLee** [comment]
Thanks for your request! I can indeed see the value of this. I'll see what I can do, but it will likely be somewhere Q4 at earliest.

**Comment by AvdLee** [comment]
I decided to not do this since it's not the style of RocketSim. It matches the Simulator colors which also doesn't come with a light mode.
