### ISSUE TITLE
Add a shortcut to minimize the window

### ISSUE THREAD

**Issue by danilolutti** [AvdLee/RocketSimApp#404]
Please add a close button: every time I want to hide the panel I have to click twice: dots -> minimize windws.
A close / hide button will be very useful!

**Comment by AvdLee** [comment]
Thanks for your report! I won't be adding a close button since the use case is too small and there's not enough visual space for such button. What I can do is adding a shortcut for minimizing the RocketSim window. Would that be a good alternative?

**Comment by SubvertDev** [comment]
I agree, a button before or after dots to minimize the window would be great, it really annoys to click two times for such common use case. Shortcut would be also great, but only if you can change it.

**Comment by AvdLee** [comment]
This will be available in 12.3.0!
