### ISSUE TITLE
Toggle/Shortcut for Slow Animations

### ISSUE THREAD

**Issue by mfreiwald** [AvdLee/RocketSimApp#408]
**Is your feature request related to a problem? Please describe.**
I often use the **Slow Animations** toggle to make animations and transitions perfect. It's sad that the simulator doesn't have a shortcut for it, because then I could easily switch between both states.

**Describe the solution you'd like**
A simple toggle in Rocketsim + Shortcut (only shortcut would also be fine) to enable/disable **Slow Animations**

**Comment by AvdLee** [comment]
The toggle will be available in 13.0.0:

https://github.com/AvdLee/RocketSimApp/assets/4329185/e5731149-cbb7-46a5-8fda-944806c9798a
