### ISSUE TITLE
How do I cancel the free trial?

### ISSUE THREAD

**Issue by broderick99** [AvdLee/RocketSimApp#409]
I signed up for a free trial but I want to cancel it. It appears to be impossible to do so. Please help

**Comment by AvdLee** [comment]
Hi @broderick99,

Just like with any subscription that you purchase with Apple, a trial always continuous till the end. Once the trial ends, the subscription will start, unless you cancel the subscription using Apple's subscription management. The latter can be found inside your iCloud account.

Hope that helps!
