### ISSUE TITLE
Unresponsive floating window after double recording

### ISSUE THREAD

**Issue by pd95** [AvdLee/RocketSimApp#41]
**Describe the bug**
After recording a video (=start & stop, floating window appears), I was not happy due to an oopsie while recording. Therefore I didn't "save" or "copy" the result of the capture and started a new recording.
After finishing the second recording, the floating window updates its content with the new capture, but is completely unresponsive... RocketSimApp has to be killed to get usable again.

**To Reproduce**
1. Open up a Simulator window, and choose "Start recording".
2. After a few seconds, stop recording. The floating window with your capture appears. The window is fully responsive, as we can hover over the window and it will show the options "mp4/gif" and the "copy" & "save" buttons. 
**Do not click** any of them!
3. Choose again "Start recording".
4. Choose again "Stop recording". The floating window will refresh, but is now unresponsive. The buttons do not appear.

To recover from the bug, RocketSim has to be quit and restarted.

**Expected behavior**
Floating window should be responsive. I.e. if the user did not save/copy the previous capture, it should probably be discarded and replaced with the new capture.

Perhaps RocketSim should collect the captures which haven't been copied or saved anywhere, so that the user can come back and check them? Alternatively, it could alert the user that he didn't save/copy his previous capture and that it will be lost?

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5 (19F101)
 - Version: RocketSim for Xcode 2.2.1

**Additional context**
N/A

**Comment by AvdLee** [comment]
Fixed and will be included in the next release!
