### ISSUE TITLE
Screen mirror from real device

### ISSUE THREAD

**Issue by KamilLukasiewicz** [AvdLee/RocketSimApp#411]
Currently, Rocketsim mainly serves developers. Designers are unlikely to use Xcode. It would be great to be able to make a mirror of an app build from a real device (iPhone) connected by cable to a computer. Something like https://getbezel.app/ does but with the view overlay options that Rocketsim provides and stuff like that.

**Comment by AvdLee** [comment]
I'll see what I can do! Will be 2024 at earliest though 🙏

**Comment by AvdLee** [comment]
Closing this as we have iPhone Mirroring! Do note that I'm considering adding support for it: #524
