### ISSUE TITLE
Screenshot & Screen Recordings has stopped working

### ISSUE THREAD

**Issue by roblabs** [AvdLee/RocketSimApp#417]
**Describe the bug**
Screenshot & Screen Recordings has stopped working

macOS Sonoma 14.0 (23A344) on x86
RocketSim 12.0.0
Xcode 15.0.1

**To Reproduce**
1. Start simulator
2. Start RocketSim and choose "create Screenshot" from the menu
3. Message that says "Creating a PNG..." is shown with no update nor progress
4. 

![image](https://github.com/AvdLee/RocketSimApp/assets/118112/e927ec25-6bbb-43da-a30c-299a276edeb1)

**Expected behavior**
RocketSim screenshots worked fine, up until updating today to latest in Apple App Store.  I don't know what version I had previous that was working

**Additional context**
* look like the container has data in `~/Library/Containers/com.swiftLee.RocketSim/Data/tmp`
* We have tried removing and reinstalling app and deleting any containers or "Application Support" folders
* This is one of our favorite paid apps, and I'm happy to renew when my year subscription is up.
* #240 
* Thank you

**Comment by AvdLee** [comment]
@roblabs thanks for reporting in! I've had another user reaching out. This will be top priority for me this weekend. Sorry for the inconvenience!

**Comment by roblabs** [comment]
@AvdLee — Thank you for fixing.

Fixed in RocketSim 12.0.1

**Comment by AvdLee** [comment]
@roblabs thank you for reporting in so quickly and help me keep RocketSim stable 💪
