### ISSUE TITLE
Show a countdown before recording ⏱

### ISSUE THREAD

**Issue by atrinh0** [AvdLee/RocketSimApp#42]
**Is your feature request related to a problem? Please describe.**
When "Start recording", it often starts immediately, we need to watch for the notification that it is recording, and then quickly read the message to verify that it is recording. Then we quickly move the mouse pointer back over the the simulator to start our interactions.

**Describe the solution you'd like**
When we do a screen recording using Quicktime, there is a configurable (none/5/10 second) countdown shown before it actually begins.

<img width="400" alt="Screenshot 2020-07-24 at 12 28 15" src="https://user-images.githubusercontent.com/16542463/88386862-2872ca00-cda9-11ea-9699-70ba8c0906e5.png">

When doing a screen recording on iOS, there is a 3 second countdown before it begins.

<img width="400" alt="Screenshot 2020-07-24 at 12 28 15" src="https://user-images.githubusercontent.com/16542463/88387098-ae8f1080-cda9-11ea-9824-610d923e191f.gif">

These give us visual prompts to get ready to interact with the screen, so we can get ready before it actually begins, and avoids the need to read the notification to see if it is actually started recording. Sort of like when a photographer counts down before taking your picture so you can strike that pose. 🕺🏻

**Describe alternatives you've considered**
This is more of a QOL improvement, keyboard shortcuts (more advanced) allows us to anticipate the notification in the corner of our eye, and get prepared to interact with the simulator.

**Comment by AvdLee** [comment]
I can see this being a very welcome change. I'll see what I can do!

**Comment by AvdLee** [comment]
I'm closing this issue as won't do. I believe the trimming functionality allows to optimize the outcome recording if you will. The RocketSim UI is not allowing me to build this nicely without complex & hidden UI.
