### ISSUE TITLE
Consider showing all `plist` files from App Group `Preferences` directory for User Defaults Editor

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#422]
Requested by R. Stone:

> First, thanks for Rocket sim. I’ve been working on geolocation stuff recently and it’s saved me a ton of time updating permissions and changing locations. I did run into an unexpected behavior today though. We use the feature of userdefaults of using different suites or domains to separate dependencies accessing segregated defaults. I went to use the user defaults viewer and wasn’t seeing my data so I verified in-app that it worked as expected. Then once I looked further I saw there are multiple plist files present in the directory but Rocketsim only sees the main one. Could you add a feature where it lists all user default domains?

I'm wondering whether we can basically show all `plist` files from the `Preferences` directory 🤔

**Comment by AvdLee** [comment]
![CleanShot 2023-11-08 at 15 56 02@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/4adba2ca-da2c-42c0-91d2-9e54e35988b6)

This will be fixed in 12.1.0

**Comment by MichaelDeVriesAh** [comment]
@AvdLee I'm running version 12.3.0 (with a pro subscription) and have quite some .plist files in the preference directory, but is not showing any of them in the selection menu.

<img width="1308" alt="Scherm­afbeelding 2023-12-13 om 14 20 22" src="https://github.com/AvdLee/RocketSimApp/assets/127212229/f33ccbd4-1b14-4099-8c1a-df93f837f902">

**Comment by AvdLee** [comment]
@MichaelDeVriesAh thanks for letting me know, I'll see what I can do to fix this!

**Comment by AvdLee** [comment]
@MichaelDeVriesAh this will be available in 12.8.0:

<img width="627" alt="CleanShot 2024-03-25 at 15 08 57@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/1675906f-0197-4462-a93e-b0ff511ab667">
