### ISSUE TITLE
Adding app to the Setapp distribution

### ISSUE THREAD

**Issue by LukasAnda** [AvdLee/RocketSimApp#425]
**Is your feature request related to a problem? Please describe.**
I would like to try this app, but I already have some subscriptions. Would it be possible to perhaps partner in the future with Setapp that provides a lot of these tools? I think it would be a great addition.

**Describe the solution you'd like**
Add the app into Setapp distribution

**Comment by AvdLee** [comment]
Hi @LukasAnda, thanks for reaching out. Unfortunately, I don't have any plans to add RocketSim to Setapp.
