### ISSUE TITLE
Option to Always Save Screenshots/Recording without having to Confirm

### ISSUE THREAD

**Issue by UnderscoreDavidSmith** [AvdLee/RocketSimApp#426]
I often use the Screenshot/Recording features in RocketSim to document the creation of my apps. What I desire is for these captures to then be written to my chosen output directory without requiring any further user interaction.  Right now I'm hitting "create screenshot" and then "Save" over and over again.  In my case I never need to choose between the other options in the little preview window which pops up.  I realize that this might not be great as a default, but if there were an option in the Capture settings for "Save without Confirmation" it would be great.  

Thank you for your consideration!

**Comment by AvdLee** [comment]
@UnderscoreDavidSmith thanks for reporting in! I'm all for making RocketSim fit anyone's workflow, so customization options would be part of that too.

Would it be fine to still see the floating thumbnail for progress, but that it will disappear after completion and save?

**Comment by UnderscoreDavidSmith** [comment]
Thanks for considering this.  Absolutely, the floating thumbnail is great to confirm that the capture has occurred.  I just end up with a giant stack of them over on the side of my screen and it would be great for them to just automatically save without needing to individually click through and say "save", "save", "save".
