### ISSUE TITLE
Add Screenshot Device Size to filename

### ISSUE THREAD

**Issue by joshuabryson** [AvdLee/RocketSimApp#428]
**Is your feature request related to a problem? Please describe.**
It would be helpful to add the device size to the screenshot filename. For instance, iOS 14 simulator would have a device size of 6.1. That way selecting images for App Store Connect would be a little easier since you could easily see which display to select when adding screenshots. 

**Describe the solution you'd like**
Currently (version 12.02.2 (182) a saved image has a file name similar to:
`RocketSim_Screenshot_iPhone_14_2023-11-08_12.06.33.jpeg`

We could update it to something like
`RocketSim_Screenshot_6.1_iPhone_14_2023-11-08_12.06.33.jpeg`

Adding the size after the generic screenshot would allow sorting by name to group the images by sections for App Store connect. 

**Describe alternatives you've considered**
Adding the size to any place in the filename would be beneficial.

**Comment by AvdLee** [comment]
Love this idea! It's simple to add, so I'll add it to my backlog!

**Comment by AvdLee** [comment]
This will be fixed in 12.3.0:
`RocketSim_Screenshot_iPhone_15_Pro_6.1_2023-11-28_19.52.17.png`
