### ISSUE TITLE
UserDefaults reader / editor for physical devices

### ISSUE THREAD

**Issue by KaiOelfke** [AvdLee/RocketSimApp#429]
The new user defaults reader and editor is quite useful. So I'd also like to use it for apps on real devices. I understand that this is maybe out of scope for a simulator app or perhaps also technically not possible. In this case the suggestion can be closed.

**Comment by AvdLee** [comment]
Indeed, that would be great, but technically impossible! I'm unable to read files from a connected iPhone as for now. If that changes in the future, I'll reopen and revisit, since it would be pretty awesome!
