### ISSUE TITLE
Save mp4 & gif by default option 💾

### ISSUE THREAD

**Issue by atrinh0** [AvdLee/RocketSimApp#43]
**Is your feature request related to a problem? Please describe.**
We have a choice of only `mp4` or `gif`, however if you wanted both you have to record it again to save it again.
Let's say you recorded that perfect clip and wanted to share the `gif` on GitHub and save the `mp4` to include in an AppStore preview video, you'd need to do that twice.
Another issue is when dragging the saved modal to drop the file somewhere and making a mistake (GitHub window isn't open), cancelling the drag via ESC removes the file and we are forced to record it again.

**Describe the solution you'd like**
When taking a screenshot in macOS, the preview modal is shown, cancelling that drag will always save the image to desktop.
It would be nice to have an option in preferences to always save the `mp4` and/or the `gif` to your export location.

**Describe alternatives you've considered**
Always selecting the `mp4` option and saving will give us the best quality, but that means we will need to manually find a tool to convert the `mp4` to `gif` for sharing purposes.

**Comment by AvdLee** [comment]
This is great input. I'll try to make the best out of this!

**Comment by AvdLee** [comment]
Started to make progress on this one, added a close button:

![image](https://user-images.githubusercontent.com/4329185/88464902-bd1b1c00-cebe-11ea-946b-322f4b8a22e3.png)

The next steps are to make the thumbnail never appear automatically. That way you can take as many actions and exports as you want.

**Comment by AvdLee** [comment]
Alright, this is what I've done:

- The thumbnail closes upon pressing one of the action buttons
- Dragging can be canceled with ESC while the floating thumbnail stays visible
- You can drag as many times as you want
