### ISSUE TITLE
RocketSim Pro

### ISSUE THREAD

**Issue by TheAbstractDev** [AvdLee/RocketSimApp#431]
Hi !

First of all, thanks for this tool, it's really the best simulator add-on.

I just wanted to ask you if you can bring RocketSim to Setapp ?

It's a great alternative to the App Store and for people who already have a subscription it can be awesome.

Thanks

**Comment by AvdLee** [comment]
Duplicate of #425. Unfortunately, there are no plans for bringing this app to Setapp.

**Comment by TheAbstractDev** [comment]
Oh .. why so ?

**Comment by AvdLee** [comment]
My biggest reason is that I don't want to maintain two App Stores. Secondly, friends have tried it out and found it not worth the investment in terms of returns. Since RocketSim is a side project, I have to pick my battles 🙏
