### ISSUE TITLE
Selection Xcode failed, unknown simulator

### ISSUE THREAD

**Issue by bilousoleksandr** [AvdLee/RocketSimApp#436]
**Describe the bug**
Bought a paid version to try screenshots utility and I can do nothing with it. Nor simulator nor Xcode is found by RocketSim, which makes application not usable. 

`code-select -p
/Applications/Xcode_15.0.1.app/Contents/Developer
`

**To Reproduce**
Install and launch 

Error on launch and app is not usable 

**Expected behavior**

**Screenshots**
<img width="372" alt="Screenshot 2023-11-15 at 16 45 03" src="https://github.com/AvdLee/RocketSimApp/assets/62213789/a24de9fb-44d3-40ea-beaa-26ba93b829b0">

**Desktop (please complete the following information):**
macOS 14.0 (23A344)
Xcode 15.0.1  
x86_64 arch 

**Additional context**

**Comment by AvdLee** [comment]
Hi @bilousoleksandr! I assume you've selected the same Xcode path via the open panel, is that correct? Would you mind sharing a diagnostics report via Settings -> About -> Report an issue?

Also, could you share a picture of your Simulator? I want to know the name of the Simulator to ensure RocketSim is able to detect it correctly.

**Comment by AvdLee** [comment]
Thanks @bilousoleksandr, yes, you make great points! I'll definitely add it to the status bar menu, and I'm also going to add a troubleshoot page for the unknown simulator alert 👌 

- [ ] Add troubleshoot documentation page
- [ ] Link unknown simulator alert to troubleshoot page
- [ ] Add Report an issue to status bar menu
- [ ] Improve copy in unknown simulator alert to describe most common issues

**Comment by AvdLee** [comment]
@bilousoleksandr I don't see any email so far 🤔

**Comment by AvdLee** [comment]
I've improved the copy and added the menu item in 12.2.0 🚀 
Closing for now, while waiting for the email
