### ISSUE TITLE
Video timer visible after recording stopped

### ISSUE THREAD

**Issue by peagasilva** [AvdLee/RocketSimApp#437]
**Describe the bug**
After stopping recording a video, part of the timer is still visible in the RocketSim menu bar item.

**To Reproduce**

Make sure you have a deeplink registered.

1. Run your app
2. Put you app in background
3. Go to the Captures tab and start recording a video
4. Go to the App Groups tab and click on the deeplink
5. Go back to the Captures tab and stop the recording
6. See that part of the video timer is still visible in the menu bar icon

**Expected behavior**
After finishing recording the video, the menu bar icon should not display the video timer (partially or completely).

**Screenshots**

https://github.com/AvdLee/RocketSimApp/assets/5387088/53af0a2c-1456-4c30-a0a1-7ebb6e9056d5

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version: 14.1.1

**Comment by AvdLee** [comment]
Also reported by Rob

**Comment by AvdLee** [comment]
Will be fixed in 12.7.0!
