### ISSUE TITLE
Shortcut to export location 📂

### ISSUE THREAD

**Issue by atrinh0** [AvdLee/RocketSimApp#44]
**Is your feature request related to a problem? Please describe.**
To quickly jump to the exported files, we need to either save a new recording, or manually browse through finder to find the export location.

**Describe the solution you'd like**
Ideally a shortcut to open finder to our exported location would be nice.
Similar to Xcode perhaps. 

![open finder](https://user-images.githubusercontent.com/16542463/88389477-7f2ed280-cdae-11ea-9973-9e7b9c8bcce2.png)

Or maybe via the main menu?

![Screenshot 2020-07-24 at 13 10 39](https://user-images.githubusercontent.com/16542463/88389817-1eec6080-cdaf-11ea-8d02-2c588c9e9eea.png)

**Comment by AvdLee** [comment]
Sounds like a quick win!

**Comment by AvdLee** [comment]
Done, added the shortcut arrow!

![image](https://user-images.githubusercontent.com/4329185/88464680-066a6c00-cebd-11ea-923d-a11cdaeb4fea.png)
