### ISSUE TITLE
More easy fine tune of zoom and offset

### ISSUE THREAD

**Issue by carlosypunto** [AvdLee/RocketSimApp#440]
The #380 fix mproved accuracy, but it is not entirely convenient to change small values. I propose the addition of a couple of buttons to increase and decrease values in increments and decrements of 1.

![request](https://github.com/AvdLee/RocketSimApp/assets/1680094/7084977d-7ee7-42ad-90cf-976d8220721d)

**Comment by casperriboe** [comment]
In addition to this I would also really love to be able to adjust the offset with the arrow keys. So when the text field has focus, pressing the up or down arrows will increase or decrease the amount (same for zoom which doesn't yet a text field). If possible change the amount by 10 when `shift` is held, like in other programs such as Figma, Sketch and Photoshop 👍🏻

**Comment by AvdLee** [comment]
@casperriboe I was actually working on that already. Planned for Q1!

**Comment by AvdLee** [comment]
@carlosypunto I decided to focus on key presses only, not adding the arrows. Let me know if that's enough for you too! It works as follows:



https://github.com/AvdLee/RocketSimApp/assets/4329185/20f06bf0-c057-4475-97fa-248746b2b32f

@casperriboe the `shift` flag option is added too.

Will be released with `12.5.0`

**Comment by casperriboe** [comment]
Awesome! Thanks @AvdLee 🎉

**Comment by carlosypunto** [comment]
Is fine for me, thanks @AvdLee 😃
