### ISSUE TITLE
Rulers distance is hidden behind simulator rounded bezels

### ISSUE THREAD

**Issue by efstathiosntonas** [AvdLee/RocketSimApp#445]
**Describe the bug**
When applying a ruler and tapping Shift key to see the distance, the red box is hidden behind the curved bezel of the simulator. See attached screenshot and notice the red box including the distance, the simulator is iPhone 15 Pro Max 17.2 but it happens in all simulators.

I use RocketSim `12.4.0 (191)`

**To Reproduce**
1. Create a ruler next to the edge, vertical or horizontal
2. The red box is hidden behind bezels

**Expected behavior**
I think the red box should be moved higher or to the left/right when it's near the simulator edges.

**Screenshots**
![Screenshot 2023-12-14 at 10 25 38](https://github.com/AvdLee/RocketSimApp/assets/717975/b5bb3627-d36f-4db9-8a01-bdfddb1965cf)

**Desktop (please complete the following information):**
 - OS: Sonoma 
 - Version: 14.2

**Comment by AvdLee** [comment]
Thanks for reporting in, clear issue! 👍

**Comment by efstathiosntonas** [comment]
Hi @AvdLee, can you please update about this issue? Thanks!

**Comment by AvdLee** [comment]
@efstathiosntonas yes! It's planned for this quarter. I'm focusing on SwiftLee Weekly first, followed by UX improvements for RocketSim. Stay tuned 🙏

**Comment by AvdLee** [comment]
Decided to give it a try and managed to fix it quite fast! Coming in 12.4.2:


![Image](https://github.com/AvdLee/RocketSimApp/assets/4329185/4696bbe5-d4d7-486c-893a-ab818d75718e)

**Comment by efstathiosntonas** [comment]
I knew it was a quick fix haha! thanks, it was a really annoying back and slowed me down trying to figure out the px with the Free Ruler app.

**Comment by AvdLee** [comment]
@efstathiosntonas glad to hear! Let me know if it actually fixed your journey and if you have any further tips on improvements. Would love to optimize it based on actual user feedback!

**Comment by efstathiosntonas** [comment]
It definitely fixed it 👍 

This might be impossibru but it would be nice if we were able to remove specific ruler lines. Imaging placing 20 rulers eg. for calculating item sizes for a shimmer loading screen and one horizontal ruler line is accidentally placed wrong, we would have to remove all horizontal rules and start over!

**Comment by AvdLee** [comment]
You can remove specific rulers already! Just pick a specific ruler and move it out of the screen 👌
