### ISSUE TITLE
Show also non recent builds

### ISSUE THREAD

**Issue by matteomonizza** [AvdLee/RocketSimApp#447]
I used the SimPholders app to show simulators folders. In this app I can see all the builds, not only recent ones.
See the attahcments.

<img width="616" alt="Screenshot 2023-12-19 alle 16 00 55" src="https://github.com/AvdLee/RocketSimApp/assets/3415640/89530edd-e780-4733-849e-5df1097d4889">

**Comment by AvdLee** [comment]
@matteomonizza do I understand correctly you want the list of recent builds to not be capped to 4 recent builds, but show all builds?

**Comment by matteomonizza** [comment]
Yes, show all the simulators and for each one show the builds.

**Comment by AvdLee** [comment]
This is not going to be in line with how RocketSim works. It currently shows your 3 recent builds, no matter which Simulator. We believe this covers most of the use cases since you're likely working with either of those 3 recent builds either way. 

Hope that's okay!
