### ISSUE TITLE
Reset settings to default

### ISSUE THREAD

**Issue by shahzadmajeed** [AvdLee/RocketSimApp#448]
Hi, 

Proud to be a pro subscriber. Could you please add `Reset Settings To Default` feature if possible?

Thank you!

**Comment by AvdLee** [comment]
@shahzadmajeed thank you so much for supporting by being a Pro subscriber! 

Regarding your request: which settings do you want to reset?

**Comment by shahzadmajeed** [comment]
In general, everything back to default like a fresh install.

My main problem was that safari pop up that is bugging me every minute or so. I thought I might have configured some setting wrong (like some deeplink). I can try to find that bug report from issues tab

**Comment by shahzadmajeed** [comment]
I think I might have submitted that error in feedback to Apple but I can try to capture a screenshot today. 

It could be unrelated but started happening since installed RocketSim
