### ISSUE TITLE
Menu consistency with Apple guidelines 👨🏻‍🏫

### ISSUE THREAD

**Issue by atrinh0** [AvdLee/RocketSimApp#45]
https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/

*Use title-style capitalization*
*Use an ellipsis whenever choosing a menu item requires additional input from the user.*

| Current | Suggested |
| --- | --- |
| Run from clipboard | Run from Clipboard |
| No deeplinks configured | No Deeplinks Configured |
| Start recording | Start Recording (and show shortcut if one exists, if possible) |
| Preferences | Preferences... |
| Quit | Quit |

**Comment by AvdLee** [comment]
Wow, this is quality feedback!! I'm really impressed and highly motivated to implement your requests. Thanks a ton!

**Comment by AvdLee** [comment]
Done! Will be included in the next release
