### ISSUE TITLE
Light mode does not look good for Push notification editor

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#453]
See: 
![CleanShot 2024-01-19 at 10 36 08@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/93ef6855-5553-49a9-98a1-c9fd6463b5c3)

Reported by Christoph on X

**Comment by AvdLee** [comment]
Closed since it looks good already now!

**Comment by ldrr** [comment]
Still not good with latest version from 12.7.1 (202)
![image](https://github.com/AvdLee/RocketSimApp/assets/580463/69a95fcb-8171-4052-b284-8e67d704ba72)
Or is it supposed to have a black background?

**Comment by ldrr** [comment]
Still not good with latest version 12.7.1 (202) (unless it's supposed to have a black background)
![image](https://github.com/AvdLee/RocketSimApp/assets/580463/9c19f839-e1a0-4af8-a93e-39196a1d0ada)

**Comment by AvdLee** [comment]
@ldrr ah, yes, it's supposed to have a black background. I guess I could update it to a whiter background, but this is personal preference 🙈

**Comment by ldrr** [comment]
Super low priority but honestly it looks broken. But just my 2 cents, feel free to ignore it :D
