### ISSUE TITLE
Rename Groups

### ISSUE THREAD

**Issue by Isaccobosio** [AvdLee/RocketSimApp#454]
**Is your feature request related to a problem? Please describe.**
When you create a Group inside the "App Actions" tabs you can't rename it.

**Describe the solution you'd like**
It'd be cool to double click (or right click as for the delete action) and rename it.

**Additional context**
<img width="772" alt="image" src="https://github.com/AvdLee/RocketSimApp/assets/26121430/2472d178-e60b-4808-86a6-e4003eba68b0">

**Comment by AvdLee** [comment]
@Isaccobosio you should be able to rename the group by just doing a one click:
![CleanShot 2024-01-25 at 15 11 05@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/3726c56f-f8a7-42b5-ab16-529001e44349)
