### ISSUE TITLE
Idea: Screenshots in multiple languages 

### ISSUE THREAD

**Issue by coderExMachina** [AvdLee/RocketSimApp#455]
What would save quite some time when localizing my App Store page, would be if I could set a list of languages that I want a screenshot for - then when taking the screenshot, the simulator would iterate over the languages and take screenshots respectively.

**Comment by AvdLee** [comment]
Yeah... that would be amazing! Unfortunately, this is impossible for me to build. I can't change the language without restarting the app, which would require navigating to the correct page etc. 

Thanks for sharing the idea though!!
