### ISSUE TITLE
Incorrect simulator recording

### ISSUE THREAD

**Issue by peagasilva** [AvdLee/RocketSimApp#466]
**Describe the bug**
While working with two simulators (both were iPhone 15 Pro, one on iOS 17.2, the other on iOS 17.0), I recorded one video in one of the simulators, but RocketSim recorded the screen from the other simulator. On top of that, closing one of the simulators make the video and gif recording stop working.

**To Reproduce**
1. Open two simulators with the same device name, with different iOS versions (e.g. iOS 17.0 and 17.2)
2. In the iOS 17.0 simulator, start recording a video and interact with the simulator
3. When the recording has finished, click on the scissor icon in the recording thumbnail in the bottom right corner
4. See that the video is incorrect

**Expected behavior**
RocketSim should record the correct simulator, even if two simulators for the same device are open.

**Screenshots**
Sorry for the low quality video, that was the only possible way below 10MB 😬 

<video height=200 src="https://github.com/AvdLee/RocketSimApp/assets/5387088/5c10e03d-5745-4285-af0d-9a8c7fe81992" /><br>

#### After closing one of the simulators (the one with iOS 17.2)

<video height=200 src="https://github.com/AvdLee/RocketSimApp/assets/5387088/45913efb-7fa1-4a7c-bce9-abb05d31622a" />

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version: 14.2.1 (23C71)

**Comment by AvdLee** [comment]
Thanks, this should indeed be fixed!

**Comment by AvdLee** [comment]
Alright, the tricky part here is that I get back window info, but both windows have the same title: "iPhone 15 Pro" and "iPhone 15 Pro".

I'll have to dig a bit deeper to see if I can somehow find out which OS versions are used for each window. T.b.c.

**Comment by AvdLee** [comment]
This will be fixed in 12.6.6!
