### ISSUE TITLE
Record Mac audio along with simulator video recording

### ISSUE THREAD

**Issue by art-divin** [AvdLee/RocketSimApp#469]
**Is your feature request related to a problem? Please describe.**
When I start recording video in RocketSim app
And I use Accessibility Inspector to inspect the app in Simulator for accessibility labels
I expect the resulting video recording to include audio of the VoiceOver from accessibility inspector

**Describe the solution you'd like**
- audio of the VoiceOver from accessibility inspector is included into the final video recording

**Describe alternatives you've considered**
- built-in screen recording on macOS also does not support this out of the box, but can record macOS audio using alternative tools

**Additional context**
N/A

**Comment by AvdLee** [comment]
This will be fixed with https://github.com/AvdLee/RocketSimApp/issues/340, so closing as a duplicate
