### ISSUE TITLE
Request for Simulated Jailbreak Environment Feature

### ISSUE THREAD

**Issue by Muhammadbarznji** [AvdLee/RocketSimApp#471]
I am proposing the addition of a feature to simulate a jailbroken environment within the app for testing purposes during development. This would enable developers to test and validate the app's behavior under simulated jailbreak conditions without the need for an actual jailbroken device.

**Comment by AvdLee** [comment]
@Muhammadbarznji that's a great idea! However, I'm quite unfamiliar with jailbroken devices. Do you have any advice on how we can simulate this?

**Comment by Muhammadbarznji** [comment]
@AvdLee thank you for your response. I currently do not have a jailbroken device, although I had one in the past on real devices. Unfortunately, I am not familiar with the process of jailbreaking on the simulator. I am actively searching for information, and if I come across any relevant details, I will be sure to notify you.

**Comment by AvdLee** [comment]
I decided to close this issue. Jailbreaks are different for every OS version and really complicated to replicate for the Simulator either way. Out of scope, unfortunately.
