### ISSUE TITLE
More information of the simulator

### ISSUE THREAD

**Issue by matteomonizza** [AvdLee/RocketSimApp#478]
When I run an app on multiple simulator devices but on different SDKs, I cannot recognize wich I'm selecting from the app. 

Show also the iOS Version

<img width="438" alt="Screenshot 2024-03-09 alle 17 57 42" src="https://github.com/AvdLee/RocketSimApp/assets/3415640/fb4eed4a-415c-4207-a13e-f136c997f707">

**Comment by AvdLee** [comment]
Good call! I'll see what I can do 🙏

**Comment by AvdLee** [comment]
This will be fixed in 12.8.0:

<img width="282" alt="CleanShot 2024-03-26 at 15 26 28@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/578be6b0-fcd5-47f7-a6bf-74836ff50085">

**Comment by matteomonizza** [comment]
Thank you very much
