### ISSUE TITLE
GIF doesnt save the entire duration

### ISSUE THREAD

**Issue by chriisong** [AvdLee/RocketSimApp#48]
**Describe the bug**
Saving as GIF (haven't tried  MP4) does not save the entirety of the recording.

**To Reproduce**
1. Record
2. Save as GIF
3. Watch the recording

**Expected behavior**
GIF file should play the entirety of the recorded duration

**Screenshots**
[Youtube video, recording of the error](https://youtu.be/4S4oAE3zuEk)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Version 2.2.1

**Additional context**
I was able to successfully record longer gifs and file sizes were greater than 8MB. But Now, no matter how long the video is, it will never exceed 7.9MB.

I've tried restarting the macbook, quitting and restarting RocketSim, changing folder location.

**Comment by AvdLee** [comment]
@chriisong I absolutely love how you're reporting this issue, this is super useful. I'm currently working hard on the export logic of both the recordings and GIFs which will hopefully, automatically, solve this issue too. I don't have an exact timeline but do know I'm making progress every week!

I'll keep you posted in this issue. Thanks again!

**Comment by AvdLee** [comment]
This should be fixed with 3.0, available later this month. If not by then, feel free to reopen and I'll dive deeper into this.
