### ISSUE TITLE
Can't choose XCode from user Dir

### ISSUE THREAD

**Issue by yahu1031** [AvdLee/RocketSimApp#482]
**Describe the bug**
I'm trying to install the app and choosing Xcode from the user's directory. And I get, 
```
It looks like you didn't select Xcode. Your Xcode can't live inside your user directory for RocketSim to work. 
```

**To Reproduce**
1. Install App
2. Choose XCode which is installed in user specific Directory.

**Expected behavior**
It should choose it ideally. Not sure if there are any restrictions with it.

**Screenshots**

https://github.com/AvdLee/RocketSimApp/assets/35523357/1e946a5d-203c-4b32-9a91-66e1c8274fcb

**Desktop (please complete the following information):**
![Screenshot 2024-03-21 at 11 13 13 AM](https://github.com/AvdLee/RocketSimApp/assets/35523357/150d317d-9b65-4bcf-83fe-d20db0aed3b0)

**Comment by AvdLee** [comment]
@yahu1031 this is fixed in 12.7.1. If not, feel free to reopen or reach out via Settings -> About -> Report an issue so I'll also have debugging logs to work with 🙏

**Comment by yahu1031** [comment]
This was recorded in 12.7.1 itself. @AvdLee

**Comment by yahu1031** [comment]
Even persists in 12.8.0(203).

**Comment by AvdLee** [comment]
Ah, I mixed two issues. This one indeed isn't fixed an the error message actually applies:

> It looks like you didn't select Xcode. Your Xcode can't live inside your user directory for RocketSim to work. 

Since RocketSim is sandboxed, it isn't able to work with an Xcode installation inside the user directory. I can't do much about it, unfortunately.

You'll have to make sure Xcode is installed at e.g.:

```
/Applications/Xcode-15.3.0.app
```
