### ISSUE TITLE
Add option to trash video.

### ISSUE THREAD

**Issue by ajmccall** [AvdLee/RocketSimApp#49]
**Is your feature request related to a problem? Please describe.**
I often find that I do not need to Save or Copy the simulator's recording once it has finished. 

A common scenario is when using RocketSim to record ui tests. As UI tests are long and tedious, I record the tests to play back _if_ they fail. Often they don't fail, or the failure is obvious. In this case I usually Save the video and then immediately delete it after it's saved. 

What I _actually_ want to do is, trash that recording and remove the Save/Copy window the appears in the bottom left corner of the desktop.

![image](https://user-images.githubusercontent.com/939454/92041483-3e908480-ed70-11ea-831c-74ec7de64b8a.png)

**Describe the solution you'd like**

After the simulator recording is finished, in addition to Copy and Save options, a Trash/Ignore option could be available.  Choosing this option would remove any temporary files and/or in memory objects stored during that recording. The Copy/Save window would dissappear.

**Describe alternatives you've considered**
- Ignoring the Copy / Save window in the bottom right corner of the screen.
- Choose Copy, but then never using the in-memory copy.
- Choose Save, then immediately delete the file

**Additional context**
Thanks for the app

**Comment by AvdLee** [comment]
Thanks for reporting in @ajmccall. I happy to tell that I've got this implemented already and scheduled for the next release! Therefore, closing this one 💪

**Comment by ajmccall** [comment]
Amazing!
