### ISSUE TITLE
Start recording blocks the UI if the previous record was not saved

### ISSUE THREAD

**Issue by djavan-bertrand** [AvdLee/RocketSimApp#50]
**Describe the bug**
If we start a record while the former record was not saved or discarded (i.e. the small preview with the gif or mp4 save options is still displayed), when we stop the record, there is no way to save this new record (i.e. the small preview is displayed but hovering with the mouse does not show any save option) and the preview is blocked there with no way to discard it.

**To Reproduce**
1. Start recording
2. Stop recording
=> small preview is displayed as intended. Hovering it shows save options (gif/mp4, copy/save).
3. Start recording
4. Stop recording
=> New small preview is displayed as intended. However, when hovering it with the mouse, no save options are displayed and there is no way to hide the preview. The only way to get back to a correct state is to quit the app and relaunch it.

**Expected behavior**
The old preview should disappear, replaced by the new one, fully fonctional.

**Screenshots**
<img width="249" alt="Screenshot 2020-09-04 at 11 37 12" src="https://user-images.githubusercontent.com/630339/92226709-72b99180-eea5-11ea-9aea-746bf6a95c28.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6 (19G2021)
 - App Version: 2.2.1 (31)

**Comment by AvdLee** [comment]
@djavan-bertrand thanks for reporting in. I can confirm this is fixed in the next big release. It's a bigger release that will take a few weeks to arrive but I promise you it's worth it!

**Comment by djavan-bertrand** [comment]
Thanks for the quick answer. No worries, this was not a blocking bug, i'll wait for the next release.
Thanks a lot for all your work !
