### ISSUE TITLE
Clear SPM Cache

### ISSUE THREAD

**Issue by blastum** [AvdLee/RocketSimApp#500]
**Is your feature request related to a problem? Please describe.**
"Hear me out, bro..." But seriously, debugging Swift Package problems can be a pain. A shortcut to clear out the SPM cache would be occasionally useful, in the same way as is deleting Derived Data.

**Describe the solution you'd like**
trash ~/Library/Cachesorg.swift.swiftpm

**Describe alternatives you've considered**
I do it manually as needed

**Additional context**
Have a nice day

**Comment by AvdLee** [comment]
I did not know that existed! I'll definitely consider adding that, however, I've never had a situation where I needed this. Can you explain when you're using this and why File -> SPM -> Reset Package Caches for your project doesn't work?

**Comment by AvdLee** [comment]
Closing this as this is out of scope for the Simulator.
