### ISSUE TITLE
Properly report unsupported Apple TV devices

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#501]
Users are now stuck at:

<img width="372" alt="???? 린샷 2024-04-22 오후 7 41 31" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/5324a7d0-1250-4c6a-a7e2-a05aa9013780">

Reported by 진재명

**Comment by AvdLee** [comment]
Will be fixed in 12.9.1

**Comment by jaemyeong** [comment]
Thanks :)
