### ISSUE TITLE
Allow the user to order their deep links.

### ISSUE THREAD

**Issue by TheEffekted** [AvdLee/RocketSimApp#51]
**Is your feature request related to a problem? Please describe.**
As far as I'm aware, you are unable to order your deep links in a group. If you have dozens of deep links and want to add another, it has to be put at the bottom of the group. This is problematic if you want to put similar deep links next to each other, like a subcategory and category deep links, but your ordering has already been set.

I've tried changing the order of the deep links in the linked JSON file, but that doesn't seem to control the ordering?

**Describe the solution you'd like**
Make the deep links orderable. Perhaps a drag and drop.

**Describe alternatives you've considered**
I don't think there are any alternatives.

**Additional context**
My app has nearly 100 deep links across different environments(staging, prod), and having better tools to organize them would be appreciated!

**Comment by AvdLee** [comment]
I've got good news, this is working in a local version of mine and was fixed with #37!

Currently, I'm working on a big 3.0 update. Downside is that it takes a bit longer for it to arrive but it will contain many great features.
