### ISSUE TITLE
Crash when stopping recording 🥺

### ISSUE THREAD

**Issue by atrinh0** [AvdLee/RocketSimApp#52]
**Describe the bug**
App crashes when stopping a recording. Started happening on the latest Big Sur beta. Earlier betas were ok.

**To Reproduce**
1. Start recording with the simulator open
2. Stop the recording (either by shortcut, or the menu icon to stop)

**Expected behavior**
Historically, the bottom right modal appears, now the app disappears from the top menu bar and the process has ended.

**Screenshots**
![Screen Shot 2020-10-03 at 5 45 14 pm](https://user-images.githubusercontent.com/16542463/94997585-0b762680-05a4-11eb-8101-b04098316bae.png)

**Desktop (please complete the following information):**
 - OS: 11.0 Beta (20A5384c)
 - RocketSim Version 2.2.1 (31)

**Additional context**

I have captured logs from console:
[console-export.txt](https://github.com/AvdLee/RocketSimApp/files/5322038/console-export.txt)

Also attaching some crash logs:
[Crash logs.zip](https://github.com/AvdLee/RocketSimApp/files/5322039/Crash.logs.zip)

**Comment by atrinh0** [comment]
Additional info:
- I have restarted
- I have cleared the simulator, and tried other simulators 
- I have cleared the contents of the export location
- I have explicitly selected Xcode
(all the above have not resolved the issue)

RocketSim still works on my work laptop running Catalina.

**Comment by AvdLee** [comment]
@atrinh0 thanks for reporting in with great details. Big Sur support is coming as soon as possible!

**Comment by AvdLee** [comment]
I've tested out on Big Sur and found no serious issues. I did find weird cases when Xcode was not located in the Applications folder. Is that true in your case?

**Comment by atrinh0** [comment]
> I've tested out on Big Sur and found no serious issues. I did find weird cases when Xcode was not located in the Applications folder. Is that true in your case?

My Xcode is located at: `/Applications/Xcode.app`

**Comment by AvdLee** [comment]
@atrinh0 can you upgrade to 3.0.0 and see if this still occurs?

**Comment by atrinh0** [comment]
Confirmed to be fixed in 3.0.1 👍🏻
