### ISSUE TITLE
Shortcut button for actions like Relaunch With Locale

### ISSUE THREAD

**Issue by benadamdev** [AvdLee/RocketSimApp#526]
It would be awesome if I can create a custom button which triggers an action buried in some submenu. For example, assigning "Perform -> Relaunch With Locale -> Simplified Chinese" to custom button. Thank you Antoine.

**Comment by AvdLee** [comment]
@benadamdev I'm restructuring the `perform` button to move all these actions into individual actions in the side window. Hopefully, that will solve your issue! Stay tuned

**Comment by benadamdev** [comment]
It definitely will. Thank you Antoine.

**Comment by uevs** [comment]
> I'm restructuring the perform button to move all these actions into individual actions in the side window. Hopefully, that will solve your issue! Stay tuned

Great news, I came here looking for this! I would love to have the same also for `uninstall` as I use it a lot when testing onboarding flows, nice to know that it's being worked on

**Comment by AvdLee** [comment]
Update on this: I worked on my going-indie.com course for the past 8 weeks and I've planned the whole Q4 quarter for RocketSim updates, including this one. It took a bit longer, but it's still on my list!

**Comment by benadamdev** [comment]
That is awesome Antoine. Thank you vey much.

**Comment by AvdLee** [comment]
@uevs @benadamdev this will be available in RocketSim 13.0, launching in January:

<img width="898" alt="CleanShot 2024-12-13 at 13 49 57@2x" src="https://github.com/user-attachments/assets/5e7df875-2c1b-4afc-a82b-f5a29a2c4308" />

You can see the relaunch with locale in action here: https://x.com/twannl/status/1867545086252527760

**Comment by uevs** [comment]
Amazing, thanks!
