### ISSUE TITLE
Favour #if targetEnvironment(simulator) over #if DEBUG

### ISSUE THREAD

**Issue by houtzager** [AvdLee/RocketSimApp#537]
Hi Antoine,

Is there a reason the code from the "Copy code" button of the Rocketsim Connect feature, contains an `#if DEBUG` instead of `#if targetEnvironment(simulator)`? Debug builds on real devices should and can never access the Rocketsim.app right?

Cheers!

**Comment by AvdLee** [comment]
@houtzager there is! I'm planning to add support for iPhone Mirroring, including RocketSim Connect functionality. Therefore, I want the code example to be prepared for such 🙂
