### ISSUE TITLE
Simulator get's crashing when enabled network monitoring

### ISSUE THREAD

**Issue by Sangsom** [AvdLee/RocketSimApp#540]
**Describe the bug**
Sometimes while using simulator with enabled Network Monitoring I get the following fatal error:
Thread 9: Fatal error: Could not get data from _swizzleURLSessionDataTaskDidReceiveData. It might causes due to the latest iOS changes. Please contact the author!

**To Reproduce**
Unfortunately I'm not able to reproduce it on demand, sometimes it crashes on simulator launch, sometimes can work for a long time and crash.

**Expected behavior**
Not crashing

**Screenshots**
<img width="1090" alt="image" src="https://github.com/AvdLee/RocketSimApp/assets/3636976/726bd9aa-650a-49cb-a56d-60d49c702045">

**Desktop (please complete the following information):**
 - OS: iOS Simulator
 - Version: 17.5
 - Xcode 15.4

**Comment by AvdLee** [comment]
This is fixed in version 12.11.2!
