### ISSUE TITLE
Objective-C support?

### ISSUE THREAD

**Issue by cannyboy** [AvdLee/RocketSimApp#555]
Can Rocket Sim be used in an Objective-C app? Or an app which is part-Swift, part-ObjC?

**Comment by cannyboy** [comment]
Thanks, do you recommend any particular way if integrating into an Objective-C? I mean, is there an Objective-C version of the AppDelegate integration mentioned here: https://docs.rocketsim.app/features/hzQMSrSga7BGWvxdNVdwYs/introduction/iXHZvJWvedgZuVTN5V3YS1

**Comment by AvdLee** [comment]
I'd recommend using the breakpoint if possible!
