### ISSUE TITLE
Order "Relaunch with Locale" options

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#557]
> I’d like to have the “Relaunch with Locale” option show items in a more logical order. They appear to be “randomly" presented, but I feel that it might be better to have them in an alphabetical order. Hope you can fix that! Looking forward to hearing from you!

Requested by B. Kolkman

**Comment by lindboe** [comment]
+1 to this! It's a (hopefully small?) change that would be big for quality of life.

**Comment by AvdLee** [comment]
This will be fixed in 12.11.14!
