### ISSUE TITLE
Select Simulator

### ISSUE THREAD

**Issue by piercifani** [AvdLee/RocketSimApp#56]
**Is your feature request related to a problem? Please describe.**
When I have more than one simulator open at a time (for example iPhone and iPad), I'd like to select which one is recorded.

**Describe the solution you'd like**
When more than one simulator window is open, the "Start Recording" option should have a submenu where you can select from which simulator.

**Describe alternatives you've considered**
I have to close all the other simulators before I can record the desired one.

**Additional context**
None

**Comment by AvdLee** [comment]
@piercifani thanks for reaching out! The simulator is selected by picking the front-most. Just make sure to have the simulator you want to be recorded in front and all should be fine.

Do note that you can improve this functionality from the preferences window:
![image](https://user-images.githubusercontent.com/4329185/96846221-e6adfa00-1451-11eb-9805-50a10822d0bb.png)

I'm not planning to built-in a selection popup as I'm convinced that the current working is a better user experience. Let me know if that worked!

**Comment by piercifani** [comment]
It doesn't work for me, it always picks up the iPhone instead of the iPad simulator, no matter which one is the front-most window, even minimising the iPhone sim doesn't do the trick

**Comment by AvdLee** [comment]
@piercifani it might be a bug in this case.

- Which iPhone do you have open?
- Which iPad do you have open?
- Do you have the Improved active simulator detection enabled?

**Comment by piercifani** [comment]
> Which iPhone do you have open?

iPhone 11 Pro

> Which iPad do you have open?

iPad Pro 11 2nd Gen

> Do you have the Improved active simulator detection enabled?

Yep (actually, can you even turn [it off](https://user-images.githubusercontent.com/869981/96880603-a6647100-147d-11eb-83e9-a302b0b1dad7.png)?

**Comment by AvdLee** [comment]
Reproduced this locally, working on a fix for the next update.

**Comment by AvdLee** [comment]
Fixed in the next release!
