### ISSUE TITLE
Plist item selection and updating

### ISSUE THREAD

**Issue by joshuabryson** [AvdLee/RocketSimApp#566]
**Is your feature request related to a problem? Please describe.**
It would be great if you could `select` an item in a plist. Just highlighting the row would be enough. The lack of user feedback was a little disorienting until I realized what was happening. Additionally, when you delete an item it doesn't remove it from the list so one doesn't know if it has happened or not.

**Describe the solution you'd like**
1. Row highlight on selection. 
2. When an item is deleted, the list would update (remove the item). 

**Describe alternatives you've considered**
1. Highlight the selection, possible also show the options for the given type.
2. You could mark it red or something. Anything that gives the user an idea that a successful action occurred.

**Comment by AvdLee** [comment]
Absolutely great points. Adding it to the roadmap!
