### ISSUE TITLE
Turn off the watermark as soon as one becomes Pro

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#569]
To prevent users from creating many screenshots only realizing later the watermark is still visible.

**Comment by xu-chris** [comment]
I have bought a yearly subscription after launch. So no simulator was running, just opening the app and closed the deal. After that, I have made couple of screenshots with the simulator and just saw that they all had the watermark on it. 

Mac OS 15.0 beta, Xcode 16 beta, iOS 18 on iPhone 15 simulator.

Hope this helps!

**Comment by AvdLee** [comment]
This will be fixed in the next release
