### ISSUE TITLE
Update Airplane Mode instructions for Sequoia

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#575]
- [x] Update documentation
- [ ] Update in-app instructions
- [ ] Fix copy in-app:
![image](https://github.com/user-attachments/assets/381315c7-b8f6-4d03-a1eb-d19f5cd7ef9e)

![image](https://github.com/user-attachments/assets/a89c0120-941b-4c7c-9bba-df2738a3d1c8)

https://obsproject.com/forum/threads/macos-15-sequoia-beta-system-extensions-settings-moved.176958/

**Comment by JuanRdBO** [comment]
Happened to me too while trying to start the airplane mode. I had to go to general => extensions => network activity and click on the "i".

**Comment by AvdLee** [comment]
This was useful: https://gist.github.com/rmcdongit/f66ff91e0dad78d4d6346a75ded4b751

Fixed in 12.12.0:

![Image](https://github.com/user-attachments/assets/15d8e3a3-03ec-4944-bed6-e41912416583)

Deeplinking into:

![Image](https://github.com/user-attachments/assets/9ce115fb-68e0-4fbd-9d62-3333a1685a38)

I've also [updated the documentation](https://docs.rocketsim.app/features/hzQMSrSga7BGWvxdNVdwYs/simulator-airplane-mode/pRVTC5ok6nHCUnkmNnxV11).
