### ISSUE TITLE
AirPlane mode disables network for the whole computer on Sequoia 15.1beta

### ISSUE THREAD

**Issue by tgrapperon** [AvdLee/RocketSimApp#578]
**Describe the bug**
I'm giving RocketSim a spin, and I'm checking the AirPlane mode toggle. I installed the network extension properly I guess. When I toggle the AirPlane mode, the network goes away, but so does the whole computer network access! Furthermore, it doesn't come back after switching the toggle off. I had to disable the extension and restart the connection to regain network access.

**To Reproduce**
1. Toggle the AirPlane mode on Sequoia 15.1beta
2. The network goes away for the whole computer
3. Toggle the AirPlane mode off
4. The network doesn't come back

**Expected behavior**
Toggling on/off should toggle network on/off for the simulator only.

**Desktop (please complete the following information):**
 - OS: 15.1 Beta (24B5035e)
 - Version: 12.11.7 (235)

**Comment by AvdLee** [comment]
@tgrapperon thanks a lot for letting me know. I'm considering moving away from system extensions completely and use RocketSim Connect instead.

Just to get an idea: are you using RocketSim Connect for inspecting network traffic already?

**Comment by tgrapperon** [comment]
@AvdLee I've checked how it would work, but it was not really relevant to our case, as most of the exchanges are happening through a WebSocket connection that I believe pulse doesn't support. 
How is RocketSim Connect working? Is it affecting NWConnection too?

**Comment by AvdLee** [comment]
@tgrapperon I've been trying to reproduce this without luck. I'm going to close this ticket for now and will keep an eye on this when the non-beta release is there. Keep me posted!
