### ISSUE TITLE
Launch Arguments

### ISSUE THREAD

**Issue by joshuabryson** [AvdLee/RocketSimApp#582]
It's tedious to toggle or change launch arguments in Xcode: (Target -> edit scheme -> Run -> Arguments). It would be useful for these (or a new list) to be available in RocketSim. 

A good place for this would be on the action tab. Perhaps under the perform section.

I'd probably rate this as a low priority. My experience is most people don't change launch arguments much. However, if you ever need to change them a bunch, it'd be a great feature to have. So, unless this is easy to add, I'd save it till you really need ideas.

**Comment by AvdLee** [comment]
@joshuabryson thanks for the idea, I recognize the scenario. However, in my case, I change arguments permanently and I want them to be active for debug sessions. If I'm going to implement this in RocketSim, I'd at most allow you to setup configurations per app actions (e.g. action A launches the app with arguments X, Y, Z), but you won't be able to attach Xcode's debugger via a RocketSim app launch.

With that in mind, do you still think it's useful?

Another option would be to replace launch arguments with user-defaults driven settings. I'm considering #345 User Defaults actions which would alternate user defaults into a certain state. For example:

**Action: Enable Premium**
Adjustment: `is_pro = true`

**Comment by joshuabryson** [comment]
Nah, like I said, this is a pretty niche idea. You've probably got bigger / better fish to fry.

Thanks again for the great app! I've just discovered uninstalling the app, huge time saver!!!

**Comment by AvdLee** [comment]
All good, thanks for thinking with me! Feel free to open another issue with any idea you might have 🙏
