### ISSUE TITLE
Can't hide Rocket Sim app from Dock

### ISSUE THREAD

**Issue by KaiOelfke** [AvdLee/RocketSimApp#589]
**Describe the bug**

Before the latest version RocketSim worked as menu bar app only with the floating window next to the simulator. Since the latest update there's always the RocketSim app in the Dock as well. I'd like to have the app only in the menu bar. Or my memory is wrong and the icon also was in the Dock before, in which this can be seen as a feature request.

**To Reproduce**
1. Launch RocketSim and use the menu bar or simulator floating window

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14.6.1
 - Version: 12.11.9

**Additional context**

**Comment by AvdLee** [comment]
You're completely right, something's off! I'll look into fixing this next week 🙏

**Comment by AvdLee** [comment]
This will be fixed in 12.11.11!
