### ISSUE TITLE
Does RocketSim provide any functionality for macOS apps? Or is it iOS(sim)-only?

### ISSUE THREAD

**Issue by dvclmn** [AvdLee/RocketSimApp#590]
Hope this is an appropriate avenue for this question. I've got the feeling I'm missing something obvious, as I've scoured the RocketSim website and combed Google, and haven't been able to find an answer.

There are a number of RocketSim features that sound very handy for my case, however I'm primarily a macOS dev, I rarely create iOS apps. Are any of RocketSim's features provided when running a macOS app from Xcode?

I've just fired up a trial, and I'd love to get clarity on this before I pull the trigger on a yearly sub :)

Cheers.

**Comment by AvdLee** [comment]
@dvclmn sorry for replying late, your trial must be completed! As of now, RocketSim is iOS only. However, I'm a Mac developer myself, and have several ideas already (See #255)

Could you add your ideas to #255? I'm closing this as a duplicate 🙏
