### ISSUE TITLE
12 / 24 hour time

### ISSUE THREAD

**Issue by smithi01** [AvdLee/RocketSimApp#593]
Thanks so much for this app. It is great.

When I set a custom time, it is challenging to change it between a 12 and 24 hour clock. e.g. 9:41 versus 09:41. I can change it by changing the Mac time setting between 12 and 24, then resetting the simulator device, then rebooting the Mac. A toggle in RocketSim or some guidance on how RocketSim decides the format would be great.

This is important for localised screenshots.

**Comment by AvdLee** [comment]
@smithi01 thanks for your request! Can't you just use the 9:41 button that's available?
![CleanShot 2024-10-24 at 08 51 39@2x](https://github.com/user-attachments/assets/cdfed5a6-fad8-4ab8-b482-88b41065bb78)

**Comment by smithi01** [comment]
Thanks for the reply. If 9:41 am was an ok time for my screenshots, then I still don't know how to change between 09:41 and 9:41. I seem to be able to do it with changing the Mac time format then either restarting the computer, erasing the simulator, or other restarts. In my case I want to use different times. (See https://bedsideradio.app) Either way, changing between 12-hour and 24-hour clock is problematic for me. How does RocketSim decide what format to use? Cheers, Ian

**Comment by smithi01** [comment]
Hi again. I have found RocketSim great and I love using it, thank you. If you could give me some clues as to how RocketSim determines whether to use 12-hour or 24-hour time. I could adjust my workflow to suit that, rather trying to change it by trial and error. Cheers, Ian

**Comment by AvdLee** [comment]
Ah, now I get it. RocketSim respects the system setting and has to, as the Simulator uses that too. We can't change that, unfortunately. If you need a leading 0, you'll have to configure your system time settings to a 24-hour clock I'm afraid.

Closing this issue since I can't do anything about it, but feel free to continue the conversation.

**Comment by smithi01** [comment]
Thanks for the response. If RocketSim and the Simulator did respect the system setting that would solve my problem. Unfortunately this is not the case, even after closing and restarting the simulator.  See attached screenshot, in which the system setting is for a 24-hour clock while the simulator and RocketSim are still using a 12-hour clock.

Restarting RocketSim, makes RocketSim show the most current 24-hour clock setting clock in the 'Custom' panel, but the Simulator seems to stay on the clock setting at the time of the last reboot. 

This is starting to look more like a Simulator problem than RocketSim, although when RocketSim is using one time format and the Simulator another, I am finding the 09:41 button stops working. I need to do more testing to confirm this.

For international screenshots my workflow will need to be:
1) Do all the screenshots for App Stores in areas typically using a 24 hour clock (which I usually use)
2) Change the Mac to a 12-hour clock
3) Reboot the Mac and do the remaining screenshots

When I get time (haha), I will try to do some more testing with Simulator and file a bug with Apple if warranted.

Thanks again for a great product.

<img width="766" alt="Screenshot 2024-11-27 at 08 46 15" src="https://github.com/user-attachments/assets/72948db8-63dd-41de-92d2-5bacd8f0abad">
