### ISSUE TITLE
Cannot select developer directory

### ISSUE THREAD

**Issue by jmccance** [AvdLee/RocketSimApp#595]
**Describe the bug**

RocketSim prompts me to select Xcode and grant Developer directory access on launch. After selecting the Developer directory, I get an error pop-up:

> **Can't get access to /Users/jmccance/Library/Developer folder**
>
> Did you pick the correct folder?

Clicking "Try again" and picking the folder again gives the same result, sticking me in a loop that I can't escape without force-quitting the app.

**To Reproduce**

1. Open RocketSim
2. Select Xcode
3. Click "Set Up Permissions"
4. Click "Open"
5. Get error
6. `GOTO 3`

**Expected behavior**

After selecting the Developer directory, I should be able to proceed.

**Screenshots**

![image](https://github.com/user-attachments/assets/e022ba93-8d2b-4a18-810f-2654b31f893f)

![image](https://github.com/user-attachments/assets/f8500d64-794a-4b3a-9e37-7bf78eef5d83)

**Desktop (please complete the following information):**

 - OS: macOS 15.0.1 (24A348)
 - Version: 12.11.12

**Additional context**

Our IT department has us run in non-admin mode most of the time, with a utility to temporarily grant admin permissions. I've tried it both with and without admin on.

**Comment by jmccance** [comment]
I force-quit RocketSim this morning so I could move forward. Just now I relaunched it and it asked me to select Xcode, but didn't ask me to grant access to the Developer directory.

**Comment by AvdLee** [comment]
@jmccance thanks for reporting in, this is a known issue and relates to a bug on macOS Sequoia: https://www.avanderlee.com/swift/security-scoped-bookmarks-for-url-access/#macos-sequoia-failed-to-retrieve-app-scope-key-bug

I'm going to work on a temporary fix today that will solve this issue as much as possible (on a per-session basis)

**Comment by AvdLee** [comment]
I'm also adding the notice in the view itself:

![Image](https://github.com/user-attachments/assets/3135cd41-ffb4-48ab-91cb-1aaeb7cbe524)

**Comment by AvdLee** [comment]
@jmccanceCan you report an issue via Settings → About → Report an Issue? this will give me some more logs to work with!

**Comment by jmccance** [comment]
@AvdLee I wasn't able to access the report tool because of the loop. I wonder if that's something you could add to these prompt screens?

Thanks for the quick fix, though! I'll give it a try once the update comes through.
