### ISSUE TITLE
Remove single guideline 

### ISSUE THREAD

**Issue by vospennikov** [AvdLee/RocketSimApp#598]
Hi! Thank you for the app! 
Please simplify the interface of removing a single guideline.
As a simple solution, it increases the touch area for several points. 
In addition, removing it by right click (or double) would be easier than moving it outside. 

![Screen Recording 2024-10-20 at 14 52 48](https://github.com/user-attachments/assets/3cf67ea0-07d9-4131-8ba7-497efe410345)

**Comment by AvdLee** [comment]
@vospennikov good point! Do you have experience with other apps and how those do it? As in, what would be your ideal solution to this?

Or are the solutions you've suggested the way you'd love to see this solved?

**Comment by AvdLee** [comment]
Closing this as won't do. The right click is following other app's standards on macOS as far as I know.
