### ISSUE TITLE
Issue with syncing linked JSON files

### ISSUE THREAD

**Issue by TheEffekted** [AvdLee/RocketSimApp#60]
**Describe the bug**
I track linked JSON files in Git so I can share the deep links with my team. But whenever I change a deep link in a group using the  Mac app, it doesn't change the corresponding deep link in the linked JSON file. So it appears as if the JSON file isn't linked at all.

**To Reproduce**
1. Create a group and some deep links.
2. Link that group to a JSON file.
3. Mutate the group in some way and see that the linked JSON file isn't changed (git status).

**Expected behavior**
I'd expect the JSON file to update. If I rename a deep link it should be renamed in the linked file.

**Additional context**
It would also be nice if updating the JSON file updates the groups in the apps, but it seems like the linked JSON file isn't the source of truth.

**Comment by AvdLee** [comment]
Thanks for reporting in. The wrong security scope was set and it was read-only. I've fixed this for the upcoming update but it does mean you have to link it again. However, it's going to work!
