### ISSUE TITLE
Airplane mode does not disable the user's internet connection

### ISSUE THREAD

**Issue by Miguelife** [AvdLee/RocketSimApp#600]
**Describe the bug**
Airplane mode does not disable the user's internet connection

**To Reproduce**
Activate airplane mode on rocketsim
Make a http request 
Successful Request

**Expected behavior**
Activate airplane mode on rocketsim
Make a http request 
Request Failed

**Screenshots**
![image](https://github.com/user-attachments/assets/55d22a0a-c68a-4ca3-8eee-a5a27954c5a0)

**Desktop (please complete the following information):**
 - OS: Sequoia
 - Version: 15.0

**Comment by AvdLee** [comment]
@Miguelife Airplane mode blocks requests from within your app using URLSession. Can you share more details on what requests are not being blocked?

**Comment by Miguelife** [comment]
I'm using a package that handles calls from the app, the company I work for forces me to use it, internally it's using URLSession, so I'm not very clear about what may be going on...

The package is public and you can check it out here: https://github.com/fsalom/TripleA
I have the possibility to make modifications to the package if necessary

This is the class Network when we are making authorized requests calling loadAuthorized or unathorized request calling load
`open class Network {
    var baseURL: String = ""
    public let authenticator: AuthenticatorProtocol?
    var additionalHeaders: [String: String] = [:]
    var format: LogFormat!
    var session: URLSession

    public init(baseURL: String = "",
                authenticator: AuthenticatorProtocol? = nil,
                headers: [String: String] = [:],
                format: LogFormat = .full,
                session: URLSession = URLSession.shared) {
        self.authenticator = authenticator
        self.additionalHeaders = headers
        self.baseURL = baseURL
        self.format = format
        self.session = session
    }

    // MARK: -  loadAuthorized
    /**
    Call to protected API adding authorization header and checking for refreshToken if needed

     - Parameters:
        - endpoint: Endpoint with request information
        - type: T of a decodable object
        - allowRetry: Bool in case retry calls is not an option
     - Returns: object of type  `T` already parsed.x
     - Throws: An error of type `CustomError`  with extra info
    */
    open func loadAuthorized<T: Decodable>(this endpoint: Endpoint,
                                           of type: T.Type? = AuthNoReply.self) async throws -> T {
        var modifiedEndpoint: Endpoint = endpoint
        modifiedEndpoint.addExtra(headers: additionalHeaders)
        modifiedEndpoint.addBaseURLIfNeeded(url: baseURL)
        do {
            let request = try await authorize(this: modifiedEndpoint.request)
            Log.thisCall(request, format: format)
            let (data, urlResponse) = try await session.data(for: request)
            guard let response = urlResponse as? HTTPURLResponse else{
                throw NetworkError.invalidResponse
            }
            Log.thisResponse(response, data: data, format: format)
            if response.statusCode == 401{
                try await revokeAccessToken()
                return try await loadAuthorized(this: endpoint, of: type)
            }
            do {
                return try parse(with: data, and: response, for: type)
            } catch {
                Log.thisError(error)
                throw error
            }
        } catch {
            throw error
        }
    }

    // MARK: - load
    /**
    Call to unprotected API

     - Parameters:
        - endpoint: Endpoint with request information
        - type: T of a decodable object
        - allowRetry: Bool in case retry calls is not an option
     - Returns: object of type  `T` already parsed.
     - Throws: An error of type `CustomError`  with extra info
    */
    open func load<T: Decodable>(endpoint: Endpoint,
                                 of type: T.Type? = AuthNoReply.self) async throws -> T {
        var modifiedEndpoint: Endpoint = endpoint
        modifiedEndpoint.addExtra(headers: additionalHeaders)
        modifiedEndpoint.addBaseURLIfNeeded(url: baseURL)
        Log.thisCall(modifiedEndpoint.request, format: format)
        let request = modifiedEndpoint.request
        let (data, urlResponse) = try await session.data(for: request)
        guard let response = urlResponse as? HTTPURLResponse else{
            throw NetworkError.invalidResponse
        }
        do {
            return try parse(with: data, and: response, for: type)
        } catch {
            Log.thisError(error)
            throw error
        }
    }
}`

**Comment by stachon** [comment]
Hi, I purchased RocketSim subscription in hopes that it would help me simulate offline mode. However, the Airplane mode does not work. The app uses URLSession with a little bit of customization (delegate for SSL Pinning). MacOS 15.1, XCode 16.1

**Comment by AvdLee** [comment]
@Miguelife @stachon it sounds like both of you are running into edge cases. RocketSim only blocks network requests for calls made from your app's bundle identifier. 

We need to find out how your requests are attributed for RocketSim to identify them as coming from your apps.

Would it be possible to use an app like Charles Proxy or Proxyman and share me the RAW request metadata?
That way, I can further optimize and fix this.

If you're able to create a small sample project reproducing this issue, that would be even better and a golden path to solving this quickly 🙏

**Comment by AvdLee** [comment]
I found out this issue and solved it for the next major 13.0.0 release.

**Comment by stachon** [comment]
Thanks, will check it later, don't have time to debug it now. I think maybe it is some issue with my system, I tried also Little Snitch which is also a network filter extension at it also does not work sometimes.

**Comment by HugoHeneault** [comment]
> I found out this issue and solved it for the next major 13.0.0 release.

Awesome! Any ETA for it ? ;)

**Comment by AvdLee** [comment]
@HugoHeneault I'm submitting this week, so hoping to release the week after!
