### ISSUE TITLE
Add button-based simulator control

### ISSUE THREAD

**Issue by Miguelife** [AvdLee/RocketSimApp#601]
**Is your feature request related to a problem? Please describe.**
Sometimes navigating with a keyboard and mouse imitating the gestures of the simulator is confusing and tedious.

**Describe the solution you'd like**
Añadir una característica para poder navegar por el simulador con shortcuts y controles de navegación similares a los de Android.

<img width="448" alt="image" src="https://github.com/user-attachments/assets/7b852f55-1f56-4c75-b213-e8cc7911a158">

**Comment by AvdLee** [comment]
@Miguelife thanks for your request. While I get the point, I don't think this is achievable for me to build. Sorry for that!
