### ISSUE TITLE
Network monitor contents are unavailable when the Simulator is paused during debugging

### ISSUE THREAD

**Issue by huckncatch** [AvdLee/RocketSimApp#608]
When my app is paused while debugging (e.g. execution hit a breakpoint in Xcode), the Network Monitor window reverts to its "Rocketsim Connect Integration" view and the previously captured network calls are unavailable.

I'd like to inspect the network calls already captured when my app is paused. This is especially important when debugging network response handling where I need to view the response.

**Comment by AvdLee** [comment]
Great feedback! I'll see what I can do. Currently, I'm pinging RocketSim and as soon as RocketSim stops pinging, I consider it as disconnected.

However, once you've showed how to set up RocketSim, there's no need to show the instructions again. It's better to keep the traffic visible and show a status within that view instead. Totally see where you're both coming from. 

I'll pick this up right away!

**Comment by AvdLee** [comment]
This will be fixed in 12.12.0
