### ISSUE TITLE
What's new is unreadable in light mode

### ISSUE THREAD

**Issue by seanlifetime** [AvdLee/RocketSimApp#610]
**Describe the bug**
Cannot read text when the computer is using light mode

**To Reproduce**
Install the latest version (12.11.16)

**Expected behavior**
Be able to read the what's new notes, all tabs display the text the same

**Screenshots**
Cannot read what's new when using light mode

<img width="900" alt="image" src="https://github.com/user-attachments/assets/25abb8e7-5731-4e52-b53d-3cdf312e2fce">

**Desktop (please complete the following information):**
 - OS: macOS 15.1

**Additional context**
Switching to dark mode fixes the issues...

**Comment by AvdLee** [comment]
Oh boy, ouch! Thanks for letting me know!
