### ISSUE TITLE
Add altitude to locations routes

### ISSUE THREAD

**Issue by HugoHeneault** [AvdLee/RocketSimApp#614]
**Is your feature request related to a problem? Please describe.**
I need the altitude to be filled whilst running a fake location

**Describe the solution you'd like**
Locations from routes should include altitude when mocked

**Describe alternatives you've considered**
Running GPX from XCode but it's far less convenient

**Additional context**
Thank you so much for doing RocketSim 🫶

**Comment by AvdLee** [comment]
Thanks for reporting in, and glad you're enjoying RocketSim!

Unfortunately, there's no way for me to pass in the altitude to location Simulation. The Simulator does not support simulating these 😢

**Comment by HugoHeneault** [comment]
Ha I didn't know that. One day maybe? ;)

Thanks for your reply!
