### ISSUE TITLE
Network monitor is reporting each HTTP request twice

### ISSUE THREAD

**Issue by gaw3** [AvdLee/RocketSimApp#616]
**Describe the bug**
Just started using the network monitor.  Network monitor is reporting each HTTP request twice.

**Expected behavior**
Network monitor reports each HTTP request only once.

**Screenshots**
The following is from the network monitor:
![CleanShot 2024-12-04 at 21 00 39](https://github.com/user-attachments/assets/7ef09203-c7aa-4164-9fe2-d22f46053318)

This a screenshot from an Xcode iPhone 16 Pro running my app.  It uses the `netfox` cocoapod to monitor and report network traffic.  
![Simulator Screenshot - iPhone 16 Pro - 2024-12-04 at 20 57 59](https://github.com/user-attachments/assets/1e81141f-592a-4484-806d-1b0e71091350)

How do I achieve the expected behavior?

**Desktop (please complete the following information):**
 - OS:  Sequoia 15.1.1 (24B91)
 -RocketSim:  12.12.0 (248)

**Comment by gaw3** [comment]
Well, crud.  The network monitor works as expected when I disable `nexfox` in the app, which I should have thought to do prior to opening a bug.  I am guessing that the network monitor catches the original request and reports it.  This request is then caught & reported by `netfox`, then resent.  Then, the network monitor catches the resend and reports that as well.  That's why the timestamps of dupe requests in the left pane of the network monitor are 1 ms apart.  This is just my working theory.

**Comment by AvdLee** [comment]
@gaw3 yes, you're completely right. It's because both apps use swizzling underneath.
For now, there's no other option than disabling one or another. You can also see if you can install Netfox without swizzling (manually connecting URLSession). Hope that helps!
