### ISSUE TITLE
Verify PRO status when recovered from early adoption

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#62]
**Describe the bug**
Some report the watermark is still visible while being promoted to PRO on Big Sur after being an early RocketSim adapter.

**To Reproduce**
1. Install Big Sur
2. Upgrade to PRO from early adoption
3. See preferences screen showing is pro
4. See watermark being visible

**Expected behavior**
Watermark should hide

**Desktop (please complete the following information):**
 - OS: Big Sur
 - Version 11.0.1 beta

**Additional context**
Reported by François

**Comment by frboulais** [comment]
Even with a lifetime subscription:
<img width="912" alt="Screenshot 2020-11-23 at 09 01 04" src="https://user-images.githubusercontent.com/4943835/99939476-6b9a7500-2d6a-11eb-8ac9-af71212a1af2.png">
The rendered video still shows the RocketSim watermark:
<img width="543" alt="Screenshot 2020-11-23 at 09 04 37" src="https://user-images.githubusercontent.com/4943835/99939686-ebc0da80-2d6a-11eb-8690-74c58cbd56d5.png">
No big deal, but look like a bug 😀

**Comment by AvdLee** [comment]
@frboulais I've verified the implementation and it's looking all good. You do have to disable the watermark yourself after becoming pro. You can do this from the general tab.

Did the watermark still appear after doing that?

**Comment by AvdLee** [comment]
Closing this as it seems to be fixed. Feel free to comment for a reopen!
