### ISSUE TITLE
Add support for rotated recordings

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#63]
**Is your feature request related to a problem? Please describe.**
Recording a device which is in, for example, landscape, doesn't record nicely.

**Describe the solution you'd like**
Support rotated device recording.

**Comment by frboulais** [comment]
The generated video doesn't take the device rotation into account, that could be a really nice bonus!
<img width="806" alt="Screenshot 2020-11-23 at 09 08 55" src="https://user-images.githubusercontent.com/4943835/99939948-85888780-2d6b-11eb-81d0-2b5b48f4c464.png">

**Comment by AvdLee** [comment]
This is fixed in the upcoming release!
