### ISSUE TITLE
The screen size for iPad 12.9'' 3rd is not accepted by ASC

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#64]
**Describe the bug**
A screen recording for the iPad 12.9'' 3rd edition is not accepted by App Store Connect as a preview video.

**To Reproduce**
1. Open the iPad 12.9'' 3rd simulator
2. Create a recording
3. Upload to App Store Connect

**Expected behavior**
The recording should be accepted

**Additional context**
Reported by François

**Comment by frboulais** [comment]
App Store Connect requires a **1200x1600** or **1600x1200**:
<img width="1097" alt="Screenshot 2020-11-23 at 09 10 51" src="https://user-images.githubusercontent.com/4943835/99940088-ca142300-2d6b-11eb-93e4-3b91ad5b498c.png">
But the generated video is **2048x2732**
<img width="464" alt="Screenshot 2020-11-23 at 09 12 13" src="https://user-images.githubusercontent.com/4943835/99940196-fc258500-2d6b-11eb-9bfe-755d150f8ef5.png">

**Comment by frboulais** [comment]
Same bug observed with 3rd generation (the resolution should also be accepted)

**Comment by AvdLee** [comment]
Confirmed this issue, we're not respecting https://help.apple.com/app-store-connect/?lang=en/#/dev4e413fcb8 for every simulator. Working on a fix now!

**Comment by AvdLee** [comment]
This is fixed in the next release.

**Comment by AvdLee** [comment]
![image](https://user-images.githubusercontent.com/4329185/103481586-3dce3480-4ddc-11eb-8900-ad78a34bc629.png)
