### ISSUE TITLE
Screen recording colors are off in some cases

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#65]
**Describe the bug**
See this tweet: https://twitter.com/RecursiveSwift/status/1331990645980839936?s=20
Although this is not created using RocketSim, RocketSim produces the same recording. The question is whether we can do anything about this.

**Comment by atrinh0** [comment]
Please see mp4 and gif renditions of the same clip.

The top right blue button, and yellow backgrounds lose their colors, and the cream skin tones of the emojis also become white.

https://user-images.githubusercontent.com/16542463/103415500-39a2dc80-4b7a-11eb-90ab-e96ae4856c1b.mp4

![RocketSim Recording - iPhone 12 mini - 2020-12-31 15 06 31](https://user-images.githubusercontent.com/16542463/103415494-360f5580-4b7a-11eb-85f4-bcadc69cc389.gif)

Project used: https://github.com/atrinh0/scrumdinger

**Comment by AvdLee** [comment]
It's a bit clearer to me now:
- MP4 give the expected result using the right colors
- GIF lose colors

This is, however, kind of expected as I've lowered the color size of gives. However, now that GitHub supports MP4, I don't have to be too strict with GIF sizing anymore and I can increase the number of colors in GIFs. I'll see if that works.

**Comment by AvdLee** [comment]
So, the reason this is happening is that converting alpha layers into a GIF seems hard. I've not found a solution yet but it's likely alpha layers that turn wrong here. I'll see if I can do anything about this.

**Comment by atrinh0** [comment]
Thank you for looking into this. 🙏🏻

Just in case it helps, I have modified my code to move away from alpha/opacity to make the colors lighter programmatically. The results are the same. 🧐

https://github.com/atrinh0/scrumdinger/commit/48853ddb23ff3bd855dc1aaac57930b7b53dd665

https://user-images.githubusercontent.com/16542463/103443502-c4a5d480-4c57-11eb-8711-4133fd98a55f.mp4

![RocketSim Recording - iPhone 12 mini - 2021-01-01 17 28 43](https://user-images.githubusercontent.com/16542463/103443510-e4d59380-4c57-11eb-8ab2-bcf22024163d.gif)

**Comment by AvdLee** [comment]
Interesting! I've found out that most of the conversion works, colors are great in-between frames, until I use `CGImageDestinationAddImage` to add it to a GIF destination.

This thread seems related: https://stackoverflow.com/questions/44960714/ios-colors-incorrect-when-saving-animated-gif

In other words; it seems like the colors are good until I add them to a GIF destination. I'll continue my journey, I'm curious now! 😂

**Comment by AvdLee** [comment]
The easiest fix turned out to be to lower the size of the GIF itself to allow it to contain more colors. This is the final result which seems acceptable to me.

![image](https://user-images.githubusercontent.com/4329185/103480945-f34ab900-4dd7-11eb-9905-9d33ae021324.png)

I'll think about adding a setting in the future for more control.

Either way, fixed in the next version!
