### ISSUE TITLE
Save-Button doesn't save

### ISSUE THREAD

**Issue by crabucate** [AvdLee/RocketSimApp#67]
Pressing the Save-Button doesn't save the gif to the specified location. The gif is just gone.
I can copy and paste. That works.

**Comment by AvdLee** [comment]
Might be related to #57. What is your location setting showing?

![image](https://user-images.githubusercontent.com/4329185/103442002-80fc9c00-4c52-11eb-9dba-9279ae97957c.png)

**Comment by crabucate** [comment]
I changed the folder. Now it works. Thank you!
