### ISSUE TITLE
Login for App Store is asked on every launch

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#69]
- Relaunch your Mac
- See that the login screen is prompted

**Comment by brunodelgado** [comment]
A small addition to this issue: I also have to restore purchase to become pro again every time I restart my Mac.

**Comment by AvdLee** [comment]
@brunodelgado yeah, that's definitely related to this. I'm hoping to get started fixing this soon!

**Comment by brunodelgado** [comment]
Great!
I'm a big fan of this project, excelent work. 🏆

**Comment by AvdLee** [comment]
I have a hard time finding out the cause of this. I've added extra logging in a minor update which will help me take the next steps in the following release.

**Comment by AvdLee** [comment]
Finally found [the cause](https://github.com/codykerns/PurchasesHelper/commit/4239afb49fd287d346c46610d5c6c3141a22b58a#diff-25e2732643b4f1b121ea8622f2f77fbfe4ae71727b94c882f137ed770d683308).

My code is heavily inspired on the above one and this seems to be exactly the issue. Fixed in the next release!
