### ISSUE TITLE
Dedicated GPU is required

### ISSUE THREAD

**Issue by laevandus** [AvdLee/RocketSimApp#72]
**Describe the bug**
I made some recordings and now Activity Monitor's Energy tab reports that RocketSim requires dedicated GPU. 

**To Reproduce**
1. Launch RocketSim 3.2.1 (40) and have a simulator open
2. Click on start recording
3. Stop recording
Since now on, RocketSim requires dedicated GPU (which increases battery usage). That is probably what we do not want.

**Expected behavior**
RocketSim never requires dedicated GPU or only while processing the recording.

**Screenshots**
![rocketsim](https://user-images.githubusercontent.com/1469907/104984240-b1657800-5a51-11eb-8fec-4d8d2af12f95.jpeg)
![rocketsim2](https://user-images.githubusercontent.com/1469907/104984235-af031e00-5a51-11eb-8039-086f1068ed89.jpeg)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.1
 - Xcode 12.3
 - Macbook Pro (15", 2017)

**Additional context**
I have an external display connected and MBP is in clamshell mode.

**Comment by AvdLee** [comment]
> RocketSim never requires dedicated GPU or only while processing the recording.

I would assume the same so I need to look into this. I might have some retain cycles causing issues.
Thanks for the report!

**Comment by laevandus** [comment]
Not a really big deal but something to improve in the future. Otherwise it is really convenient tool to have.

**Comment by AvdLee** [comment]
I have improved a bit of code and like to close this issue as "fixed in the next release", which will be 3.2.2.

**Comment by laevandus** [comment]
Cool, thanks for looking into this.
