### ISSUE TITLE
Deeplinks list order is randomized

### ISSUE THREAD

**Issue by kristiyandobrev** [AvdLee/RocketSimApp#73]
**Describe the bug**
Deeplinks list order is randomized every time I open the app from the menu bar

**To Reproduce**
1. Go to MacOS menu bar
2. Click on 'RocketSim
3. Select an app (observe the deeplinks order)
4. Repeat the previous 3 steps
4. The deeplinks order is different compared to the previous time.

**Expected behavior**
I would say that the most logical behaviour would be to have the list sorted alphabetically

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.1
 - Version [3.2.1]

**Comment by AvdLee** [comment]
The order can be changed by drag and drop. There was, however, no backup order which I now updated to use alphabetical order. This is fixed in the next release.
