### ISSUE TITLE
Error when recording Watch Simulator

### ISSUE THREAD

**Issue by djavan-tagheuer** [AvdLee/RocketSimApp#76]
**Describe the bug**
Unable to record Apple Watch simulator

**To Reproduce**
1. Open an Apple Watch Simulator
2. Start recording
3. An error saying that Recording has failed and that I need to check my Command Line Tools version.

**Expected behavior**
Recording should (and did) work on a Watch simulator

**Screenshots**
<img width="348" alt="Screenshot 2021-01-26 at 17 18 16" src="https://user-images.githubusercontent.com/43636702/105872614-e5650e00-5ffa-11eb-8ca5-4f7e6e1efaf3.png">

**Desktop (please complete the following information):**
 - OS: 11.1
 - Version 3.2.1 (40)
 - Xcode version: 12.3 (12C33)

**Additional context**
This used to work before.
I did `xcode-select --install` and reinstalled from [here](https://developer.apple.com/download/more/?=for%20Xcode) the Command Line Tools. This did not change the behavior.
Thanks in advance for any advice on how to fix the problem 🙏

**Comment by AvdLee** [comment]
Thanks for the report, @djavan-tagheuer. So far, I haven't added support for recording on the watch, or Apple TV. Only iPhone and iPad are supported.

I'll see if I can add this in the future.

_Upvote this comment if you're interested in this feature too_

**Comment by djavan-tagheuer** [comment]
It's weird, I'm sure I've recorded the watch a few month ago with RocketSim.
Thanks for your feedback. Having the Watch supported would be great!

**Comment by AvdLee** [comment]
@djavan-tagheuer that could definitely be true! I've updated the code and optimized it in one of the last releases. One thing I did is filtering out those devices as I don't support them.

It does make me realize it might actually be simple to support them so I'll see what I can do!

**Comment by AvdLee** [comment]
This is fixed in the next release.
