### ISSUE TITLE
Can not save recordings

### ISSUE THREAD

**Issue by matsmats** [AvdLee/RocketSimApp#77]
I start the recording and stops it. 
The Save or Copy dialog is shown. 
I choose Save, the dialog is gone but there is no recording in the chosen file location.
I have restarted the RocketSim app.
I have updated the location where to save the files.

 - OS: macOS BigSur Version 11.1
 - RocketSim version: 3.2.1 (40)

**Comment by AvdLee** [comment]
Thanks for reaching out @matsmats! Can you email me a diagnostics report? There's a button in the 'general' settings page at the bottom.

It would help me solve this more quickly!

**Comment by matsmats** [comment]
I have pressed the Send Diagnostics button, but I am not sure what it does. Google Chrome flashes and then I am back to the settings view. Have you received an email? I am not using any built in mail app.

**Comment by AvdLee** [comment]
> I am not using any built in mail app.

Ah, damn, I think I don't support custom mail apps yet! That's too bad.
It should normally open up the email composer with the diagnostics report attached.

I do need it to take next steps as this feature is currently working on my own machine running the same setup 🤔

**Comment by matsmats** [comment]
I have got hold of the report and sent an email.

**Comment by AvdLee** [comment]
This will be fixed in 3.2.2
