### ISSUE TITLE
Deep links convert # to %23

### ISSUE THREAD

**Issue by DeveloperMaris** [AvdLee/RocketSimApp#78]
**Describe the bug**
All deep links, which contains the # symbol (for the url fragment) is encoded as _%23_, and that actually makes the URL not work correctly.

**To Reproduce**
Precondition:
1. Dynamic Links are provided with `apple-app-site-association` configuration like this:
```
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "XXXXXXXXXX.com.example.test",
                "paths": ["/foo"]
            },
        ]
     }
}
```
2. App associated domains configuration:
```
applinks:example.com?mode=developer
```
_developer mode is optional_

1. Create a deep link with URL - https://example.com/foo/#bar
2. Install the app
3. Try to open the deep link with the provided URL

**Expected behavior**
App opens and detects the _fragment_ as "bar"

**Actual behavior**
Simulator does not open the app, but opens the Safari with URL - https://example.com/foo/%23bar

**Desktop (please complete the following information):**
 - OS: iOS
 - Simulator OS version: 14.3
 - RocketSim version: 3.2.1 (40)

**Additional context**
Similar issue happens for this link as well - https://example.com/foo#bar
Also, the main host name is changed to _example.com_ because of private details.

**Comment by AvdLee** [comment]
A typical encoding issue which should be easy to fix. Thanks for reaching out!

**Comment by AvdLee** [comment]
Thanks again for the detailed report. This is fixed in the next release.
