### ISSUE TITLE
Add sound recording to the recording features

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/RocketSimApp#8]
Right now, the recordings won't contain any sound. It would be a great feature if sound can be recorded as well.

**Comment by hotngui** [comment]
Definitely need sound in order to be useful for my apps.

**Comment by AvdLee** [comment]
@hotngui would you be OK if you need to change your system output to a virtual audio device called "RocketSim" before each recording? As in, would that already be great to have?

It's not really easy to record Simulator audio!

**Comment by hotngui** [comment]
Yes that would be acceptable.

On May 4, 2020, at 12:59 AM, Antoine van der Lee <notifications@github.com> wrote:

﻿

@hotngui<https://github.com/hotngui> would you be OK if you need to change your system output to a virtual audio device called "RocketSim" before each recording? As in, would that already be great to have?

It's not really easy to record Simulator audio!

**Comment by massimobio** [comment]
This would be great!
Perhaps [BlackHole](https://github.com/ExistentialAudio/BlackHole) could be used to route system audio to RocketSim.

**Comment by AvdLee** [comment]
@massimobio yeah, thanks for pointing that out! I've had it on my list to try out, indeed. I wonder whether I can make this work without the need of any user audio adjustment. Also, I would prefer to record audio from the simulator only, not also from any other app causing sounds 🤔 

It's not an easy one to tackle. Ideally, I would be able to record sound from a specific window.

**Comment by AvdLee** [comment]
It took a long time, but this will be implemented in 9.5.0!
