### ISSUE TITLE
Add bezel to recordings

### ISSUE THREAD

**Issue by pdamonkey** [AvdLee/RocketSimApp#80]
Having the option to apply a relevant bezel to the recordings could make the output look more realistic.

**Comment by AvdLee** [comment]
That would be pretty cool indeed! I'll think more about this 🙂

**Comment by AvdLee** [comment]
It's requested here too but for screenshots: https://developer.apple.com/forums/thread/131139?page=2

**Comment by AvdLee** [comment]
This is now available in beta! 
https://testflight.apple.com/join/ORz3QWRv
