### ISSUE TITLE
Delete deeplink group button nearly invisible

### ISSUE THREAD

**Issue by mac-cain13** [AvdLee/RocketSimApp#81]
**Describe the bug**
When in the Deeplinks settings screen I can't see a delete button for the groups next to the `+` to add a group. There is a tiny '-' that I can click, but I seriously thought it was dust on my monitor at first.

**To Reproduce**
1. Go to 'Preferences...' -> 'Deeplinks' tab
2. Next to the '+' button to create a group is the remove button is nearly invisible

**Expected behavior**
A clear remove button to delete a group.

**Screenshots**
![Schermafbeelding 2021-02-01 om 22 58 17](https://user-images.githubusercontent.com/618233/106523341-3edca980-64e1-11eb-9ad6-d529c2f21566.png)

![Schermafbeelding 2021-02-01 om 22 58 17](https://user-images.githubusercontent.com/618233/106523662-bb6f8800-64e1-11eb-8405-9206389007be.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.1 (20C69)
 - Version 3.2.2 (41)

**Additional context**
🚀

**Comment by AvdLee** [comment]
@mac-cain13 oops! Thanks for reporting in!

**Comment by AvdLee** [comment]
Fixed in the next release!
