### ISSUE TITLE
Deeplink groups sorting messes up sometimes

### ISSUE THREAD

**Issue by mac-cain13** [AvdLee/RocketSimApp#82]
**Describe the bug**
The sorting in of the deeplink groups in preferences is sometimes incorrect. Resulting in another group name selected in the left (master) pane than is visible in the right (detail) pane.

**To Reproduce**
1. Go to 'Preferences...' -> 'Deeplinks'
2. Hit '+' 2 times (so you have "Group 0" and "Group 1"
3. Rename "Group 0" to "Group 2" (hit enter to commit change)
4. Close the Preference window
5. Again, go to 'Preferences...' -> 'Deeplinks'
6. (The preselected group on the left is consistent with the right) Select another group, the state now becomes inconsistent

**Expected behavior**
The selected group on the left should correspond with the details presented right.

**Screenshots**
Movie time! 🎥 

https://user-images.githubusercontent.com/618233/106524818-616fc200-64e3-11eb-86f3-0f36f9dde011.mov

**Desktop (please complete the following information):**
 - OS: macOS 11.1 
 - Version 3.2.2 (41)

**Additional context**
Not that when you rename a group while in the inconsistent state, the problem fixes itself.

**Comment by AvdLee** [comment]
Ai, great find! And thanks for the recording, that helps a lot. I'll fix this in the next release.

**Comment by AvdLee** [comment]
This should be fixed in 4.1.0
