### ISSUE TITLE
Hight CPU usage when the tool isn't doing any work

### ISSUE THREAD

**Issue by Ariandr** [AvdLee/RocketSimApp#85]
**Describe the bug**
After recording several videos, I stopped using the app, but its CPU utilization was high.

**To Reproduce**
Launch RocketSim, record simulator screen, save as MP4 and GIF, leave the app to be in top tray.

**Expected behavior**
App shouldn't use so much of CPU time.

**Screenshots**
<img width="800" alt="Screenshot at Feb 17 14-53-14" src="https://user-images.githubusercontent.com/13591333/108207403-5eeea880-7130-11eb-8610-8ce5b8fad798.png">

It happenss when the app is just in the tray not doing anything:
<img width="223" alt="Screenshot at Feb 17 14-53-25" src="https://user-images.githubusercontent.com/13591333/108207411-61e99900-7130-11eb-89a1-a00accf3b263.png">

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Version: RocketSim 3.4.1

**Additional context**
If you close the app and launch it again it won't use CPU. Only after recordings.
I noticed the issue because the fans on my Macbook Pro 2015 became loud.

**Comment by AvdLee** [comment]
You're not the first to report this. I thought I fixed it but I clearly didn't! Must be something with retaining processes or exporting logic.

I'll have a look, thanks for the issue!

**Comment by AvdLee** [comment]
I had some classic non-weak delegate retain cycles. This should be fixed in the next release!
