### ISSUE TITLE
How to buy the Lifetime Version (as stated in the MacAppStore)?

### ISSUE THREAD

**Issue by dhf** [AvdLee/RocketSimApp#89]
In the Appstore In-App Purchase descriptions there is stated a "RocketSim Lifefime" option. How can i buy this Lifetime Option?

1. Go to Settings -> Pro
2. No "Lifetime" Option is visible, only monthly and yearly subscription

Lifetime Option as stated in the Mac Appstore
<img width="565" alt="image" src="https://user-images.githubusercontent.com/4035583/110924732-af69b800-8322-11eb-945b-b36a9682d08d.png">

Purchase Options in the App:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/4035583/110924851-cf997700-8322-11eb-93d7-3ac55d140f4f.png">

**Comment by AvdLee** [comment]
@dhf thanks for reaching out. Unfortunately, Lifetime is no longer available from within the app and will be removed from that listing too.
