### ISSUE TITLE
Recording is not working on Big Sur 11.0.1 after the latest update

### ISSUE THREAD

**Issue by DKalachniuk** [AvdLee/RocketSimApp#91]
**Describe the bug**
I'm clicking start recording but it is not happening 

**To Reproduce**
Big Sur 11.0.1
Latest version of the app
Just click start recording button 
**Expected behavior**
Recording will start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 11.0.1

**Additional context**

**Comment by getbiks** [comment]
Yup. I am using xcode 11.6 and Big Sur 11.1
When I click on record, nothing happens. I have given recording permission to the application.

System Specs:
MacBook Pro (Retina, 15-inch, Mid 2014)
2.5 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3

**Comment by AvdLee** [comment]
@DKalachniuk which version of Xcode are you using?

Unfortunately, I've had to introduce a fix earlier which requires Xcode 12.3 and up. @getbiks I'm pretty sure that's the issue in your case.

**Comment by getbiks** [comment]
Yup.. I am using Xcode 11.6. I will try with Xcode 12.3+ 
Thanks.

**Comment by DKalachniuk** [comment]
> @DKalachniuk which version of Xcode are you using?
> 
> Unfortunately, I've had to introduce a fix earlier which requires Xcode 12.3 and up. @getbiks I'm pretty sure that's the issue in your case.

Indeed, I have Xcode 12.2. Thanks

**Comment by AvdLee** [comment]
Alright, great! Closing this as resolved but feel free to reopen if it didn't work.

Sorry for the inconvenience; Xcode 12.4 introduced a way to improve the recordings in such way I wanted to completely depent on it as it will be better long-term!
