### ISSUE TITLE
Possibility to hide the new Start recording and Drop an image views

### ISSUE THREAD

**Issue by matsmats** [AvdLee/RocketSimApp#93]
I would like to be able to hide the new Start recording and Drop an image views from the preferences.

I will not use the Drop image view so I would like to hide it.

**Comment by AvdLee** [comment]
Makes total sense! This is high on my list to fix in an upcoming update.

**Comment by matsmats** [comment]
May I ask what the Touches and Remove Watermark do in the Start Recording view? I can not click on anything, should I be able to that?

**Comment by AvdLee** [comment]
@matsmats if you're pro, you can use these settings to show touches in the recording and remove the watermark label in the exported video. You can read more about it here: https://www.avanderlee.com/workflow/rocketsim-comparing-designs/

The upcoming update will contain a fix for this!

![image](https://user-images.githubusercontent.com/4329185/111871525-dc554500-898a-11eb-9e9d-eb9d3762f642.png)

**Comment by matsmats** [comment]
I am a PRO but I have only question marks in the view as you see in the image

![Screenshot 2021-03-20 at 20 32 41](https://user-images.githubusercontent.com/1843153/111883421-79c86d00-89bb-11eb-87bc-03d4d96ec914.png)

**Comment by AvdLee** [comment]
Yes, these are fixed in the upcoming release, currently in review. Once that version is out, it will make more sense as checkmarks show up! 🙂
