### ISSUE TITLE
App screen(s) are hidden by simulator after rotate

### ISSUE THREAD

**Issue by Devepre** [AvdLee/RocketSimApp#94]
**Describe the bug**
App screen(s) are hidden by simulator after rotate of simulator from portrait to landscape.

**To Reproduce**
1. Launch simulator of your choice in portrait mode.
2. Rotate simulator to landscape mode.
3. Observe simulator screen overlaps RocketSim screen(s).

**Expected behavior**
RocketSim screen(s) should be visible.

**Screenshots**
![Portrait mode](http://i.piccy.info/i9/5de6b6116bf285db721a0d5f3937c7b8/1616153189/176771/1421701/35637Portrait.jpg)
![Portrait mode](http://i.piccy.info/i9/a3d8abed48684aa76075cd0744224801/1616153249/104174/1421701/Landscape.jpg)

**Desktop:**
 - OS: macOS Bis Sur 11.2.2 / iOS 14.4
 - Version 4.0.1 (50)

**Comment by AvdLee** [comment]
@Devepre thanks for the awesome bug report, really appreciate the effort you did here! In return, I've fixed this directly and you can expect it in an update early this week.
