### ISSUE TITLE
Can't start recording

### ISSUE THREAD

**Issue by tiarnann** [AvdLee/RocketSimApp#95]
**Describe the bug**
Recording is not working at all. I hit "Start Recording" in status bar and recording does not start. Even in the latest version of RocketSim if I hit "Start Recording" in floating panel it does not work either. 

**To Reproduce**
I don't have any steps to reproduce as it does not happen on my other Macbook. I've added all version information below with as much additional info as I have.

**Expected behavior**
When I hit record it should start recording.

**Screenshots**
![rocket-sim-not-recording-bug](https://user-images.githubusercontent.com/10522081/112193545-e3d15400-8bff-11eb-85cf-02a85989a4b2.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H524)
 - Rocket Sim Version: 4.0.2 (52)
 - Xcode Version: Version 12.0 (12A7209)
 
 ** Additional information **
- I've tried a variety of Simulators
- I am not using an external display
- I've restarted my machine multiple times
- I've uninstalled RocketSim and reinstalled it
- Screen recording is allowed in Privacy Settings
<img width="780" alt="Screenshot 2021-03-23 at 17 20 51" src="https://user-images.githubusercontent.com/10522081/112189785-46c0ec00-8bfc-11eb-86b1-0cd97ad2a2e4.png">

**Comment by AvdLee** [comment]
@tiarnann thanks for reporting! This is a known issue, Xcode 12.4 or up is required for recording. I'm still looking into ways for making that more clear.

Xcode 12.4 sends out a message when recording is started which is needed for RocketSim.

For my understanding, why aren't you updated to Xcode 12.4? It might give me reason to add support to Xcode 12, which I don't have right now.

**Comment by tiarnann** [comment]
> Xcode 12.4 or up is required for recording

Oh that's super surprising. Has this always been the case? I think I've used RocketSim with this version of Xcode nearly 100 times already

> For my understanding, why aren't you updated to Xcode 12.4? It might give me reason to add support to Xcode 12, which I don't have right now.

This is my work machine and we don't immediately upgrade to the latest version of Xcode as there are typically some hiccups along the way.

**Comment by AvdLee** [comment]
> Oh that's super surprising. Has this always been the case? I think I've used RocketSim with this version of Xcode nearly 100 times already

Definitely not. In fact, I _can_ make it work with older Xcode versions but I figured there isn't really a reason for developers to stay on Xcode < 12.4 as they can upgrade to 12.4 without issues (afaik). So I decided to rather optimise the recording behavior.

I'll keep this issue open for others if they run into this, but it's not a priority for me to add backwards compatibility as this will be an issue that solves itself on the short term.

**Comment by tiarnann** [comment]
> I'll keep this issue open for others if they run into this, but it's not a priority for me to add backwards compatibility as this will be an issue that solves itself on the short term.

Gotcha! Sounds good. 

In my opinion, it would be beneficial to communicate this to the user. When a selected Xcode version is not supported, I think adding a ⛔️ flag to the settings would help. Also displaying an alert when the user tries to start recording using an unsupported Xcode version.

**Comment by AvdLee** [comment]
@tiarnann makes total sense! I'll see what I can do 🙂

**Comment by xyreryp** [comment]
Hey @AvdLee I am on Xcode 12.2 and Catalina. Before updating to version 4.0.2(52), it worked just fine. But I updated RocketSim yesterday and the recording functionality stops working

**Comment by AvdLee** [comment]
@xyreryp yeah, indeed! It confirms what we discuss in this issue. Let me know if it didn't work after updating Xcode! 🙂

**Comment by AvdLee** [comment]
Closing this as an update of Xcode will fix this automatically.
