### ISSUE TITLE
Timer for starting/stopping the recording

### ISSUE THREAD

**Issue by BenjiMandel** [AvdLee/RocketSimApp#96]
**Is your feature request related to a problem? Please describe.**
The feature request I have will fix the problem of making promo videos for the app store too long. The limit is(as far as I remember) 30 seconds.
Also, sometimes the part you want to record will only come after a few clicks, so a timer so that the recording will start in X seconds would be nice too

**Describe the solution you'd like**
I would like the ability to
Quickly set a timer (maybe as a checkbox saying: keep videos at app store length limit) in the start recording view. You could also provide the user with the option to set a custom duration when the timer should stop. 

Then, when you want to have specific animations recorded, but not the other parts of navigation to that animation(when you fixed a particular animation and you want to add to the pull request), it could be a nice add on to add a start timer so that the user can click on the trigger for the animation as soon as the recording starts and doesn't need to edit the video afterwards.
**Describe alternatives you've considered**
For the end timer, I have not seen an alternative solution. But for start time, almost all recording software has it built it(like Camera, or QuickTime 
**Additional context**

**Comment by AvdLee** [comment]
Would this be solved if you were able to trim the video afterwards?

**Comment by BenjiMandel** [comment]
Yes, that could also be a good fix. 

I do think an option for a timer with the app store length limit could he good aside to the trim feature.

**Comment by AvdLee** [comment]
I'm closing this in favor of the trim functionality. Automatically trimming might result in losing valuable recording content, so I rather make that a manual process.
