### ISSUE TITLE
The app crashes/closes after opening a  deeplink from the top item "Open ....".

### ISSUE THREAD

**Issue by Ariandr** [AvdLee/RocketSimApp#97]
**Describe the bug**
The app crashes/closes after opening a deeplink from the top item "Open ....".

**To Reproduce**
1. Open RocketSim
2. Copy a link into pasteboard
3. Click "Open ..."
4. Deeplink opens, RocketSim closes

**Expected behavior**
RocketSim should stay open

**Screenshots**
<img width="254" alt="Screenshot at Mar 24 15-31-02" src="https://user-images.githubusercontent.com/13591333/112318669-f73ef680-8cb5-11eb-8148-780776b94af3.png">

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - RocketSim 4.0.2

**Comment by AvdLee** [comment]
This will be fixed in 4.1.0
